### ISSUE TITLE
Move from Linux Standard Base to native systemd intefaces for setup scripts

### ISSUE THREAD

**Issue by brendank310** [Bareflank/hypervisor#139]
Most distributions are moving toward deprecation of LSB to use native systemd interfaces. We should update our setup scripts to reflect these changes.

**Comment by spockfish** [comment]
I've checked Ubuntu 14.04 and that has already got an /etc/os-release as well.

**Comment by rianquinn** [comment]
This has been fixed here: https://github.com/Bareflank/hypervisor/pull/349
