### ISSUE TITLE
[Question] Incorrect check for VM-execution control "use TPR shadow"

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#168]
Section 26.2.1.1, Volume 3C of the [Intel manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf) states in the eighth bullet down,
> If the "use TPR shadow" VM-execution control is 1 and the "virtual-interrupt delivery" VM-execution control is 0, bits 31:4 of the TPR threshold VM-execution control field must be 0.

The next bullet states

> The following check is performed if the "use TPR shadow" VM-execution control is 1 and the "virtualize APIC accesses" and "virtual-interrupt delivery" VM-execution controls are both 0: the value of bits 3:0 of the TPR threshold VM-execution control field should not be greater than the value of bits 7:4 of VTPR (see Section 29.1.1).

The function that implements [the check](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/src/vmcs/src/vmcs_intel_x64_check_controls.cpp) is vmcs_intel_x64::check_control_tpr_shadow_and_virtual_apic.  It currently checks bits 31:4 of the TPR threshold only if TPR shadow is 1 and virtual-interrupt delivery is 1.  Shouldn't the check occur when TPR shadow is 1 and virtual-interrupt delivery is 0?

Likewise bits 3:0 of TPR threshold are checked against bits 7:4 of VTPR only if TPR shadow, virtual-interrupt delivery and virtualize APIC accesses are all 1 when the manual states the latter two should be 0.

**Comment by rianquinn** [comment]
Yup... the code we have there is wrong.

**Comment by rianquinn** [comment]
@connojd please close this once the unit test is complete and merged

**Comment by rianquinn** [comment]
Fixed here: https://github.com/Bareflank/hypervisor/pull/209
