### ISSUE TITLE
[Question] Physical-address width in check_control_enable_ept_checks

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#170]
The check 
```cpp
if ((eptp & 0xFFFF000000000000) != 0 || (eptp & 0x0000000000000F80) != 0)
       throw std::logic_error("bits 11:7 and 63:48 of the eptp must be 0");
```
in `vmcs_intel_x64::check_control_enable_ept_checks` essentially hard-codes the physical address width.  Would it be better to call `is_physical_address_valid(eptp)` instead?

**Comment by rianquinn** [comment]
Checking to make sure that the physical address is valid would take care of the upper bits, but it would not take care of the lower bits 11:7. You could break this up into two checks so that there isn't duplication with the physical address width.

**Comment by rianquinn** [comment]
@connojd please close this once the unit test is complete and merged

**Comment by rianquinn** [comment]
Fixed here: https://github.com/Bareflank/hypervisor/pull/209
