### ISSUE TITLE
git command error

### ISSUE THREAD

**Issue by huddy1985** [Bareflank/hypervisor#171]
>cd ~/
>git https://github.com/bareflank/hypervisor.git
>cd ~/hypervisor
>git checkout -b v1.0.0

>./tools/scripts/setup_<platform>.sh

Here the git command should be:
git clone https://github.com/bareflank/hypervisor.git

BTW how could I send the patch to this project?

**Comment by rianquinn** [comment]
Yeah, that's wrong (it's clearly missing "clone"). To create a patch, you need to create a fork of the project, make the change and create a Pull Request. The documentation for this can be found in:

https://github.com/Bareflank/hypervisor/blob/master/CONTRIBUTING.md

If you need any help feel free to ask. Also, if you run into trouble, it's an easy fix on my end if need be.
