### ISSUE TITLE
#define ⇒ enum?

### ISSUE THREAD

**Issue by elfring** [Bareflank/hypervisor#175]
Would you like to replace more defines for constant values by [enumerations](https://en.wikipedia.org/wiki/Enumerated_type#C_and_syntactically_similar_languages) to stress their relationships?
* [ENTRY_ERROR_…](https://github.com/Bareflank/hypervisor/blob/1a6e4833328aa9d27614715d27b1bfdef192c06f/include/error_codes.h#L56)
* [VMM_…](https://github.com/Bareflank/hypervisor/blob/1a6e4833328aa9d27614715d27b1bfdef192c06f/include/driver_entry_interface.h#L34)

**Comment by rianquinn** [comment]
Would love too. You up for providing a PR? Both of those files are compiled by both C++ (GCC, Clang) but also by the OS driver compilers (i.e. GCC, Visual Studio), so keep a couple things in mind:

- The enums need to compile in all of the different environments
- They need to remain 64bit ints (we type cast based on the compiler). 

But yeah, anything to remove more macros is a plus 😄

**Comment by rianquinn** [comment]
I gave this a shot and there are two issues that I ran into.
- GCC/G++ wants to use "int" for enums, so 0x8xxxxxxxxxxxxxxxLL.... does not work as it's really defined as 64bit int. To fix this issue we would need to redefine the error codes which I don't want to do at the moment
- GCC/Nmake specifically don't like the use of LL literals in the kernel which makes it difficult to set the error codes the way they are. Currently we use a cast to get around this which we cannot use in an enum definition

#define makes the most sense for now until we can come up with a better solution to works across all of the compilers for both userspace and the kernel. That being said... if there are any other uses of #define that we can get rid of, I would love to entertain possible solutions.
