### ISSUE TITLE
Improve iostream usage

### ISSUE THREAD

**Issue by RicoAntonioFelix** [Bareflank/hypervisor#180]
According to [SL.io.50](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#SS-io) in the [C++ Core Guidelines](https://github.com/isocpp/CppCoreGuidelines) the use of `std::endl` should be replaced with `'\n'` for performance reasons...

Therefore [bfendl](https://github.com/Bareflank/hypervisor/blob/master/include/debug.h#L59) should be updated...

**Comment by rianquinn** [comment]
Fixed

**Comment by RicoAntonioFelix** [comment]
:+1:
