### ISSUE TITLE
[RFC]: VMCall Interface

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#182]
In the next couple of days we will be implementing a VMCall interface that can be used by users of Bareflank to quickly and easily talk to the hypervisor. Our goal here is to keep this as simple as possible so that it can be extended in the future without causing issues with API changes

Since we intended to work with ARM in the future, we cannot VMCall from userspace as this is not supported on ARM (sad story). Instead, we will provide an IOCTL interface so that userspace applications like BFM can VMCall to the hypervisor. 

One issue with supporting both ARM and Intel is the total number of registers. To support this in a sane way, I propose we use the ABIs are our guide. On Intel, the System V ABI defines the order of each register. We can define a struct that has 32 registers (i.e. r0 -> r31) and the ABI will tell use which register in our struct belongs to which physical register (i.e. r0 -> rax, r1 -> rdx, etc...). From here, the driver can use this information to produce a VMCall, and the only "arch" specific code will be the register decoding. This should produce a simple VMCall interface that can be used generically. 

In addition to register decoding, Bareflank will need to reserve a register for defining the type of VMCall that is occurring. At the moment, I envision three different types of VMCalls, but this could be expanded in the future:
- raw register VMCall (minus reserved registers)
- data VMCall
- unit test VMCall

The raw register VMCall would do nothing more than send raw register values to the hypervisor. This is likely to be the most used VMCall. The data VMCall would send in / out pages to the hypervisor to handle. The unit test VMCall can be used to unit test code inside the hypervisor (e.g. libcxx). To ensure future compatibility, I would like to reserve r0 and r1 (rax / rdx on Intel) for Bareflank, and extensions can use all of the registers for whatever they want. 

Thoughts?

To start, I would like to add raw register and unit test support to BFM, and the data VMCall can be added later (its a little more complicated as it has to map / unmap memory, and we need a clean way to send binary / string data via BFM).

**Comment by brendank310** [comment]
Overall, this sounds pretty reasonable to me; creating a high and low bandwidth option for exchanging data with the hypervisor is going to be required for all non-trivial feature additions. I see preventing calls from userspace to be a feature, to allow whatever policy enforcement over vmcall access that exists in the operating system to be leveraged. I don’t agree that unit tests is a separate category of vmcall, it more than likely falls into one of the other two categories, for different test cases. But if the statement about the 3 types is about reserving the values for the functional use of the register, page sharing, and unit tests I have no objections.

**Comment by rianquinn** [comment]
Yeah, it's just reserving an enum for r0. And yeah, sharing in/out data is really just going to be page sharing in the end. The harder part is how to get data into BFM so that we can then share the page. At the moment, my thought was something like 

./bfm vmcall data < cat file.txt
./bfm vmcall data < echo "<json>"

But I have to play around to see how feasible this will be.

**Comment by rianquinn** [comment]
Ok so this is what I have come up with

```
struct vmcall_registers
{
    uintptr_t r0;
    ...
    uintptr_t r31;
}
```

IOCTL Interface:

```
#define IOCTL_VMCALL _IOR(BAREFLANK_MAJOR, IOCTL_VMCALL_CMD, struct vmcall_registers *)
```

Commands:
```
// Send Raw Registers
// In:
r0 == VMCALL_REGISTERS
r1 == 0
r2 ... r31 == XXX

// Out:
r2 ... r31 == XXX
```
```
// Send Unit Test 
// In:
r0 == VMCALL_UNITTEST
r1 == unittest_index
r2 ... r31 == 0

// Out:
r2 == 1 for pass, 0 for fail
```
```
// Send String
// In:
r0 == VMCALL_STRING
r1 == id
r2 == addr
r3 == size

// Out:
r2 == 0 on success, otherwise error_code
```
```
// Send Binary File
// In:
r0 == VMCALL_BINARY
r1 == id
r2 == addr
r3 == size

// Out:
r2 == 0 on success, otherwise error_code
```

Send string and send binary are very similar and are basically just doing page sharing. The difference is the VMM will know to interpret as a string. They both send an id to the VMM that can be used to identify the string / binary when coupled with a raw register vmcall (for example, when starting a guest VM, you would send possibly some JSON that describes the VM, and a file image). Duplicate ids are allowed (no enforcement) which makes them optional as well. The unit test commands will be wrapped in a macro so that they have to be enabled to be used. 

BFM will have:
```
./bfm vmcall registers <r2> <r3> ... <r31>
./bfm vmcall unittest <r1>
./bfm vmcall string <string>
./bfm vmcall binary <filename>
```

With respect to the raw registers vmcall, you only have to put the registers that you want, but they have to be in order. For example, 

```
./bfm vmcall registers 1 2 3    // r2 == 1, r3 == 2, r4 == 3
./bfm vmcall registers 0 0 0x10    // r2 == XXX, r3 == XXX, r4 == 0x10
```

In this example, if you want to set r4 only, you have to set r2 and r3 to something.

**Comment by brendank310** [comment]
Each call should include a magic number, which will be checked on the VMM side.

**Comment by rianquinn** [comment]
I like that, so the commands would be:

```
// Send Raw Registers
// In:
r0 == VMCALL_REGISTERS
r1 == MAGIC_NUMBER
r2 ... r31 == XXX

// Out:
r2 ... r31 == XXX
```
```
// Send Unit Test 
// In:
r0 == VMCALL_UNITTEST
r1 == MAGIC_NUMBER
r2 == unittest_index
r3 ... r31 == 0

// Out:
r2 == 1 for pass, 0 for fail
```
```
// Send String
// In:
r0 == VMCALL_STRING
r1 == MAGIC_NUMBER
r2 == id
r3 == addr
r4 == size

// Out:
r2 == 0 on success, otherwise error_code
```
```
// Send Binary File
// In:
r0 == VMCALL_BINARY
r1 == MAGIC_NUMBER
r2 == id
r3 == addr
r4 == size

// Out:
r2 == 0 on success, otherwise error_code
```

**Comment by tklengyel** [comment]
I would advise adding versioning to each vmcall that gets matched (and enforced) on the VMM side. There should just be a single vmcall that can be issued without an interface version attached, which queries the VMM for the interface version it supports (say VMCALL_INTERFACE_VERSION). This will help a lot with avoiding compatibility issues of running applications built for older/newer version of Bareflank.

Also, instead of VMCALL_BINARY and VMCALL_STRING I think VMCALL_DATA should be more flexible approach, where the rest of the information gets defined on the shared memory page using a pre-defined ABI.

**Comment by rianquinn** [comment]
I like the idea of having a specific version number vmcall for sanity. With respect to BINARY vs STRING, I like the idea of a single data VMCALL as it's more flexible, but BFM itself should maintain a DATA and STRING specific call specifically to make it easier to get string commands to the hypervisor. I would like to add JSON support to the Extended APIs in the future which could drive commands to the hypervisor directly from BFM like:

```
./bfm vmcall string JSON_COMMAND "{\"get_reg\":\"rax\"}" -> "{\"rax\":\"0x10\"}"
```

So with that said, here is my proposed changes. Every new version we will generate a new magic number, and of course, this could always be set by the user as well (for defensive applications, users would likely want their own custom magic numbers as a nice to have, added PITA). The hypervisor will use it's interface and be written defensively to only accept incoming VMCalls that make sense. In other words, rejection only occurs from the magic number. If a magic number is valid, fuzzing needs to be done to ensure that the interface can withstand messed up ABIs. 

Also, one thing that I didn't make clear is that if the CPU doesn't have 31 registers (like ARM and Intel currently), the registers that it doesn't support are ignored / undefined.

```
// Get Version Info
// In:
r0 == VMCALL_GET_VERSION
r1 == MAGIC_NUMBER
r2 ... r31 == 0

// Out:
r2 == hypervisor version
r3 == vmcall interface version
r4 ... r31 custom version (may be used by extensions)
```
```
// Send Raw Registers
// In:
r0 == VMCALL_REGISTERS
r2 == MAGIC_NUMBER
r2 ... r31 == XXX

// Out:
r2 ... r31 == XXX
```
```
// Send Unit Test 
// In:
r0 == VMCALL_UNITTEST
r1 == MAGIC_NUMBER
r2 == unittest_index
r3 ... r31 == 0

// Out:
r2 == 1 for pass, 0 for fail
```
```
// Send / Receive Data
// In:
r0 == VMCALL_DATA
r1 == MAGIC_NUMBER
r2 == id
r3 == in_type
r4 == in_addr
r5 == in_size
r6 == out_type
r7 == out_addr
r8 == out_size

// Out:
r2 == 0 on success, otherwise error_code
```

Note that VMCALL_DATA requires virtually contiguous memory for both in / out, and the hypervisor will map this address using the current guest CR3, perform whatever operation it should, and then unmap on exit (yeah.. that will be fun to code 😄 ). Also, the type fields will have a set of predefined type fields with the first half of the 64bit field belonging to Bareflank Repos (hypervisor, Extended APIs and the soon to come HyperKernel), while the second half can be used for user defined types. 

With respect to BFM, it will use VMCALL_DATA for both STRING and BINARY calls, but provide a different user interface thats appropriate. Keep in mind that BFM is a developer tool to keep things sane. If your doing something more complicated, you might want to consider making your own app and use the IOCTL interface instead. For example, the HyperKernel repo will likely have it's own userspace app for starting / stopping VMs that leverages JSON to keep things simple without overcomplicating BFM in the Bareflank repo which is designed to be minimalistic.

**Comment by tklengyel** [comment]
FYI transmitting full 64-bit values with json can be problematic for C applications, most json parsers don't actually support it. This has been a problem when trying to read full VAs out of JSON files generated by Rekall (the solution was to just truncate 64-bit values to 48-bit when stored in JSON and then make them canonical when reading them out). It's a PITA.

**Comment by rianquinn** [comment]
@tklengyel Shouldn't be a problem with BFM -> VMM as the VMM would use a modified version of:

https://github.com/nlohmann/json

with float/double removed which already supports 64bit unsigned ints. That being said, JSON commands would only be intended as easy ways to use BFM to send commands, but all commands would have an alternative method for calling the API that can be done from a driver without the need for string manipulations. Originally I wanted one way to do this but JSON is not good for drivers, and raw registers is not great for the command line. Having both provides sane ways to do this generically, without overcomplicating the VMM (the JSON part would just decode to raw registers).

**Comment by rianquinn** [comment]
Ok, so here is the interface file that I have so far. I had to make a couple of changes:
- the id field was changed to a uuid field (takes two registers instead of one). This way, uuids can be used which provide better guarantees on uniqueness. 
- the register mapping is based on System V, but it is not the same as rsp and rbp were removed from the mapping as we really don't want to use these registers (no simple way to save off the existing registers prior to vmcall if these are used). 
- Added an index field to the versions vmcall so that it acts more like cpuid, and can be extended in the future. 

```
#ifndef VMCALL_INTERFACE_H
#define VMCALL_INTERFACE_H

#pragma pack(push, 1)

#ifdef __cplusplus
extern "C" {
#endif

/*
 * VMCall Magic Number
 *
 * Defines a magic number that can be defined by the user to uniquely identify
 * both the version of the user as well as the VMM. Note that this value will
 * change with each release of Bareflank, but should probably be manually set
 * when creating production code.
 */
#ifndef VMCALL_MAGIC_NUMBER
#define VMCALL_MAGIC_NUMBER 0xB045EACDACD52E22
#endif

/*
 * VMCall Version
 *
 * Define the version of this VMCall ABI. Note that unlike the magic number,
 * this number only changes when this file changes.
 */
#define VMCALL_VERSION 1

/*
 * VMCall Opcode
 *
 * Defines the vmcall being made. Note that these are generic vmcall opcodes,
 * and they made be used to create actual commands to the hypervisor. For
 * example, the registers vmcall could contain user defined instructions
 * while the data vmcall could also contain JSON formatted instructions.
 *
 * Each opcode is defined below. Note that these might change as part of
 * an updated. It's up to the user to ensure that versions match correctly.
 */
enum vmcall_opcode
{
    /*
     * Versions
     *
     * Returns version information from the hypervisor which can be used by
     * users of the vmcall interface to ensure that their code is compatible
     * with the VMM.
     *
     * @note: indexes 0x0000000000000000 -> 0x7FFFFFFFFFFFFFFF are reserved
     *     for Bareflank. The remaining indexes may be used by custom
     *     extensions for version information
     *
     * In:
     * r0 = VMCALL_VERSIONS
     * r1 = VMCALL_MAGIC_NUMBER
     * r2 = index
     *
     * Out (index == 0):
     * r2 = VMCALL_VERSION
     *
     * Out (index == 1):
     * r2 = BAREFLANK_VERSION_MAJOR
     * r3 = BAREFLANK_VERSION_MINOR
     * r4 = BAREFLANK_VERSION_PATCH
     */
    VMCALL_VERSIONS = 1,

    /*
     * Raw Registers
     *
     * Provides a means to send to the VMM, raw register values, and
     * return raw register values. This is a wrapper around your basic vmcall,
     * consuming the reserved registers in the process for ABI compatibility
     *
     * In:
     * r0 = VMCALL_REGISTERS
     * r1 = VMCALL_MAGIC_NUMBER
     * r2 = xxx
     * ...
     * r31 = xxx
     *
     * Out:
     * r2 = xxx
     * ...
     * r31 = xxx
     */
    VMCALL_REGISTERS = 2,

    /*
     * Data
     *
     * Provides a means to send and receive binary data (page sharing). With
     * this vmcall, an in and out buffer are provided. The VMM will map in
     * both buffers, perform whatever operation it should, and then unmap the
     * buffers. The type field must be provided for the input buffer, and it
     * defines what type of data is being provided. The VMM will return data
     * in the output buffer, and set the output type based on whatever
     * operation it performed. The size is in bytes, but the VMM will map
     * complete pages. If the size of the buffer is not a multiple of a page,
     * the VMM will have access to data outside the bounds of the buffer
     * (which may be fine depending on the use case). The uuid field is provided
     * as a means to identify the data being sent / received. Specifically,
     * this field can be paired with the registers vmcall to ensure that
     * consecutive vmcalls have the proper data. For example, if an operation
     * takes more than one vmcall to perform, and software on the CPU is
     * threaded, the uuid field provides the VMM with a means to handle when
     * more than one vmcall becomes interlaced. Note that the uuid field is
     * optional.
     *
     * In:
     * r0 = VMCALL_DATA
     * r1 = VMCALL_MAGIC_NUMBER
     * r2 = uuid1 (bits 0 -> 63)
     * r3 = uuid2 (bits 64 -> 127)
     * r4 = in_type (vmcall_data_type)
     * r5 = in_addr (addr of virtually contiguous buffer)
     * r6 = in_size (size of virtually contiguous buffer)
     * r7 = out_type (vmcall_data_type)
     * r8 = out_addr (addr of virtually contiguous buffer)
     * r9 = out_size (size of virtually contiguous buffer)
     *
     * Out:
     * r2 = 0 == success, error code otherwise
     */
    VMCALL_DATA = 3,

    /*
     * Unit Test
     *
     * This vmcall is used to unit test software inside the VMM. For example,
     * for Bareflank to ensure that supported portions of libc++ actually work
     * inside the VMM, unit testing must be performed in the VMM itself. This
     * vmcall does that.
     *
     * @note: indexes 0x0000000000000000 -> 0x7FFFFFFFFFFFFFFF are reserved
     *     for Bareflank. The remaining indexes may be used by custom
     *     extensions for their own unit tests
     *
     * In:
     * r0 = VMCALL_VERSIONS
     * r1 = VMCALL_MAGIC_NUMBER
     * r2 = index
     *
     * Out:
     * r2: 0 == success, otherwise the unit tested failed.
     */
    VMCALL_UNITTEST = 10,
};

/*
 * VMCall Data Type
 *
 * Defines the different data types for data vmcall.
 *
 * @note: types 0x0000000000000000 -> 0x7FFFFFFFFFFFFFFF are reserved
 *     for Bareflank. The remaining types may be used by custom
 *     extensions to define their own data types
 */
enum vmcall_data_type
{
    VMCALL_DATA_STRING = 1,
    VMCALL_DATA_BINARY = 2,
};

/*
 * VMCall Registers
 *
 * Defines a structure that stores each register. The register names are
 * generic so that they can be used by different CPU architectures.
 *
 * Intel:
 * r0 = rax
 * r1 = rdx
 * r2 = rcx
 * r3 = rdx
 * r4 = rdi
 * r5 = rsi
 * r6 = r8
 * r7 = r9
 * r8 = r10
 * r9 = r11
 * r10 = r12
 * r11 = r13
 * r12 = r14
 * r13 = r15
 * r14 = undefined
 * ...
 * r31 = undefined
 *
 * ARM:
 * <TBD>
 */
struct vmcall_registers
{
    uintptr_t r0;
    uintptr_t r1;
    uintptr_t r2;
    uintptr_t r3;
    uintptr_t r4;
    uintptr_t r5;
    uintptr_t r6;
    uintptr_t r7;
    uintptr_t r8;
    uintptr_t r9;
    uintptr_t r10;
    uintptr_t r11;
    uintptr_t r12;
    uintptr_t r13;
    uintptr_t r14;
    uintptr_t r15;
    uintptr_t r16;
    uintptr_t r17;
    uintptr_t r18;
    uintptr_t r19;
    uintptr_t r20;
    uintptr_t r21;
    uintptr_t r22;
    uintptr_t r23;
    uintptr_t r24;
    uintptr_t r25;
    uintptr_t r26;
    uintptr_t r27;
    uintptr_t r28;
    uintptr_t r29;
    uintptr_t r30;
    uintptr_t r31;
};

#ifdef __cplusplus
}
#endif

#pragma pack(pop)

#endif
```

**Comment by josephsharkey** [comment]
Not sure how I feel about eliminating userspace VMCALLs. I see the security benefit (but it relies on filtering in the OS), but there could be performance implications depending on what you're trying to do. VMWare worked really hard to trap straight to the hypervisor to avoid extra world switches (user->kernel->hyp->kernel->user as compared to user->hyp->user); they wrote some papers a while ago discussing all the extra performance they got by doing that. It isn't always applicable, but it depends on what you're trying to use it for. It seems like leaving the specification open to optionally supporting userspace VMCALLs on the arch's that support it may be a good idea if you're planning to do anything performance intensive with it.

Otherwise it sounds good.

**Comment by rianquinn** [comment]
@josephsharkey so yeah, Bareflank itself will not check which ring the vmcall came from, so as long as you stick to the above interface, it will not care where the vmcall came from. Bareflank will simply provide an IOCTL for a vmcall so that you can have the OS bounce the vmcall for you in the event that you are supporting both Intel and ARM. If your use case only supports Intel, you could vmcall from user space without an issue. Likewise, defensive extensions of bareflank could check rflags and drop vmcalls from user space if so desired.

**Comment by ranok** [comment]
Is there value in providing the ability to limit the number of registers copied and sent in the VMCALL? For high-frequency calls, copying all 32 registers may be unneeded and slower than providing the ability to have a struct field num_regs to limit the copying to registers and back to memory...

**Comment by rianquinn** [comment]
@ranok yeah, we could probably do that. It would mean that we would consume 3 register for the raw register command

```
r0 = VMCALL_REGISTERS
r1 = VMCALL_MAGIC_NUMBER
r2 = num_regs
r3 ... r31 = xxx
```

On x86_64 (and from what I can tell ARM as well) that would leave 10 general purpose registers.

Thoughts?

**Comment by rianquinn** [comment]
@ranok do we have any numbers on the performance impact of a vmcall with all of the registers vs only a few. The only reason I as is adding num_regs (now that I'm looking at it) will likely overcomplicate the interface as we would basically need a separate function for each number of registers since it has to coded in assembly. Furthermore, the VMM has to save off the entire register state on all VM Exits anyways so your already looking at a performance hit for the VMCall, a couple of registers likely will not make a huge difference, even if they are called a lot. I would be more concerned about the need for vmread / vmwrite to RIP / RSP than saving some registers unused registers

**Comment by rianquinn** [comment]
I think one thing we are missing is a VMCALL_EVENT, which passes an event number and that's it. I also think that this is a good compromise with respect to Jacob's concern about speed. 

```
r0 = VMCALL_EVENT
r1 = VMCALL_MAGIC_NUMBER
r2 = index
```

**Comment by rianquinn** [comment]
Ok, so I'm working on this again. I was able to merge my old code with the huge re-write that is underway, and it's working great. 

I have all of this working, minus mapping in guest memory from user space. The mapping part is not the hard part (it's just a matter of walking the current CR3, and then adding the same mapping to the VMM's CR3), the hard part is the virtual memory management. To that end, I provided a PR that re-wrote the memory manager a third time to provide a generic memory pool that could be used for heap memory, the page pool, and virtual memory management. So all that is left is defining where to put the virtual memory. 

Here is my thought (and I think @brendank310 thought about this too). Each OS that we support (which is 64bit) uses canonical addressing where the memory given to the hypervisor is in so called "kernel memory" which is 0xFF..... We need to reserve a block of virtual memory dedicated towards mapping. My thought is to use the so called "user memory" which is 0x00..... So we could start at say 1MB in, and allocate a chunk of virtual memory space for mapping, and then all mapping occurs there. 

Thoughts? @ktemkin @tklengyel @brendank310 @josephsharkey

**Comment by rianquinn** [comment]
I'm almost done with this (should have "hello world" being mapped into the hypervisor in the next hour or so). One thing that is needed is scoped virtual memory mappings as this code has to basically map in a physical address, read some data, and release the mapping. To this end, I think it would make sense to create the following:

```cpp
bfn::unique_map_ptr<T> p = bfn::make_unique_map<T>(phys_addr);
```

This would take the physical address to map as it's param. Since I changed the memory pool code to use a template class, we now have a virtual memory pool that we can alloc space from. It has no backing memory in RAM, it's just a number, and we need to take the result and tell the memory manager to map the virt -> phys. So this code would do the alloc, and map in the constructor and it's destructor would unmap and free. 

The above code would be designed to mimic `std::unique_ptr`, with a couple of additions:
- Instead of taking a size, it will take the physical address and will always be the size of a page (it's a mapping, so you get page granularity). 
- It will have a function to return a span of the memory. A lot of the time, the memory that is mapped in is an array, so getting a span makes a lot of sense. 
- Will not support the "[]" array syntax when allocating (i.e. allocating an array) as we are not allocating RAM so it doesn't make a lot of sense. 

In the future I envision adding the following as well:
```cpp
auto p = bfn::make_unique_map<T>(phys_addr, length);   // only works for physically contiguous memory
auto p = bfn::make_unique_map<T>(list);   // works for non-contiguous memory, takes a std::vector of std::pairs (phys addr and length).
```

And then of course at some point we will need to implement all of the above but with the reference counted `std::shared_ptr` version. 

Thoughts?
@brendank310 @RicoAntonioFelix

**Comment by rianquinn** [comment]
Ok, here's my status. Most of the code is done. Here is what the exit handler looks like specifically for handling a VMCALL_DATA vmcall:

```cpp
void
exit_handler_intel_x64::handle_vmcall_data(vmcall_registers &regs)
{
    switch (regs.r04)
    {
        case VMCALL_DATA_STRING_UNFORMATTED:
        case VMCALL_DATA_STRING_JSON:
        {
            auto str = bfn::make_unique_map_x64<char>(regs.r05, vmcs::guest_cr3::get(), regs.r06);
            bfdebug << "received string: " << str.get() << bfendl;

            break;
        }

        case VMCALL_DATA_BINARY_UNFORMATTED:
            bfdebug << "received binary data of size = " << regs.r06 << bfendl;
            break;

        default:
            break;
    }

    regs.r07 = VMCALL_DATA_NONE;
    regs.r08 = 0;
    regs.r09 = 0;
}
```

As you can see, mapping in the data is simple, and uses a pattern similar to `std::unique_ptr` for mapping memory. I have added three different constructors:

```cpp
unique_map_ptr_x64(integer_pointer phys, attr_type attr);
unique_map_ptr_x64(const std::vector<std::pair<integer_pointer, size_type>> &list, attr_type attr);
unique_map_ptr_x64(integer_pointer virt, integer_pointer cr3, size_type size, attr_type attr);
```

And of course there are `bfn::make_xxx` versions of these to simplify things (they default to read/write maps). All of these spit out a virtually contiguous memory range that can be used to access the mapped region, and when they go out of scope, they unmap / free this memory. The first constructor allows you map in a single page. The second allows you to map both physically contiguous and non-contiguous memory ranges (similar to an MDL in Windows). The third allows you to map a virtually contiguous memory range given an existing CR3 (which you can see is used in the above example to map in the Host OS memory range, which actually comes from the BFM user space process if your using that). 

The only issue that came up was what to do about TLB flushing. This class performs the flush for you on your local CPU (sadly unlike ARM, Intel does not have a global TLB flush). For this reason, if you want to share mapped memory with another CPU, you will have to manually flush the TLB (I provide a function to do that), or copy the memory into malloc'd memory which is already mapped to all of the cores. Although this is a pain, IPIs are worse and I would like to avoid them if possible.

**Comment by rianquinn** [comment]
I have completed the mapping work. Just have to get through a bunch of testing now (but at least the unit tests for the mapping code are complete). Here is the code:

https://github.com/rianquinn/hypervisor/blob/vmcall_interface/bfvmm/include/memory_manager/map_ptr_x64.h

There are three different constructors:
```cpp
unique_map_ptr_x64(integer_pointer vmap, integer_pointer phys, attr_type attr = map_read_write);
unique_map_ptr_x64(integer_pointer vmap, const std::vector<std::pair<integer_pointer, size_type>> &list, attr_type attr = map_read_write);
unique_map_ptr_x64(integer_pointer vmap, integer_pointer virt, integer_pointer cr3, size_type size, attr_type attr = map_read_write);
```

They allow you to do the following:
- Map a single virtual page to a single physical page
- Map a physically contiguous / non-contiguous memory range by provide a list of physical ranges (very similar to an MDL on Windows)
- Map a virtual address to a physically contiguous / non-contiguous memory range given an existing virtual address, size and CR3 (great for mapping guest memory into the VMM)

Also keep in mind that you will likely use the `bfn::make_unique_map_x64` functions instead of directly using the map class as the `make` functions allocate virtual address space for you, and encapsulate the alloc/free code in the event of an exception. 

Am I missing anything? My hope is that we won't need more than this while working on the Extended APIs which will add a lot of EPT APIs. 

Also, if anyone wants to give this code a quick review I would appreciate it 😄
