### ISSUE TITLE
Missing Page Modification Log check

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#183]
From section 26.2.1.1 of the [Intel manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf):

> If the "enable PML" VM-execution control is 1, the "enable EPT" VM-execution control must be 1.

This check, along with the check that the PML address is a 4KB-aligned physical address, is absent in vmcs_intel_x64_check_controls.cpp

**Comment by rianquinn** [comment]
Yeah, that's a bug. They should be added.

**Comment by rianquinn** [comment]
@connojd please close this once the unit test is complete and merged

**Comment by rianquinn** [comment]
Fixed here: https://github.com/Bareflank/hypervisor/pull/209
