### ISSUE TITLE
Incorrect event injection instruction length check

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#185]
From section 26.2.1.3 from the [Intel manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf):

> If the interruption type is software interrupt, software exception, or privileged software exception, the
VM-entry instruction-length field is in the range 0–15. A VM-entry instruction length of 0 is allowed only if IA32_VMX_MISC[30] is read as 1; see Appendix A.6.

Should we read the MISC msr to make sure that a length of 0 isn't allowed?  Currently `check_control_event_injection_instr_length_checks` throws a `logic_error` if the length is 0. I noticed that IA32_VMX_MISC_MSR isn't in intrinsics_intel_x64.h so it would need to be added.

**Comment by rianquinn** [comment]
Yeah, we can add that. I would put that in your PR for the control checks.

**Comment by connojd** [comment]
Ok I was going to include fixes for each issue I find in the control checks in the PR

**Comment by rianquinn** [comment]
Awesome 😄

**Comment by rianquinn** [comment]
@connojd please close this once the unit test is complete and merged

**Comment by rianquinn** [comment]
Fixed here: https://github.com/Bareflank/hypervisor/pull/209
