### ISSUE TITLE
[Question]: Deleting cross compiler documentation

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#187]
Way back when we first started the project, we put together some cross compiler documentation that was to be used by developers to hand create the cross compilers. This process is scripted now, and would be insane to document now that we also support docker, and will in the next coming weeks support Clang//LLVM. 

So the question is... does anyone have an issue with me deleting this documentation? It will always be available in the version 1.0 tag (even though it is out-of-date in that tag too) just in case people want to refer back to it.

**Comment by connojd** [comment]
Fine with me..I've only ever used the script :)
