### ISSUE TITLE
[Question] VM-entry checks related to SMM

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#188]
The last two checks (bullet points) in section 26.2.1.3 of the [Intel manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf) are 

> If the processor is not in SMM, the “entry to SMM” and “deactivate dual-monitor treatment” VM-entry controls must be 0.

and

> The “entry to SMM” and “deactivate dual-monitor treatment” VM-entry controls cannot both be 1.

seem to be missing from `vmcs_intel_x64_check_controls.cpp`.  Should these be implemented as well?

**Comment by rianquinn** [comment]
No, these checks are not needed right now. That being, I would love to demo these someday 😄
