### ISSUE TITLE
Windows Broken

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#213]
Windows appears to be broken in a couple of different ways:
- Cygwin just did an update which causes more of the GSL code to complain during compilation. We actually contributed strnlen functionality to the GSL specifically for cygwin and it appears that we will need to do the same thing for wcsnlen
- Somehow the IOCTL for write got reversed in our Clang Tidy PR, and as a result, BFM it unable to provide the driver with module information, resulting in BFM failing to load the hypervisor. This is a simple fix that hopefully will not happen again
- The TLS work appears to be killing Windows (BSOD). This doesn't seem to happen as much on real hardware, which allowed this to sneak though during testing as it's a race condition. Specifically, the us of FS seems to make Windows very mad if an interrupt fires while the hypervisor is being loaded. We are investigating different approaches to solve this which include: don't use FS, which would break support for `thread_storage` in the future, or disable interrupts while loading the hypervisor which might be the better approach (if it works). 

In either case, we hope to have Windows support fixed in the very near future.

**Comment by rianquinn** [comment]
I tried disabling interrupts and that didn't help, which is similar to a Linux bug I saw a long time ago, so for now we will have to continue to support interrupts while we launch the VMM. 

So... that means that we cannot touch GS or FS while we load, which is pretty annoying. The Exit Handler can use GS/FS without issue, just not the loader. I will try to draft up a proposal on how I would like to fix the issue today as I believe the TLS implementation is a little buggy how it's implemented today anyways, so I think a new design is in order. 

This all being said, Windows is broken until we get this fixed so I will try to clean this up as fast as possible.

**Comment by ktemkin** [comment]
Looks like it's not just Windows. Picking up Bareflank again, I frequently get a kernel panic while executing pieces of the loader:

```
#make load
<snip>
[  328.419691] [bareflank]: IOCTL_ADD_MODULE_LENGTH: succeeded
[  328.419705] [bareflank]: common_add_module [4]: #intrinsics.so
[  328.419706] [bareflank]:     addr = ffffc900036b9000
[  328.419707] [bareflank]:     size = 0000000000006008
[  328.419707] [bareflank]: IOCTL_ADD_MODULE: succeeded
<snip>
#make start
[  328.858407] BUG: unable to handle kernel paging request at 00007fb969151600
[  328.858510] IP: [<ffffc900036bcea4>] 0xffffc900036bcea4
[  328.858536] PGD 6d9c1067 PUD 67c2d067 PMD 790c8067 PTE 800000006b961067
[  328.858566] Oops: 0001 [#1] PREEMPT SMP
[  328.858587] Modules linked in: bareflank(O) xfrm_user xfrm_algo xt_addrtype br_netfilter xt_CHECKSUM iptable_mangle ipt_MASQUERADE dm_thin_pool nf_nat_masquerade_ipv4 dm_persistent_data dm_bio_prison iptable_nat nf_nat_ipv4 dm_bufio nf_nat libcrc32c crc32c_generic nf_conntrack_ipv4 nf_defrag_ipv4 xt_conntrack nf_conntrack loop ipt_REJECT nf_reject_ipv4 dm_mod xt_tcpudp tun bridge stp llc ebtable_filter ebtables ip6table_filter ip6_tables iptable_filter cfg80211 fuse vmw_vsock_vmci_transport vsock uvcvideo videobuf2_vmalloc videobuf2_memops videobuf2_v4l2 videobuf2_core intel_powerclamp coretemp kvm_intel kvm irqbypass crct10dif_pclmul crc32_pclmul crc32c_intel ghash_clmulni_intel ttm aesni_intel drm_kms_helper snd_ens1371 snd_ac97_codec aes_x86_64 lrw gf128mul drm joydev glue_helper ablk_helper cryptd
[  328.858917]  ppdev videodev intel_rapl_perf ac97_bus vmw_balloon gameport psmouse snd_rawmidi snd_seq_device btusb btrtl input_leds snd_pcm btbcm btintel led_class bluetooth pcspkr evdev mousedev media mac_hid rfkill syscopyarea snd_timer e1000 i2c_piix4 sysfillrect snd soundcore sysimgblt fb_sys_fops vmw_vmci intel_agp intel_gtt shpchp nfit battery parport_pc parport fjes acpi_cpufreq tpm_tis tpm ac button sch_fq_codel ip_tables x_tables ext4 crc16 jbd2 mbcache hid_generic usbhid hid sd_mod sr_mod cdrom ata_generic pata_acpi uhci_hcd mptspi scsi_transport_spi ehci_pci ata_piix ehci_hcd libata mptscsih serio_raw atkbd usbcore libps2 scsi_mod usb_common mptbase i8042 serio
[  328.859220] CPU: 1 PID: 3999 Comm: bfm Tainted: G           O    4.7.4-1-ARCH #1
[  328.859257] Hardware name: VMware, Inc. VMware Virtual Platform/440BX Desktop Reference Platform, BIOS 6.00 07/02/2015
[  328.860037] task: ffff88006daab900 ti: ffff880079774000 task.ti: ffff880079774000
[  328.860804] RIP: 0010:[<ffffc900036bcea4>]  [<ffffc900036bcea4>] 0xffffc900036bcea4
[  328.861580] RSP: 0018:ffffc90003890bc0  EFLAGS: 00010293
[  328.861974] RAX: 0000000000000000 RBX: 0000000000000000 RCX: 8000000000000001
[  328.862369] RDX: ffffc9000377e730 RSI: ffffc90003a69894 RDI: 0000000000000000
[  328.862759] RBP: ffffc90003890be8 R08: 0000000000000535 R09: ffffffffa08253a7
[  328.863144] R10: 000000000000006d R11: ffff8800787b1200 R12: 00007fb969151600
[  328.863525] R13: ffffc900036805ed R14: 0000000000000001 R15: 0000000000000000
[  328.863902] FS:  00007fb969151600(0000) GS:ffff88007b640000(0000) knlGS:0000000000000000
[  328.864634] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  328.865002] CR2: 00007fb969151600 CR3: 0000000079e91000 CR4: 00000000003406e0
[  328.865548] Stack:
[  328.866047]  ffffc90003a8c899 ffffc90004427088 0000000000000000 ffffc90003a69894
[  328.866783]  ffffc90003ac62f0 ffffc90003890bf8 ffffc90003a69981 ffffc90003890c18
[  328.867503]  ffffc90003a0e34b ffffc900044270b0 ffffc900044270b0 ffffc90003890c28
[  328.868220] Call Trace:
[  328.868566]  <UNK>
[  328.868572] Code:
[  328.869416] c3 0f 01 0f c3 0f 01 1f c3 66 89 fa 66 89 f0 ee c3 66 89 fa 66 89 f0 66 ef c3 48 31 c0 66 89 fa ec c3 48 31 c0 66 89 fa 66 ed c3 <64> 48 8b 04 25 00 00 00 00 48 83 c0 08 c3 66 2e 0f 1f 84 00 00
[  328.870543] RIP  [<ffffc900036bcea4>] 0xffffc900036bcea4
[  328.870881]  RSP <ffffc90003890bc0>
[  328.871208] CR2: 00007fb969151600
[  328.871526] ---[ end trace 9dcdb5a3a5642763 ]---
```

Note the ```CR2``` and ```FS``` values, which are a pretty dead giveaway that someone's trying to read the TLS base pointer from ```[fs:0x0]```.  Sure enough,  ```RIP``` points to the following line in ```intrinsics_x64```:

```asm
; uint64_t __tls_base(void)
__tls_base:
>   mov rax, [fs:0x0]
    add rax, 0x8
    ret
```

Given ```FS``` points to a userland address, I'd say it looks like Linux is getting just as mad as Windows. :(

**Comment by rianquinn** [comment]
Yeah, while loading we cannot touch FS or GS, but the exit handler needs these. I am currently working on an RFC on how to handle this better. The other problem with the way this works now is the memory being used for TLS is different during loading from the exit handler, and thus there is a consistency problem that I'm surprised has not blown up. Both issues need to be addressed.

**Comment by rianquinn** [comment]
@brendank310, @ktemkin, @josephsharkey 

I think I have a good solution to this issue, but I would like some input. Basically, to get thread local storage (TLS) to work (which is needed by the libc++), we need a way to identify a block of memory, VERY quickly, per CPU. The way the kernel does this is it stores a pointer to the block in FS or GS (for the kernel it might be GS), but either way, clearly both Linux and Windows are using FS and GS for something which is why this issue exists. 

So this means we cannot use FS or GS to identify where this memory is for each CPU, at least not while we are loading the VMM. The VMM exit handler can use these just fine, but there is a discontinuity that we must resolve (whatever we use for loading must also be used by the exit handler). 

So... I think a good solution is to use RDTSCP. This is a very fast instruction, and it returns an OS defined proc ID. On Linux, this ID matches the core number, and I am willing to bet it's the same on Windows. So, if I dump out this ID, I see 0, 1, 2, etc.... 

So, my idea is pretty simple. The common.c in the driver can get the total number of CPUs (it already does this), and pre-calc a block of memory for each CPU for the TLS storage, as one big array. It would then call into our C++ code to tell the pthread library where the TLS block is. When libc++ calls into the pthread library to get/set something in the TLS data, we call RDTSCP to get the index into this block of memory, and we are done. All we would need to do is make sure that we leave these indexes the same for the VMM, which makes sense anyways, and we should have a simple way of getting this data very fast. We can also have a sane way of checking this in the driver just to make sure the index is not out of bounds. 

The only downside is the CPU would need to support RDTSCP, which is not a problem since we require the TRUE based controls, and I'm pretty sure any CPU that supports these, also supports RDTSCP. 

Thoughts? What is the equivalent on ARM?

**Comment by rianquinn** [comment]
FYI, I tested on Windows, and it is doing the same thing as Linux, (i.e. 0, 1, 2, etc...)

**Comment by josephsharkey** [comment]
That makes sense to me.

Can't you also use the x2APIC ID as the core number? You get get that via CPUID (eax val 0x0B).

ARM is a little more complicated (no surprise!). There is a CPU register MPIDR_EL1 that contains this info. But it gives somewhat sparse values - i.e. you might get core numbers 0,1,2,3,8,9,10,11 on a CPU with 4 big cores and 4 little cores since they are essentially arranged into clusters and they have a field for cluster number, then a core number within the cluster. The linux kernel takes the value of this register and translates it into logical CPU numbers; but the translation is based on #defines at compile time that know the # of cores for each cluster for your SoC....

**Comment by rianquinn** [comment]
We can use the APIC, but CPUID is pretty slow compared to RDTSCP, and this will get called potentially a lot in the exit handler (`on_success`, `on_failure` need TLS to work), so I'd rather use RDTSCP if possible. It is a fencing instruction, but not as bad as CPUID which completely serializes the pipeline. 

The other issue with CPUID is it has the same issue you just described with ARM, in that you will likely get non-contiguous indexes. Unlike ARM, I don't know of anyway to calculate the logical ID. So long as you guys think that there is at least a way to calc a logical address on ARM we should be good. @ktemkin

**Comment by ktemkin** [comment]
These ideas seem like they'd work-- but I strongly suspect we can do this more efficiently by imitating the way the Linux kernel stored its thread context in pre-2.4 kernels:
http://lxr.free-electrons.com/source/include/asm-i386/current.h?v=2.2.26

This model is relatively straightforward. When each thread is created, it is allocated a small stack whose address is _aligned to the stack size_. Thread stacks are always sized to a binary number; this enables us to _locate the first entry on the stack given the stack pointer_, no matter how much data is on the stack. 

For example, if we had a 64K stack that occupies virtual addresses ```0xABCD0000```-```0xABCDFFFF```, we can always find the end of the first entry by OR'ing with ```0xFFFF```. 

If we follow this model, we can allocate an easily-located block of thread-specific storage by carving out a block of memory immediately following stack allocation-- before we call the entry point for the given thread. As this is the first element on the per-thread stack, we can always find this block with just some pointer arithmetic:

```c
// Assuming a 64K stack and a TLS_SIZE storage area:
tls_base = (tls_block_type *)((stack_pointer | 0xFFFF) - (TLS_SIZE - 1))

// For example, we might have a 64K stack that grows from 0xABCDFFFF, and a TLS storage block from 0xABCDFF00-0xABCDFFFFF. 
// If at runtime, the current SP was 0xABCD1234, our math would be 
tls_base = (stack_pointer | stack_mask) - (tls_size + 1)
tls_base = (0xABCD1234 | 0xFFFF) - (255)
tls_base = 0xABCDFF00

// Or, equivalently:
tls_base = (0xABCD1234 | 0xFFFF) & 0xFFFFFF00
tls_base = 0xABCDFF00
```

This should be fairly platform-agnostic, and much easier on the CPU.

**Comment by rianquinn** [comment]
@ktemkin I like this approach a lot better as it removes the fence that RDTSCP has, and it will work fine on Intel and ARM. 

Any objections to using this approach? It will require a larger mod as I will have to do some work to clean up the stacks that are used, but in general I think this is much better. 

In general... the way I will approach this is, at any point in time, you should be able to get the bottom of the stack by masking your SP. This can be used for setting up the VMCS, and syncing the TLS data structures between loading and the exit handler, something we are not doing at the moment (its amazing that did crash).

**Comment by rianquinn** [comment]
@ktemkin, @brendank310 

Couple of notes:

I am using 32k stacks, which is more inline with what Windows does in Windows 10. I feel the larger stack is useful since RAII does take up stack space. The stack allocation algorithm is as follows:

```
g_stack = platform_alloc_rw(STACK_SIZE * 2);
if (g_stack == 0)
    return BF_ERROR_OUT_OF_MEMORY;

g_stack_loc = (uint64_t)g_stack + (STACK_SIZE * 2);
g_stack_loc = g_stack_loc - 1;
g_stack_loc = g_stack_loc & (STACK_SIZE - 1);
```

I have to subtract 1 first to ensure we are within the bounds of the stack (0 offset problem), and then I can mask to ensure we have an aligned stack to perform the above trick. The `STACK_SIZE * 2` is to ensure there is enough space once the mask operation occurs. Let me know if I am missing anything here (my brain is still pretty foggy). 

In general, this means that we will need to alloc 64k per CPU, plus 64k for startup, with only 32k being usable per CPU. 

Also.. the TLS block needs to be in it's own memory and not on the stack. Instead the stack needs to point to the TLS block. The reason for this is the startup code and the exit handler need their own stack, but have to point to the same TLS data. So, I plan to reserve 32 bytes for pointers (4x 64bit pointers) and each TLS block will be 4K (which means that we really need 68k per CPU). 

Finally, the pthread logic will need to be updated to use atomic operations for key allocation, as right now there is the potential for a race that could cause god to get mad and end all life as we know it 😄 .

**Comment by ktemkin** [comment]
```
platform_alloc_rw(STACK_SIZE * 2);
```

Nitpick: this could probably be ```platform_alloc_rw((STACK_SIZE * 2) -  1);```, as the worst-case is that you're assigned an address one byte after an aligned address-- in which case, you need to waste ```STACK_SIZE - 1``` bytes. (I'm sure this essentially makes no functional difference; so this is just a question of aesthestics and possibly clarity.)


```
g_stack_loc = (uint64_t)g_stack + (STACK_SIZE * 2);
g_stack_loc = g_stack_loc - 1;
g_stack_loc = g_stack_loc & (STACK_SIZE - 1);
```

This doesn't look quite right:

1. Looks like you're missing a bitwise-inverse, here. This will clear out all bits except the least significant; when I suspect you mean the opposite.
2. The alignment math isn't quite right here, either. You want to move to the next alignment boundary by adding one less than the alignment size-- which increments the high bits only if we're not already aligned-- and then masking off the low bits, like so: 

```
g_stack_loc = (uint64_t)g_stack + (STACK_SIZE - 1)
g_stack_loc = g_stack_loc & ~(STACK_SIZE - 1);
```

You're adding too much, and thus have the danger of moving past the desired aligned block and into the partial block afterwards. Imagine you're allocated a region starting in the middle of an aligned block, like below:

```
------------
|          |
|   ---    | <-- pointer returned by malloc to region STACK_SIZE * 2 long
|    |     |
|    |     |
------------ <-- stack location you want 
|    |     |
|    |     |
|    |     |
|    |     |
------------ <-- stack location you’d get with your math
|    |     |
|   ---    | <-- end of guaranteed region, and also g_stack + (STACK_SIZE * 2) 
|          |
|          |
------------
```

**Comment by rianquinn** [comment]
Couple of things:
- With respect to the inverse, yeah I found that too. I debated sending another post, or just updating the original, and did the later, so if you look at it, I added the `~`. 
- The math above is trying to locate the top of the stack. Since a push subtracts, we need to find the top, and work our way to the bottom, with the TLS data sitting right at the top, and the actual stack sitting 32 bytes below that. So at least... this is what I have in my head (assume STACK_SIZE=0x4000 for this example):

```
------------ 0x9050 <-- top of stack
|          |
|   ---    | 0x7FFF <-- top of stack & ~(STACK_SIZE - 1) - 1. 
|          |            This is what we give RSP
|          |
|          |
|   ---    | 0x4020 <-- bottom of stack + reserved space. 
|          |            TLS, Core #, magic #, etc... go here
|   ---    | 0x4000 <-- bottom of stack. The rest is wasted
|          |
|          |
|          |
|          |
------------ 0x1050 <-- returned by platform_alloc_rw(STACK_SIZE * 2)
```

So long as RSP (in this example) is between 0x4000 <-> 0x7FFF, we always get 0x4000 when we `& ~(STACK_SIZE -1)`. So I did forget a -1 at the end, and since we mask, I can just move the existing one to this:

```
g_stack_loc = (uint64_t)g_stack + (STACK_SIZE * 2);
g_stack_loc = g_stack_loc & ~(STACK_SIZE - 1) - 1;
```

Thoughts?

**Comment by ktemkin** [comment]
Oops-- I misinterpreted what you were trying to calculate, and assumed you were trying to find the an aligned location to _put_ the stack (and thus it's lowest address), rather than the base.
 
Nonetheless, the mistake I was pointing out still remains:

```c
// This just adds values to the more-significant bits;
//it doesn't actually affect alignment.
g_stack_loc = (uint64_t)g_stack + (STACK_SIZE * 2);

// What you want is something that will 'add one' to the 
//more-significant bits iff the given address isn't already aligned:
g_stack_loc = (uint64_t)g_stack + ((STACK_SIZE * 2) -1);
```

Without that correction, your code fails if you pass it an aligned address. For example, if we have a ```STACK_SIZE``` of  32K, then we'd expect that ```g_stack = 0x abcd0000``` to produce a 32K aligned stack starting at ```0xabcd0000``` and with a bottom of ```0xabcd7fff```. In this case, nothing should change; we're already aligned. With your math, I get ```0xabcdffff```; with the corrected I get the expected ```0xabcd7fff```.

There's also a typo-ish issue: ```&``` has super-low precedence, so you'll want to parenthesize ```(g_stack_loc & ~(STACK_SIZE -1)) - 1```.

With those corrections, this becomes: 

```c
g_stack_loc = (uint64_t)g_stack + (STACK_SIZE * 2 - 1);
g_stack_loc = (g_stack_loc & ~(STACK_SIZE - 1)) - 1;
```

I find this a little hard to read; I might prefer this as:

```c

// Find an aligned address for the top of our stack.
g_stack_top = (uint64_t)g_stack + (STACK_SIZE - 1); 
g_stack_top &= ~(STACK_SIZE -1);

// Locate the bottom of our stack:
g_stack_bottom = g_stack_top + (STACK_SIZE - 1); 

// [OR] Locate a structure of type struct_blah stored at the bottom of the stack:
g_my_struct = g_stack_top + (STACK_SIZE - sizeof(struct_blah)); 
```

**Comment by ktemkin** [comment]
Also, just for reference, here's the crappy python I was using to sanity-check myself as I looked over your math:

```python
STACK_SIZE = 1024 * 32

def align(stack_loc):
#    bottom = stack_loc + (STACK_SIZE * 2 - 1);
#    bottom = (bottom & ~(STACK_SIZE - 1)) - 1;
    top = stack_loc + (STACK_SIZE - 1)
    top = top & ~(STACK_SIZE - 1)
    bottom = top + (STACK_SIZE  - 16)
    return bottom

def assert_equal(a, b, prefix):
    if a != b:
        print(prefix)
        print("    expected {}, got {}".format(hex(b), hex(a)))


for i in range(0xABCD0000, 0xABCDFFFF):
    aligned = align(i)
    prefix = "{} => {}".format(hex(i), hex(aligned))

    if i == 0xABCD0000:
        assert_equal(aligned, 0xABCD7fff, prefix)
    elif (i > 0xABCD0000) and (i <= 0xABCD8000):
        assert_equal(aligned, 0xABCDffff, prefix)
    elif (i > 0xABCD8000) and (i <= 0xABCDffff):
        assert_equal(aligned, 0xABCE7fff, prefix)
    else:
        print("coding error")
```

**Comment by rianquinn** [comment]
Yeah, I agree the `- 1` should be there. The compiler found the missing parenthesize so that has also been fixed. 

I don't agree with g_my_struct, as that really should be (since the struct is at the bottom):

```
g_my_struct = (my_struct *) g_stack_bottom;
```

**Comment by rianquinn** [comment]
Ok talking with Kyle privately I think we are on the same page, so this is what we came up with. Short story is, we decided to move the struct to the top of the stack. It adds an additional addition to the calculation of the struct's location (thats a lot of adds in a single sentence 😄 ), but it prevents the struct from becoming corrupt in case an overrun occurs, and allows the extra space to be used if it's need. So here is the math:

```
------------ 0x9050 <-- top of stack (0x1050 + STACK_SIZE)
|          |
|   ---    | 0x7FFF <-- actual top stack = top of stack & ~(STACK_SIZE - 1) - 1
|          |            TLS, Core #, magic #, etc... go here
|   ---    | 0x7FCD <-- RSP = actual top stack - 32
|          |            
|          |
|          |
|   ---    | 0x4000 <-- bottom of stack
|          |
|          | Extra space can be used on overrun
|          |
------------ 0x1050 <-- returned by platform_alloc_rw(STACK_SIZE * 2)
```

To get the location of the struct you do the following:

```
bottom_of_stack = RSP & ~(STACK_SIZE - 1)
top_of_stack = bottom_of_stack + STACK_SIZE - 1
struct_loc = top_of_stack - 32
```

Obviously the code will be written with a `sizeof(struct)` and I will fill in the struct with 4 64bit unsigned ints with:
- 0 -> CPU core # (should be the same thing you see in RDTSCP)
- 1 -> TLS pointer
- 2 -> reserved
- 3 -> reserved

Thoughts?

**Comment by rianquinn** [comment]
Fixed
