### ISSUE TITLE
Potential for incorrect guest CR0 check

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#214]
The first bullet of section 26.3.1.1 of the [Intel manual](http://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-manual-325462.pdf) says that  bits 0 and 31 of `cr0` aren't checked if the "unrestricted guest" VM-execution control is 1. But `check_guest_cr0_for_unsupported_bits` checks those two bits without checking "unrestricted guest" first. This may cause the check to fail when it really shouldn't. Should `check_guest_cr0_for_unsupported_bits` be changed to check "unrestricted guest" first?

**Comment by rianquinn** [comment]
yes

**Comment by connojd** [comment]
Fixed in #343
