### ISSUE TITLE
Check for pending debug exceptions RTM

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#230]
In section 26.3.1.5, the third dash under the "Pending debug exceptions" bullet describes a check that occurs if RTM (bit 16 of pending debug exceptions) is 1.  Do we need to implement this check?

**Comment by rianquinn** [comment]
Lol.. my manual must be out of date as I only have two dashes. So yeah, it probably does need to be checked.

**Comment by connojd** [comment]
Fixed in #343
