### ISSUE TITLE
Missing install_clang_1604 function

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#239]
Need to add something like
```bash
install_clang_1604() {
    wget http://llvm.org/releases/3.8.1/clang+llvm-3.8.1-x86_64-linux-gnu-ubuntu-16.04.tar.xz
    tar xf clang*
    sudo cp -R clang*/* /usr/local/
    rm -Rf clang*
}
```
in `tools/scripts/setup_ubuntu.sh` for the 16.04 folks.

**Comment by rianquinn** [comment]
what version ships with Ubuntu 16.04?

**Comment by rianquinn** [comment]
On my system at least, I have 3.8.0-2ubuntu4 which should work fine without having to go through the mess of installing from their site. The only reason I have it in there for 14.04 is clang is too old so I have to update it for Travis. I would note that 14.04 is not actually supported outside of whatever testing Travis is doing for us.

**Comment by connojd** [comment]
The version above works fine and is the one I'm using, but I get a "command not found" error [here](https://github.com/Bareflank/hypervisor/blob/master/tools/scripts/setup_ubuntu.sh#L171) when I try to run setup

**Comment by rianquinn** [comment]
Oh... ha, that just needs to be removed. Feel free to toss in a PR for that if you want.
