### ISSUE TITLE
[RFC]: New MSR / CR / RFLAGS code

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#241]
The MSR, Control Register, RFLAGS is pretty terrible, and it's missing a lot of stuff. Right now, it's just a set of `#defines`, with no real organization. There is a ton of stuff missing (which is not helpful when your trying to prototype stuff), and there is 0 encapsulation so we have masking and bit shifting happening all over the place, which makes testing a nightmare. 

So, here is my proposal. I have some of this working already just to prove to myself that I got it right, as this code is new to me (and likely most of you). 

Lets take the `ia32_vmx_basic` MSR as an example, but everything else will likely take the same form. 

```
namespace intel_x64
{
namespace msrs
{
    template<class I, class T> constexpr auto
    read_msr(I in, T msr)
    { return in->read_msr(msr); }

    namespace ia32_vmx_basic
    {
        constexpr const auto addr = 0x00000480U;
        constexpr const auto name = "IA32_VMX_BASIC";

        template<class I> constexpr auto get(I in)
        { return read_msr(in, addr); }

        namespace revision_id
        {
            constexpr const auto mask = 0x000000007FFFFFFFUL;
            constexpr const auto from = 0;

            template<class I> constexpr auto get(I in)
            { return gsl::narrow_cast<uint32_t>((ia32_vmx_basic::get(in) & mask) >> from); }
        }

        namespace vmxon_vmcs_region_size
        {
            constexpr const auto mask = 0x00001FFF00000000UL;
            constexpr const auto from = 32;

            template<class I> constexpr auto get(I in)
            { return gsl::narrow_cast<uint32_t>((ia32_vmx_basic::get(in) & mask) >> from); }
        }

        ....
    }
}
}
```

Normally, in your code, if your working on an Intel CPU, the first thing your going to do is the following so that you can unwrap some of the nested namespaces here:

```
using namespace intel_x64;
```

Then, code that looks like this:

```
void
vmxon_intel_x64::check_vmx_capabilities_msr()
{
    auto vmx_basic_msr = m_intrinsics->read_msr(IA32_VMX_BASIC_MSR);

    auto physical_address_width = (vmx_basic_msr >> 48) & 0x1;
    auto memory_type = (vmx_basic_msr >> 50) & 0xF;
    auto true_based_controls = (vmx_basic_msr >> 55) & 0x1;

    if (physical_address_width != 0)
        throw std::logic_error("invalid physical address width");

    if (memory_type != 6)
        throw std::logic_error("invalid memory type");

    if (true_based_controls == 0)
        throw std::logic_error("invalid vmx true based controls");
}
```

Now looks like this:

```
void
vmxon_intel_x64::check_vmx_capabilities_msr()
{
    if (msrs::ia32_vmx_basic::physical_address_width::get(m_intrinsics) != 0)
        throw std::logic_error("invalid physical address width");

    if (msrs::ia32_vmx_basic::memory_type::get(m_intrinsics) != x64::memory_type::write_back)
        throw std::logic_error("invalid memory type");

    if (msrs::ia32_vmx_basic::true_based_controls::get(m_intrinsics) == 0)
        throw std::logic_error("invalid vmx true based controls");
}
```

This is obviously a lot cleaner, and allows us to use all sorts of things like:

```
msrs::ia32_vmx_basic::memory_type::get(m_intrinsics)  // Read MSR from intrinsics
msrs::ia32_vmx_basic::memory_type::set(m_intrinsics, value)  // Write to MSR with intrinsics
msrs::ia32_vmx_basic::memory_type::mask // Returns the mask for this field in the MSR
msrs::ia32_vmx_basic::memory_type::from // Returns the starting bit of the field in this MSR
msrs::ia32_vmx_basic::get(m_intrinsics) // Returns the whole MSR
msrs::ia32_vmx_basic::addr // Returns MSR's address (the hex number in the manual)
msrs::ia32_vmx_basic::name // Returns MSR's address (the hex number in the manual)
```

Unlike what we have now, there is a lot of useful stuff here, all organized in a way that matches the Intel docs almost perfectly. We could even add a `description` and `comments` field to this in the future to almost completely match the documentation. 

Now, just for reference, I should explain how the generic programming works here. This code uses some "always auto" patterns, not all of them however because I feel that stating that a field is narrowing should be explicit (narrowing past 32bits in C++ is a bad idea since the compiler automatically converts 16bit and 8bit ints to 32bit ints for you), and the addresses / masks are all explicit. But lets at least look at this pattern:

```
template<class I> constexpr auto get(I in)
{ return gsl::narrow_cast<uint32_t>((ia32_vmx_basic::get(in) & mask) >> from); }
```

The `template` argument here prevents us from having to define what is actually giving us the MSR, so long as it has a function called "read_msr" it will work. From there the `gsl::narrow_cast` states that we are possibly converting a 64bit value to a 32bit value. The `constexpr auto` says the return type can be deduced from what is actually returned (no need to state it), and the `constexpr` tells the compiler, "if you can convert this to a constant expression, do so", which means, treat it like a `#define` macro if you can, removing the function calls, and extra overhead, etc... so this compiles to basically:

```
m_intrinsics->read_msr(addr) & mask >> from
```

Thoughts?

A PR for this will take a couple of days as I have to convert a lot of code to clean this up, but the plus side is we will have a lot cleaner code, and everyone attempting to use Bareflank will have a more complete set of MSRs, Control Registers and RFLAGS to work from. And of course if anything is missing we now have a cleaner way of adding it in the future.

**Comment by connojd** [comment]
Overall I like the direction away from #defines to more C++-style features. One comment to add: since we're using generics for this, I think the design should be generic as possible. It should be designed with other architectures and platforms in mind.  

The nested structure of the namespaces above sort of suggests that only Intel architectures have msrs and control registers.  Should those be represented at a higher level in the namespace?  Maybe it is just a naming issue of the namespaces, because like you said, any I that has a `read_msr` function can use the `msrs::read_msr` function.

I know the code above isn't final but those are some thoughts I had when reading it.

**Comment by rianquinn** [comment]
So I thought about that, and I don't see any way to generalize control registers between ARM and Intel, and I don't think it's worth doing as it would come at a cost of clarity. 

Now... that being said, there are MSRs, control registers, etc... that are shared between AMD and Intel. So my idea here is as follows:

x64:: -> AMD / Intel shared registers. Likely RFLAGS, one, maybe two of the control registers, and several MSRs
intel_x64:: -> Intel specific registers
amd_x64:: -> AMD specific registers

For now, most of the code is going to go into intel_x64, and as we begin to add support for AMD, we can start to move things to the general x64:: namespace. 

Now that being said I am open to suggestions on how to generalize this further, but I'm not sure it's going to be possible without the interface being too confusing. For example, CR4 has a LOT of Intel specific fields. We could divide CR4 up between x64, intel_x64 and amd_x64, but then you would have to know which one it belongs to to figure out what you need, which I think is too confusing.

One idea would be to have everything in x64:: that is shared, with the same things being in intel_x64 that is in x64:: + intel specific stuff. So if you only need generic stuff, you go to one vs the other. The problem here is I'm not sure how to organize this without there being duplication. If this is something people really want, and duplication is the only way I'm fine with that, but I'd like to avoid it if possible. 

Another thing I like about this approach is it will work great with C++ modules once they become available, something we should be thinking about as our compile times are already pretty high.

**Comment by connojd** [comment]
A possibility is to move the msrs, control registers, etc. information into the intrinsics hierarchy as static data members. Each class along the hierarchy already defines their own read_msr, write_msr, etc. functions and plus the msrs are referenced in the context of instances of the intrinsics hierarchy already. This would prevent duplication of common registers and of code, and allow for more-derived classes to define their own masks, fields, etc. for arch-specific registers.

**Comment by rianquinn** [comment]
So I thought about using class inheritance, but I don't like it four a couple of reasons:
- I cannot organize the various definitions like I can above without either introducing a train wreck, or some other odd ball nested class structure, which really doesn't get to what your looking for here
- The only implementation I can think of, would have to use the name itself to organize where we put things, so you would have something like `msrs_<msr name>_field_get()` which I really don't like. 
- Since we cannot spread the code out in classes like we can with a namespace, you would have a pretty massive sized intrinsics class that would not work well with modules
- It's really heavy handed, the code above compiles to the same thing we have now, and testing is simple, using class inheritance, we would have a pretty massive addition to the code itself.
- We really try to avoid static functions and data members as they are even harder to test. 

The only advantage I see to using class inheritance for this problem is the ability to access a set of registers for x64 and Intel from one m_intrincis->reg(), but since you need to include everything in the name to deal with conflicts, I don't see how the code is really any more readable vs x64::msrs::<reg>::get() and then doing intel_x64::msrs::<reg>::get() 

One thing I have been playing with is trying to find a way to be able to remove the need to pass in an intrinsics class, which I think I can do just fine (I can call the intrinsics function no problem). The issue with that is unit testing. If all of the code calls this without passing the intrinsics class, how do you unit test?

One possibility, is to remove the intrinsics class completely, and just call a set of wrapper C++ functions, and use Hippomocks to mock the functions using their C versions, or better yet, just not link in the intrinsics library, and have to provide these symbols manually. The former would require static linking which can be a pain as a mod to the library doesn't currently get detected my make. The latter would work without the need for static linking, but likely would require all of the symbols to be defined (even if they are not needed)... but now that I think about it, we could provide "weak" versions of each one that throws an exception saying they need to be redefined. Might not actually be a bad idea.

Thoughts?

**Comment by rianquinn** [comment]
Testing out removing the intrinsics code now (one step at a time as it's pretty large), but so far, using Hippomocks and using static intrinsics linking, it seems to be working really well. Statically linking to that library actually shouldn't be a big deal as we don't touch that code very often. 

The only odd ball thing that might come up is if you forget to mock an intrinsic, the linker might compile out a symbol that is needed, in which case the test will likely fail to run while attempting to load in the dynamic libraries. This error is likely a good thing anyways, but it's good to note at least some of the strange things that happen when you mix static and dynamic libraries.

**Comment by rianquinn** [comment]
This is complete now. It has been fixed by several PRs over the past month.
