### ISSUE TITLE
Track a clang_complete file for the project

### ISSUE THREAD

**Issue by brendank310** [Bareflank/hypervisor#244]
If you have an editor that supports clang autocomplete, having the clang_complete file as part of the project would help reduce the need to switch between files. The large (and growing larger) number of constants and methods that are of interest to those extending the hypervisor (MSRs come to mind) becomes a little more manageable with autocomplete support.

**Comment by rianquinn** [comment]
I have been unable to get this to work with multiple editors. We have the file at least, and it looks right based on the documentation, and as far as I can tell it's not an issue with the clang_complete file itself as Vim, Sublime and Atom cannot complete STL classes either. So for now I'm going to close this until someone can find an editor that actually supports clang complete
