### ISSUE TITLE
True control msrs

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#259]
I've noticed that we use the `IA32_VMX_TRUE_*_CTLS` msrs without checking bit 55 of `IA32_VMX_BASIC` msr.  If you look at the last bullet under "A.2 RESERVED CONTROLS AND DEFAULT SETTINGS" in the manual it says that if bit 55 is 0 those four msrs aren't supported.

Have we just gotten lucky without checking bit 55, or am I missing something and we actually don't need to check it?

**Comment by rianquinn** [comment]
You require the TRUE based MSRs. So, no we don't check for them. That being said, now that we will have easy logic for getting to this information, we could add some code to do the check just to make sure they are supported and throw an error saying "unsupported hardware". 

But yeah, if you don't have a SandyBridge or higher, we don't support it.

**Comment by rianquinn** [comment]
I'll file this as a bug so that we add this to 1.1 as it should be pretty simple to add a check.

**Comment by rianquinn** [comment]
This is actually being checked here:
https://github.com/Bareflank/hypervisor/blob/master/bfvmm/src/vmxon/src/vmxon_intel_x64.cpp#L101
