### ISSUE TITLE
[RFC]: Delete OS X for 1.1 (will be reintroduced once it's working)

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#280]
The OS X code at the moment is broken in many ways, and we don't plan to support it for 1.1. I'd like to create a branch that has this code in it, and then delete the code in master for the upcoming 1.1 release. Once we have time to revisit this code and add OS X support we can delete the branch, and continue official support in master from there. 

My main reason for wanting to delete this code is I don't want users of 1.1 to get confused and think that OS X works as it doesn't at the moment as we are still trying to figure out how to alloc / mprotect read/execute memory in the kernel.

**Comment by brendank310** [comment]
I don't really think there is a hazard in leaving it. The readme by the driver clearly states it isn't currently supported. I'm not set against it being removed, but it seems like churn for no reason.

**Comment by rianquinn** [comment]
At the very minimum, if we are going to keep it, we need to clean it up so that doxygen isn't so mad about the code in there. Maybe I can add an exclusion for this dir so that's not being documented. 

Thoughts?

**Comment by rianquinn** [comment]
Fixed in: #285
