### ISSUE TITLE
[RFC]: Remove virtual functions in exit handler

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#329]
I would like to remove the virtual functions in the exit handler prior to releasing 1.1 in favor of a different paradigm. 

The exit handler has a lot of unhandled virtual functions (that are never used) which causes two issues:
- `new exit_handler{}` results in a pretty large object which consumes a lot more memory than is needed. Removing the virtual functions will remove this issue (in fact the exit handler might be reduced to just a couple of bytes)
- All of the unhandled functions result in extra code that is never used, being loaded. 

Instead, I would prefer the dispatch function to call a handle_exit function which is the only function to be labeled virtual. It would provide the exit reason, and internally, it would handle default actions that the exit handler already provides. Users would override this function and handle the exit on their own, or call the base class and have it handle the exit (or default to unhandled). 

The functionality would be identical, but would reduce both the `new` size, and the oversize of the code. 

Thoughts?

This is a pretty minor change, which a large impact. We are pushing REALLY hard to get 1.1 RC1 done for Thanksgiving, so I would like to get this change in this weekend.

**Comment by connojd** [comment]
I think if extensions of bareflank want to deviate from the default exit handling, all they will need is the relevant fields like the exit reason, exit instruction length, etc. As long as the mechanism is there then it's probably fine to expose one function to extensions.
