### ISSUE TITLE
[RFC]: extended_apis: IO bitmap support

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#358]
NOTE: These changes will be made to the [extended_apis](https://github.com/Bareflank/extended_apis) repo and not the main Bareflank repo as we want to keep Bareflank simple. 

### Proposed APIs:
To support IO bitmaps, I would like to add the following APIs:

- `vmcs::trap_on_io_access(port #)`
- `vmcs::trap_on_all_io_accesses()`
- `vmcs::pass_through_io_access(port #)`
- `vmcs::pass_through_all_io_accesses()`
- `vmcs::whitelist_io_access(std::vector ports)`
- `vmcs::blacklist_io_access(std::vector ports)`
- `exit_handler::log_io_access(bool enable)`
- `exit_handler::clear_io_access_log()`

**trap_on_io_access:**
This function will set the corresponding port # in the IO bitmaps to 1, causing any access to this port to be trapped to the hypervisor. 

**trap_on_all_io_accesses:**
This function will set the entire IO bitmaps to 1, causing any access to any port to be trapped to the hypervisor. 

**pass_through_io_access:**
This function will set the corresponding port # in the IO bitmaps to 0, causing any access to this port to be passed to the VM. 

**pass_through_all_io_accesses:**
This function will set the entire IO bitmaps to 0, causing any access to any port to be passed to the VM. 

**whitelist_io_access:**
All ports will be set to 1, (likely via memset), and then only the ports provided in the list will be set to 0. 

**blacklist_io_access:**
All ports will be set to 0, (likely via memset), and then only the ports provided in the list will be set to 1. 

**log_io_access:**
If enabled, all accesses to ports that trap will be logged to a std::map<port, count>. This should only be enabled by developers, but can be used to see which ports are being accessed by the VM to help generate black / white lists.

**clear_io_access_log:**
Clears the IO access log

### Proposed VMCall APIs:
To support IO bitmaps, I would like to add the following vmcall APIs:

**register based calls**:
- trap_on_io_access
    - r2 = eapis_cat__io_instruction (0x1000)
    - r3 = eapis_fun__trap_on_io_access (0x1)
    - r4 = port
- trap_on_all_io_accesses
    - r2 = eapis_cat__io_instruction (0x1000)
    - r3 = eapis_fun__trap_on_all_io_accesses (0x2)
- pass_through_io_access
    - r2 = eapis_cat__io_instruction (0x1000)
    - r3 = eapis_fun__pass_through_io_access (0x3)
    - r4 = port
- pass_through_all_io_accesses
    - r2 = eapis_cat__io_instruction (0x1000)
    - r3 = eapis_fun__pass_through_all_io_accessed (0x4)

**JSON based calls**:
- {"set": "trap_on_io_access", "port": port}
- {"set": "trap_on_io_access", "port_hex": "port"}
- {"set": "pass_through_io_access", "port": port}
- {"set": "pass_through_io_access", "port_hex": "port"}
- {"set": "whitelist_io_access", "ports":  [port, ...]}
- {"set": "whitelist_io_access", "ports_hex":  ["port", ...]}
- {"set": "blacklist_io_access", "ports":  [port, ...]}
- {"set": "blacklist_io_access", "ports_hex":  ["port", ...]}
- {"set": "log_io_access", "enabled":  boolean}
- {"run": "clear_io_access_log"}
- {"get": "io_access_log"} -> log (std::map -> JSON)

### Exit Handler Additions:
To support logging, an exit_reason::basic_exit_reason::io_instruction handler will be provided with a default seem for hooking. The default seem will pass trapped IO instructions back to the VM, but can be overridden by the user to provide custom logic. 

### Default:
By default, an empty blacklist will be provided (meaning all ports are passed through), and logging will be disabled.

**Comment by rianquinn** [comment]
@josephsharkey @ionescu007 @tandasat @brendank310 @connojd @RicoAntonioFelix @ktemkin @tklengyel 

Since RC1.1 is out, I can start (finally) working on the extended APIs. I should have an RFC for each of the major features, and figured I would start with IO bitmaps. You will notice that I have register and JSON versions of the vmcalls. The register versions are intended for drivers as string manipulation is not fun in a driver, and the JSON versions are intended for the command line because memorizing enums on the command line is not fun... so I provide both. 

Let me know if you think I am missing anything or you would like to see it done a different way. Also... its important to note that none of this code will be in the main repo. The only mods to main repo going forward will likely be adding support for new operating systems like UEFI, BSD and macOS as well as adding ARM support.

**Comment by mor619dx** [comment]
IO bitmap access is per vm setting (in vmcs) but the api doesn't allow you to choose which vm you are referring to, do you planned it to be automatically to the bitmap which did the vmcall?

Also what about using the functionallity without the bfm but from the hypervisor iteself will it be possible?

**Comment by mor619dx** [comment]
Yeah, I was just thinking about it might be needed to extend for other cases as using it to refer another guest from the one your currently running on.

I agree that this logic is more suitable for the hyperkernel logic.

**Comment by rianquinn** [comment]
@mor619dx ok... awesome. So just to be clear:

**Applies to VMCS that the vmcall trapped to:**
- {"trap_on_io_access": port}
- {"trap_on_io_access": "port in hex"}
- {"pass_through_io_access": port}
- {"pass_through_io_access": "port in hex"}
- {"whitelist_io_access": [port, ...]}
- {"whitelist_io_access": ["port in hex", ...]}
- {"blacklist_io_access": [port, ...]}
- {"blacklist_io_access": ["port in hex", ...]}
- {"log_io_access": true/false}
- {"get": "io_access_log"} -> log (std::map -> JSON)

**Applies to VMCS specified in request (might be another guest).. and these will exist in hyperkernel repo:**
- {"trap_on_io_access": {"port": port, "guestid": guestid, "vcpuid": vcpuid}}
- etc.... 

And obviously we would have the non-JSON versions of these are well in the hyperkernel repo, with the enums appended with "_FOR_GUEST"

**Comment by rianquinn** [comment]
privately, @brendank310 brought up a good point which is, what do we do about XSM like functionality now that we are introducing supported vmcalls so that we can prevent a guest from running these if we want / need to. 

For now.. these will be unfettered (as a lot of our users likely don't care about blocking vmcalls), but our security minded users will absolutely care about this, and it's critical we get it right. 

When a vmcall is made that is not supported, or a vmcall denial occurs, both should output the same error... something like std::runtime_error("unsupported vmcall"). This way, malicious software doesn't know if the feature is simply not there, or being blocked by policy. 

As for locking down the vmcalls, I'd like to leave some of that up to the users of Bareflank as I am sure advocates for XSM will want to port the SELinux engine. That being said, we should provide a basic capability, and I think that JSON schema is likely to be the answer to that as it would work for everything, and it's flexible so it will allow people to create their own vmcall interfaces and still use the same schema to define everything (unlike SELinux which is very static). 

So... short story is... we are aware that adding vmcalls will introduce security issues that will need to be addressed. Keep your eye out for a future RFC that addresses this exact issue, and it will likely revolve around JSON schema, but we should make sure we implement this in a way that could support SELinux if users wish to go in that direction.

**Comment by tklengyel** [comment]
The nice thing about XSM on Xen is that it's not tied to a specific implementation. Flask right now is the only supported policy engine but the basics of XSM is simply issuing a callback through an abstraction wherever needed specifying which hypercall occured. So if this is a feature that will be needed in the future here, it's nice to start with putting in placeholders for now to an abstract class that's not actually doing anything (or maybe just logs each call). Later on it would be simpler to inherit that abstract class and filling in the blanks then having to comb through the whole codebase to add the necessary calls.

**Comment by rianquinn** [comment]
@tklengyel thanks for the input! I agree (and I think @brendank310 would too as he was saying something similar) ... so with that said... I will start an RFC on how we might go about doing this, and I will implement at the very least, the logging part of this as part of this PR

**Comment by brendank310** [comment]
I agree with @tklengyel that logging is a nice way of having the stubs in place without an ton of upfront work.

**Comment by rianquinn** [comment]
Added clear_io_access_log

**Comment by rianquinn** [comment]
updated the JSON vmcalls to provide a cleaner way to parse them

**Comment by rianquinn** [comment]
Completed: https://github.com/Bareflank/extended_apis/pull/4
