### ISSUE TITLE
[RFC]: extended_apis: vmcall denials

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#363]
NOTE: These changes will be made to the [extended_apis](https://github.com/Bareflank/extended_apis) repo and not the main Bareflank repo as we want to keep Bareflank simple. 

For good reason, many have asked about how we plan to lock down the vmcall interface for Bareflank. Many of our users are interested in research / reverse engineering, so denying vmcalls is of little interest, but we do have several users interested in Bareflank for defensive research / products, and thus locking down the vmcall interface is critically important. Our goal here is to define a flexible interface that is easy to use, is as good or better then [XSM](https://wiki.xenproject.org/wiki/Xen_Security_Modules_:_XSM-FLASK), and off by default, but simple to enable. 

Also... I want to stress the fact that this is a first stab at this, and all I want to focus on are the details associated with the "ignore denial" and "deny all" cases. How we construct a policy, and how those policies are enforced will be provided in a future RFC / PR and are out of scope for this conversation. All we want to do here is get something started that can be extended later, so lets focus on making sure what we define here will work with future designs. 

### Proposed Design:
Every vmcall must come from the [exit_handler](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/src/exit_handler/src/exit_handler_intel_x64.cpp#L163), and from there it will be dispatched to the appropriate vmcall handler. For example, lets look at the proposed APIs for IO:

- `vmcs::trap_on_io_access(port #)`
- `vmcs::pass_through_io_access(port #)`

Both the register based vmcalls and the JSON based vmcalls have to call these VMCS functions one way or another. The register based will decode a provided enum while the JSON logic will decode the command and convert strings -> numbers as needed. Either way, the vmcall interfaces will eventually funnel to a single call made in the exit_handler that will make the needed API calls, and vmcall denials can be made here: 

```cpp
void 
exit_handler_intel_x64_eapis::handle_vmcall__trap_on_io_access(port_type port)
{
    if (<vmcall denied>)
        throw std::runtime_error(<ascii picture of denied meme>);

    vmcs::trap_on_io_access(port);
}

void 
exit_handler_intel_x64_eapis::handle_vmcall__pass_through_io_access(port_type port)
{
    if (<vmcall denied>)
        throw std::runtime_error(<ascii picture of denied meme>);

    vmcs::pass_through_io_access(port);
}
```

To keep things simple to read / find, all of the exit handler functions that funnel these vmcalls will live in a `_handle_vmcall.cpp` file (e.g. `exit_handler_intel_x64_eapis_io_handle_vmcall.cpp`), while the emulation for the exit handlers will reside in a `_emulation.cpp` file, and each vmcall type will have it's own file for decoding the vmcall and calling the vmcall handler (e.g. JSON vmcalls will reside in a JSON specific file, convert JSON to the needed args and call the correct `handler_vmcall_xxx` function). 

To determine if a vmcall should be denied, we will need an architecture that is fast but can also be extended (as users will be adding their own vmcalls in addition to what the extended_apis and hyperkernel repos will provide, which is different than existing hypervisors that have a static list of hypercalls to work with). If we wanted pure speed, we would create a structure that contained a list of predefined `verify_vmcall` functions that took a set of predefined args for each possible vmcall, and verified the vmcall args based on some policy from the user. No lookups would be needed, and each vmcall could be customized. The problem with this approach is it's too static and thus cannot easily be extended by users of Bareflank. 

Instead I would like to propose a compromise that adds a lookup, and verifier for validation that would take on a form similar to the following:

```cpp
void 
exit_handler_intel_x64_eapis::handle_vmcall__trap_on_io_access(port_type port)
{
    if (policy<verifier::trap_on_io_access>(index::trap_on_io_access)->verify(port) == false)
        throw std::runtime_error(<ascii picture of denied meme>);

    vmcs::trap_on_io_access(port);
}
```

`policy()` takes in an index, and verifier type, looks up the verifier, and casts it's base implementation to the proper verifier for the specific vmcall. Under the hood, the policy function will use a std::map to store the index -> verifier lookup table, and this map defines the actual "policy" being enforced by the exit handler. Different versions of this map could be created for different types of VMs that are already known and globally defined (allowing the exit_handler's resources to be very quickly created) but would also support custom creation if needed. The internal guts to each verifier would be implementation specific, but could be JSON Schema, or SELinux. The base class of each verifier will ignore the denial by default, or deny (if denials are explicitly enabled), and the first PR that contains this capability will only provide this all or nothing approach to start. 

With this approach, users will be able to create their own policies, extend the provided vmcall interfaces, and vmcall's can be verified quickly. The only performance penalty is a O(1) lookup which is fine for a vmcall interface that can be extended. 

### Default
By default this capability will be disabled, but can be enabled using a #define macro. Doing so will cause the base class verifier to deny all. Subclasses of the verifier can parse the function arguments and allow / deny based on policy

### Verifier
To support vmcall denials, the verifier would take on the following form:

```cpp
class vmcall_verifier
{
public:
    vmcall_verifier() = default;
    virtual ~vmcall_verifier() = default;

    virtual std::string to_string() const;
}

class vmcall_verifier__trap_on_io_access : public vmcall_verifier
{
public:
    vmcall_verifier__trap_on_io_access() = default;
    ~ vmcall_verifier__trap_on_io_access() override = default;

    std::string to_string() const override
    { return "allow: port 80, deny: * - 80"; }

    bool verify(portio::port_addr_type port);
}
```

### Policy
To support vmcall denials, a policy would take on the following form:

```cpp
std::map<vmcall_index_type, vmcall_verifier *> policy
```

Each `handle_vmcall__xxx` would have a vmcall_index_type associated with it, and each `handle_vmcall__xxx` function would look up it's verifier and validate the args of the vmcall. Since each exit_handler has it's own policy, you can have per-VM permissions. 

The following APIs would be provided to the exit handler:

- `exit_handler::get_verifier<T>(uint64_t index) -> verifier`

**get_verifier:**
Returns a statically casted verifier given the provided policy index and policy type

### Proposed VMCall APIs:
To supportvmcall denials, I would like to add the following vmcall APIs:

**JSON based calls**:
- {"dump": "policy"}
- {"dump": "denials"}

**dump policy**
Loops through all of the verifiers in a policy and use's it's to_string() to print out the entire policy in human readable form. This can be used to analyze a policy to identify issues. 

**dump denials**
Denials will be logged on a per exit_handler basis (i.e. each vCPU will have it's own list of denials). This function will spit out a list of all of the denials.

@brendank310 @ktemkin @tklengyel @connojd @mor619dx @josephsharkey

**Comment by rianquinn** [comment]
After talking with @brendank310 about this RFC, I remembered that although JSON is fast in binary form.. it uses malloc/free since under the hood it uses std::map / std::array, which seems like a bad idea for every singe vmcall. 

In general... we likely have an issue today with the use of JSON (i.e. with our current memory manager, @connojd and I verified that fragmentation with std::string does happen if given enough time). Our current memory manager is set to 16MB, which isn't a lot to work with. We use a very basic SLAB implementation similar to Linux, but it needs fine tuning to prevent JSON vmcalls from locking up the hypervisor due to std::bad_alloc. 

So for now... I think it makes more sense to use class inheritance for the verifiers. We will use dynamic_cast to keep things safe, which should still be lightyears faster than using JSON for the args. Not as flexible as I would have liked this interface, but it's a lot safer, and will not require any malloc / free to work, which I think is more important. 

The above text has been updated to reflect this change. Let me know if you agree!!!

**Comment by mor619dx** [comment]
Neat idea, only thing I might propose is about this code:

```void 
exit_handler_intel_x64_eapis::handle_vmcall__trap_on_io_access(port_type port)
{
    if (policy<verifier::trap_on_io_access>(index::trap_on_io_access)->verify(port) == false)
        throw std::runtime_error(<ascii picture of denied meme>);

    vmcs::trap_on_io_access(port);
}
```
It seems that
```
    if (policy<verifier::trap_on_io_access>(index::trap_on_io_access)->verify(port) == false)
        throw std::runtime_error(<ascii picture of denied meme>);
```
Will be called in each policy enforced vmcall(with only maybe different error handler), If we want to make things more clean we could create c++ variation of decorator (wrapper) and it will allow the handle vmcall function to have only the handle vmcall code itself without policy related code.

So it's just another class layer above the vmcall handler function, however it will have a drawback that will require to pass through the policy decorator (even if you don't enforce policies).

Either way the design looks good to me.

**Comment by rianquinn** [comment]
@mor619dx This is good advice, and we will be providing something like this via the hyperkernel. Lets take trap_on_io_access for an example. The extended_apis only has support for the host OS, just like Bareflank, so the only information that the verifier has to work with is the port #. The hyperkernel however will have the guest_id and group_id for both itself, and the guest the vmcall is working with, so there is a lot more information to work with. To support this, the hyperkernel will override the handle_vmcall__xxx functions and provide the verifer with this new information, and the verifiers themselves will have to be hyperkernel specific (which makes sense since the way you would deny with no guest support is certainly different than the way you would deny with guest support).  

The goal of the above design is to provide a way that all of this can happen selectively, and the policy itself can be changed dynamically at runtime if desired. I should have this code worked out today, and I'll likely toss the code into the repo for review tonight. Since this is the first bit of code to go into the extended_apis, I'm going to push without working unit tests just so that people can see it in action, while I sort out the laundry (like getting coverals, travis-ci, etc, etc... all working)

**Comment by rianquinn** [comment]
Completed: https://github.com/Bareflank/extended_apis/pull/4
