### ISSUE TITLE
[RFC]: extended_apis: monitor trap flag

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#366]
NOTE: These changes will be made to the [extended_apis](https://github.com/Bareflank/extended_apis) repo and not the main Bareflank repo as we want to keep Bareflank simple. 

The monitor trap flag VM execution control bit provides the VMM with a means to single step an instruction. For example, the default IO bitmap APIs will use the monitor trap APIs to execute port IO commands inside the guest context, while still being able to trap on each instruction, and log it's execution. 

The hardest part about the monitor trap flag is managing what to do when a trap is set (i.e. you wish to single step). This gets really complicated when you have multiple different reasons to set a trap flag. The APIs presented here should eliminate this issue, providing a simple means to handle traps. 

### Proposed APIs:
To support the monitor trap flag VM exit, I would like to add the following APIs:

- `exit_handler::register_monitor_trap(callback)`
- `exit_handler::clear_monitor_trap()`

**register_monitor_trap:**
Registers a member callback to be called after the guest completes it's next instruction. This will occur once you run vm->resume(), and the next instruction executes in the guest. For this reason, it should be viewed as an asynchronous callback, and you should be familiar with how this flag works. Specifically, read section 25.5.2 Monitor Trap Flag, in Volume 3 of the Intel SDM. To use this API, you will need to register a member callback as follows:

```cpp
register_monitor_trap(&exit_handler_intel_x64_my_ext::callback);
```

**clear_monitor_trap:**
Clears a registered callback. Under the hood, the extended APIs will use this to clear the trap flag once a trap has occurred but it can be used by the user to cancel a registered trap if desired. 

### Proposed VMCall APIs:
There are no proposed vmcalls for this RFC. 

### VMCS Additions:
There are no proposed changes to the VMCS for this RFC. 

### Exit Handler Additions:
To support these APIs, the exit handler will contain a member variable that will store the callback function. When a VM exit occurs due to a monitor trap flag, the handler will run clear_monitor_trap first, and then it will call the registered callback, providing a means for the callback to register another callback if desired. 

### Default:
By default, the monitor trap flag will be disabled, and an unhandled callback will be registered. If this handler is called, the hypervisor will throw an exception and halt. 

@brendank310 @ktemkin @tklengyel @connojd @mor619dx @josephsharkey

**Comment by tklengyel** [comment]
So register_monitor_trap would only register the callback.. but MTF is vCPU specific, so I assume there is another set of APIs for setting and clearing the bit in the VMCS?

**Comment by rianquinn** [comment]
@tklengyel My bad, I should have been more specific... `register_monitor_trap` registers the callback, and enables the trap flag. `clear_monitor_trap` registers a default handler (just incase it's called accidentally), and disables the trap flag. 

The initial implementation can be found [here](https://github.com/Bareflank/extended_apis/blob/master/src/exit_handler/src/exit_handler_intel_x64_eapis_monitor_trap_emulation.cpp)

**Comment by tklengyel** [comment]
So does this mean there is only one VMCS in-use? Otherwise I would expect the API to have further specification on which VMCS we want MTF enabled on.

**Comment by rianquinn** [comment]
@tklengyel Each vCPU has it's own VMCS. Right now we only support the host OS (working on initial guest support starting Monday), but with Bareflank right now... if you have 4 physical cores, Bareflank will start on all 4 cores. 

When you vmcall... you are trapping to the vCPU that your running on. You will have to use your OS's affinity facilities to target a specific vCPU. If your using BFM, you can do this by adding a "--cpuid xxx" to your command, which will tell the driver to target a specific core # right before it runs the vmcall instruction for you (i.e. it uses the kernel's affinity functions for you). If you want to set the trap flag on all 4 cores (in this example), you will need to run your BFM command on all 4 cores. 

The "--cpuid" already exists (run make help for a list), so you can try that now. You can also add core specific debug statements in the hypervisor so that you can see which cores are being talked to. I would image that most developers will likely bash script the vmcalls to make this easier (setting up the JSON commands they want to run, and then running each set on each core they want to target, which is likely all of them). I wanted to leave the flexibility in there though so that you can setup the vCPUs differently if you want. Sometimes it can be helpful to have different cores working in different ways... all of which works today with the "--cpuid" optional argument for BFM. 

Once we have guest support via the hyperkernel, the APIs provided by the hyperkernel will be more extensive. Specifically... there will not be a way to use the OS's affinity functions to target a vCPU on a different VM (as that makes no sense at all), so we will have to add to the APIs a means to target a vCPU for a specific guest. I want that logic to be hyperkernel specific as people interested in non-guest supported APIs are not going to want to add a guest ID when they don't have a need for them.

**Comment by rianquinn** [comment]
Completed: https://github.com/Bareflank/extended_apis/pull/4
