### ISSUE TITLE
[RFC]: extended_apis: EPT

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#374]
NOTE: These changes will be made to the [extended_apis](https://github.com/Bareflank/extended_apis) repo and not the main Bareflank repo as we want to keep Bareflank simple. 

The Extended Page Tables (EPT) provides a means to map guest physical addresses to physical addresses. Note that the manual doesn't call them host physical, but just physical, and even our use of host is overloaded a bit (like the manual, when we say host sometimes we mean the VMM, other times we mean the host OS which could be viewed as the bootstrap guest). Note that we have no intention of supporting shadow page tables (also called the vTLB), although support could be added by a user in their extensions. 

There is also likely a ton of APIs that we could add over time to EPT, so this RFC is really geared towards two main concepts, which should get EPT up and running:
- Enable EPT and provide a means to add guest physical -> physical mappings
- Trap on memory access

### Proposed Design:
Sadly, EPT entries are nothing like regular page table entries, so I don't think there will be any reuse with the existing page table code. The code however will be similar with the following two classes being added:

```cpp
class page_table_entry_x64_ept;
class page_table_x64_ept;
```

Like the regular page tables, the page_table class will inherit from the entry class (as a page table is also an entry), and there will be a set of functions to add / remove mappings:

```cpp
class page_table_x64_ept : page_table_entry_x64_ept
public
    page_table_x64_ept(uintptr_t pte);
    ~ page_table_x64_ept();

    gsl::not_null<page_table_entry_x64_ept *> add_page_512g(guest_physical addr);
    gsl::not_null<page_table_entry_x64_ept *> add_page_1g(guest_physical addr);
    gsl::not_null<page_table_entry_x64_ept *> add_page_2m(guest_physical addr);
    gsl::not_null<page_table_entry_x64_ept *> add_page_4k(guest_physical addr);

    void remove_page_512g(guest_physical addr);
    void remove_page_1g(guest_physical addr);
    void remove_page_2m(guest_physical addr);
    void remove_page_4k(guest_physical addr);
}
```

Unlike the regular pages, there isn't going to be a [root page table](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/memory_manager/root_page_table_x64.h) class responsible for mapping / unmapping guest physical addresses. Instead, this logic will reside in the VMCS, as each VMCS will have to store it's root page table for EPT. Furthermore, for now there isn't going to be a [unique_map](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/memory_manager/map_ptr_x64.h) version for EPT, but we could add one in the future. I'd like to use EPT for a while and get a sense of what types of mapping / unmapping is occurring before we commit to a class of that nature. 

Trapping on a memory address will depend on what type of trap your looking for (read, write or execute) as all three can be controlled via EPT. Since there is an overwhelming number of use cases for trapping on an access to a page, the only API we should support to start with is locating the page table entry (PTE) for a specific address. Although this will create a [train wreck](https://www.amazon.com/Art-Unit-Testing-examples/dp/1617290890/ref=dp_ob_title_bk), it will provide the user with a simple means to apply a hook. The user can mark the requested page as not readable, writable, or executable and handle the VM exit when the guest attempts to read / write / execute to this memory. 

### Proposed APIs:
To support EPT, I would like to add the following APIs:

- `vmcs::enable_ept()`
- `vmcs::disable_ept()`
- `vmcs::map(guest_physical addr, physical addr, attr_type attr)`
- `vmcs::unmap(guest_physical addr)`
- `vmcs::gpa_to_pte(guest_physical addr)`

**enable_ept:**
Enables EPT. EPT must be enabled before mapping / unmapping as the process of enabling EPT will not only enable the VMCS control field, but it will also setup the root page tables for the VMCS. Also, if VPID is not enabled first, this function will throw (VPID is required to use EPT). 

**disable_ept:** 
Disables EPT and removes the page tables associated with EPT. 

**map:**
Adds a guest physical to physical address map to the guest associated with the VMCS. The attribute parameter is similar to attribute parameter provided by Bareflank for it's page tables, but adds 512g, 1g, 2m, 4k variants so that the user can specify the size of the mapping. For example, `rw_wb_512g` would add a mapping that has read / write permissions, with write back caching, containing a mapping the size of 512g. 

**unmap:**
Unmaps a previously mapped guest physical to physical memory range. 

**gpa_to_pte:**
Locates the page_table_entry_x64_ept for the guest_physical address requested (throws if it cannot find it). The result is a pointer to the page_table_entry_x64_ept wrapped in [gsl::not_null](https://github.com/Microsoft/GSL/blob/master/gsl/gsl#L62). Although a pointer is provided it should be noted that the page tables own the pointer (i.e. this is not a shared_ptr), and thus, if you unmap the memory associated with the resulting PTE, the PTE is no longer valid. 

### Proposed VMCall APIs:
There are no proposed vmcalls for this RFC.

### Default:
By default, EPT will be disabled

### Notes:

If there are any other APIs you would like to see as part of the initial support for EPT, please speak up. 

@brendank310 @ktemkin @tklengyel @connojd @mor619dx @josephsharkey @ranok @ionescu007

**Comment by mor619dx** [comment]
Important thing to notice is that there are quite few ept (also vpid) capabilities, which in order to support needed to be verified - for example execute only pages needed to be supported by the cpu, also PML4 (which we have api's for both of them).

All the capabilities are in appendix A.10 on intel developer manual.

**Comment by rianquinn** [comment]
@mor619dx My currently plan was to throw if you attempt to use the API and it's not supported by the hardware. We have the intrinsics / VMCS namespace logic now that makes detecting these features pretty trivial (both for us, and for the user of these APIs)

Thoughts?

Also... are there any APIs that you have that you think we are missing? I'm really interested to know if what I am proposing is enough to get the job done, without there being a ton of duplication across projects (i.e. users)

**Comment by connojd** [comment]
@rianquinn my only question... are the types of the parameters you used for the api functions actual types i.e. is `guest_physical` a type?  I think it may be beneficial to make them types if they aren't.

**Comment by rianquinn** [comment]
@connojd yes, these will be aliased types, likely as follows:

```cpp
using gpa_type = uintptr_t;
using integer_pointer = uintptr_t; // in place for `physical` above
```

**Comment by connojd** [comment]
Ok looks good to me then 👍

**Comment by mor619dx** [comment]
@rianquinn It is ok to throw exeception in case feature is not supported but my concern is features that covers not a specific api (unlike setting execute only page).

For example ept & vpid combination, sure I will use vpid along with ept if the hardware supports it but in case vpid is not supported I can still use ept (with performance downgrade) in my hypervisor.
if the enable_ept function will not work without vpid support I will still want to support the systems that have only ept (i'm ok with enable_ept function to still enable ept but will throw vpid exception in case it's not supported).

The only additional feature that we need in field of ept (which related to this module) is eptp switching and easy to handle ept violations.

**Comment by rianquinn** [comment]
@mor619dx Ok... I can relax the requirement for VPID. Didn't realize you could actually have EPT without VPID (do you have an example of such a system?), but yeah, I can remove that requirement. 

As for EPTP switching and EPT violations, I'll take a look and report back.

**Comment by brendank310** [comment]
Yeah I'd be curious if there was a post-Westmere system that didn't come with both. Both seem to have been introduced in Nehalem.

**Comment by rianquinn** [comment]
@mor619dx does the following namespace logic meet your needs: [here](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/vmcs/vmcs_intel_x64_natural_width_read_only_data_fields.h#L1159)? If not, in addition to the provided parsing logic, what else would you like to see as I would like to make sure it's in there if possible. 

As for EPTP switching, we actually have more than one person interested in this, but I would like to address it in a future RFC, as that would introduce support for VM functions, which we want to support, but I think it deserves it's own topic.

**Comment by mor619dx** [comment]
I encounter ept exist without vpid while running under vmware (might have been just a bug), but other than that I don't really know cpu which come without vpid (and with ept) - but the bigger idea of blocking usage of one api because an optional one doesn't exist can probably cause some problems to someone, so we should look up to that.

Indeed we also make use of vmfunc (if possible) or virtualize vmfunc if it's not existing, I will look forward to the rfc.

**Comment by rianquinn** [comment]
@mor619dx Are the EPT violation APIs [here](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/vmcs/vmcs_intel_x64_natural_width_read_only_data_fields.h#L1159) ok?

**Comment by mor619dx** [comment]
Missed the question from before, Yeah it's looking good to me.

**Comment by rianquinn** [comment]
I almost have this work completed (should have a PR in tomorrow). One thing that I noticed is that on VMWare, 1GB pages are not supported (at least on my brand new hardware it's not). We could check when using the 1GB APIs, but that seems like wasted time, and should probably be left to the user. The APIs for checking support are already in the MSR logic in Bareflank. 

```
intel_x64::msrs::ia32_vmx_ept_vpid_cap::pde_2mb_support::get()
```

**Comment by rianquinn** [comment]
Oh.. and the class names (to keep the code smaller) are:

```
ept_intel_x64
ept_entry_intel_x64
```

**Comment by rianquinn** [comment]
There is no needed for the _xxx specialization of this function, so I'm removing it:

```cpp
void remove_page_512g(guest_physical addr);
void remove_page_1g(guest_physical addr);
void remove_page_2m(guest_physical addr);
void remove_page_4k(guest_physical addr);
```

Simply call:

```cpp
void remove_page(integer_pointer gpa);
```

**Comment by rianquinn** [comment]
I am also removing the 512g versions as that is not supported at all by hardware. Although, I guess Intel is adding a 5th level of paging since people are hitting the 256 TB limit, but my guess is pdpt's will still be required.

**Comment by rianquinn** [comment]
Here are the final APIs that I ended up with. I added identity map APIs as that is used a lot, so might as well. 

```cpp
void enable_ept();

void disable_ept();

void map_1g(integer_pointer gpa, integer_pointer phys_addr, attr_type attr)
{ this->map(gpa, phys_addr, attr, intel_x64::ept::pdpt::size_bytes); }

void map_2m(integer_pointer gpa, integer_pointer phys_addr, attr_type attr)
{ this->map(gpa, phys_addr, attr, intel_x64::ept::pd::size_bytes); }

void map_4k(integer_pointer gpa, integer_pointer phys_addr, attr_type attr)
{ this->map(gpa, phys_addr, attr, intel_x64::ept::pt::size_bytes); }

void unmap(integer_pointer gpa) noexcept;

void setup_ept_identity_map_1g(integer_pointer saddr, integer_pointer eaddr);
void setup_ept_identity_map_2m(integer_pointer saddr, integer_pointer eaddr);
void setup_ept_identity_map_4k(integer_pointer saddr, integer_pointer eaddr);

gsl::not_null<ept_entry_intel_x64 *> gpa_to_pte(integer_pointer gpa);
```

The identity map APIs allow you to specify the granularity. For hypervisors like [SimpleVisor](https://github.com/ionescu007/SimpleVisor), you would want to use the lowest granularity you can to save memory usage. But for hypervisors like [MoRE](https://github.com/ainfosec/MoRE) or [DdiMon](https://github.com/tandasat/DdiMon), you would want to increase the granularity to likely 2mb on 64bit systems (as most linkers align to 2mb on 64bit), and 4k is available if you have a lot of memory to spare, and you want really good granularity. 

Once you have an identity map setup, you can use the `gpa_to_pte()` lookup function to find the EPTE associated with a specific guest physical address. Tomorrow I am going to move [this](https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/memory_manager/map_ptr_x64.h#L805) code to `memory_manager/helpers_x64.h` file in Bareflank so that it can be used by more than just the map code, and then I will a `virt_to_phys_with_cr3()` version (that just returns the pte's physical address) so that users can lookup the physical address of a virtual address that is supplied with a vmcall, and then locate the EPTE using `gpa_to_pte()`, and mark the memory as desired. Once I have the EPT logic in place, I will create an example extension for the Extended APIs that demonstrates hooking a function in a userspace app to call a different function. Should be a really useful example, and it will also help to weed out any remaining issues with the APIs, and I don't think it will take too long to sort out.

**Comment by mor619dx** [comment]
@rianquinn I use VMWare as well and I have support in pml4 (intel_x64::msrs::ia32_vmx_ept_vpid_cap::page_walk_length_of_4::get()), also on physical machine it exists - ddimon for example require it to run. I use it on long mode (64bit) with 4kib pages.

Also i'm interested does the map which stores the gpa to pa is actuall a c++ map or does it just a name to a simple page table structure?

**Comment by rianquinn** [comment]
@mor619dx it's just a name for a page table structure. In Bareflank, for the VMM, we do store virt -> phys, phys -> virt and virt -> attr mappings in a std::map, but the actual root_page_table->map() function actually maps a phys -> virt in the root page table (very similar to mmap). In this case, the ept->map() maps a phys -> gpa, with the big difference being that you can map different sizes. I might (in version 1.2) add this feature to Bareflank's memory manager so that you can handle large pages as well, but for now it only handles 4k pages. Seemed insane to be to only support 4k pages in EPT because in a lot of cases, people don't need to spend that much memory (and in fact... there isn't enough memory in Bareflank to support 4G of 4k pages, you would have to increase the statically allocated memory to pull that off).

**Comment by rianquinn** [comment]
@mor619dx also... you can see my EPT implementation here as I have posted it already. I have to finish the unit tests still, but most of it is there and working:

https://github.com/rianquinn/extended_apis

**Comment by rianquinn** [comment]
Completed: https://github.com/Bareflank/extended_apis/pull/5

**Comment by rianquinn** [comment]
Example Usages: https://github.com/Bareflank/extended_apis_example_hook

**Comment by rianquinn** [comment]
I am updating the APIs for EPT so that we can have more than one EPT if needed. This will be needed for both EPT switching and guest support. To support this, I am moving the APIs from the VMCS to a root_ept_intel_x64 class that is the same thing as the root_page_table_x64 class in Bareflank for the CR3 based page tables. In addition, I'm adding a set_eptp() function that will take as a parameter the root_ept_intel_x64, and set the EPTP accordingly.
