### ISSUE TITLE
Making a Type 1 Hypervisor?

### ISSUE THREAD

**Issue by mingwayzhang** [Bareflank/hypervisor#417]
Hi,

I am new to bareflank and I am just able start bareflank according to the readme. However, it looks like that current setup is to use bareflank as a host based hypervisor (like kvm). So, could you let me know how could I use it as a type 1 hypervisor? Thanks.

-Mingwei

**Comment by rianquinn** [comment]
@mingwayzhang Thanks a ton for the interest in our project. 

Type 1 will be supported once we start Bareflank 1.2. Specifically, we will be adding UEFI support with hopes of being able to start both Windows and Linux **after** Bareflank has been loaded. We should be releasing rc1.1.1 in the next day or so, and then we begin testing for the final v1.1. As soon as that is done, I will be starting this work, as well as a new SLAB allocator to help with some fragmentation issues. My hope is to have basic UEFI support in the next month, with Windows, Linux and Multi-Core support for UEFI in the months to follow. 

Did that answer your question? Also, let us know if there is anything else you would like to see.

**Comment by rianquinn** [comment]
@mingwayzhang Feel free to reach out to us if you need anything else.
