### ISSUE TITLE
[RFC]: Header cleanup

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#438]
We have a lot of headers that implement all of the intrinsics and VMCS logic found in the Intel SDM. We have had a couple of complaints about the VMM not being the "bare" minimum because we have so many of these definitions defined in files like the following:

https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/vmcs/vmcs_intel_x64_64bit_control_fields.h

In v1.2 we are considering moving these headers to the Extended APIs to reduce the amount of code in the hypervisor repo. The code would still be there, but you would need the Extended APIs to get to it. Some of this code (probably 10%) is required as it is being used by the hypervisor. The down side to this is if we move this code to the Extended APIs to keep the hypervisor smaller, this logic will be oddly divided between two repos. 

For example:
```cpp
namespace basic_exit_reason
{
        constexpr const auto mask = 0x000000000000FFFFUL;
        constexpr const auto from = 0;
        constexpr const auto name = "basic_exit_reason";

        constexpr const auto exception_or_non_maskable_interrupt = 0U;
        constexpr const auto external_interrupt = 1U;
        constexpr const auto triple_fault = 2U;
        constexpr const auto init_signal = 3U;
        constexpr const auto sipi = 4U;
        constexpr const auto smi = 5U;
        constexpr const auto other_smi = 6U;
        constexpr const auto interrupt_window = 7U;
        ...
```

Not all of these are needed by the hypervisor, but are likely needed by the Extended APIs and Bareflank user extensions. The couple that are used by the hypervisor repo would stay, but the rest would be moved to the Extended APIs. As users... you would have to know which repo the definition was in. 

IMO... we leave it as is since these are just headers and are not compiled into your code unless you need them, but I figured I would toss the question out to everyone to see what your thoughts are. Do you want to see the repo smaller, more complete? 

In either case, we are still working hard to keep the ".cpp" files as small as possible, and with respect to that, we will be moving the JSON based vmcall logic to the Extended APIs as this is not needed in the main repo. 

Thoughts?

**Comment by connojd** [comment]
For someone new, all that code does is add about 20K lines of noise.  Moving them out would make it much easier for a newcomer to the project to become familiar with Bareflank.  I'm also in favor of keeping only the code that is strictly necessary for Bareflank in the hypervisor tree. It reduces the complexity, which makes it easier to grasp, lowers the barrier to entry, and reduces the potential for bugs.

**Comment by carter-yagemann** [comment]
This RFC raises an interesting point. Not only do the headers add noise for new developers, as @connojd pointed out, but they aren't complete either for experienced developers (e.g., the Intel x86 MRS header is missing MSRs, the VMCS header is missing some 32bit control fields, the CPUID header is missing subleafs, etc.).

I'm not sure what the answer is. Maybe define *everything* somewhere and then have the developer pick and choose what to add to their project?

**Comment by rianquinn** [comment]
Yeah the intrinsics code needs more work to complete that logic as you are right, it's missing stuff. What 32bit control fields are missing OOC? 

So yeah, I guess I'm looking for more input. The best way to let them "choose" is to only keep what is needed in Bareflank, and move all of the extra code to the Extended APIs. If they want the extra logic, they use the Extended APIs. Since everything is in namespaces, you can add to an existing namespace without an issue. 

Ok... So the running total is:
+2 for removing
+1 for keeping

Any other votes?
@josephsharkey @brendank310 @ktemkin @RicoAntonioFelix @mor619dx

**Comment by carter-yagemann** [comment]
@rianquinn 

Since my research focuses around PT, the stuff I've noticed are PT related. For VMCS 32-bit control fields:

- pt_conceal_vm_exits (vmcs::vm_exit_controls, bit 24)

- pt_conceal_vm_entries (vmcs::vm_entry_controls, bit 17)

- pt_conceal_vmx_non_root_operation (vmcs::secondary_processor_based_vm_execution_controls, bit 19)

For MSRs:

- ia32_rtit_ctl (addr 0x570)

- ia32_rtit_status (addr 0x571)

- ia32_rtit_cr3_match (addr 0x572)

- etc.

**Comment by brendank310** [comment]
I'm +1 on keeping them. Pushing them to the extended repos makes anyone wanting to utilize any separated fields have to pull in the extended APIs with features they may not be interested in. I see these headers as complimentary to the manuals, and if there are gaps in the coverage, I'd rather those gaps be filled than splitting the coverage between two repos where it would be hard to verify their completeness. While they make the SLOC count metric less flattering, it is unlikely that they translate into any code after compilation. The SLOC situation is only going to get worse as other architectures get introduced (ARM, AMD). From the perspective of the code base being too daunting to newcomers, I'd rather provide a 'tour' of the source code than just try to hide the fact that the architecture is... complicated.

**Comment by rianquinn** [comment]
One option that could fix both issues here (trying to find compromise to get consensus), is for the includes to be placed into their own repo, separate from the extended_apis... something like bfincludes (the v1.2 build system already breaks everything up into ~8 repos, adding one more is no big deal). We could then use "__has_include" in the main repo to auto include these includes if they exist so all the developer would have to do is install the bfincludes into the prefix, and they would be there and working. All of the unit tests for the includes would be in this same repo both reducing SLOC, but also simplifying everything for Bareflank without requiring the extended_apis. Finally... the "hypervisor" repo in v1.2 will end up just being a CMakeLists.txt that uses CMake's super build functionality to download the bfsdk, bfsysroot, bfm, bfdriver, and bfvmm repos and build them. We could add a -DBFINCLUDES=on to the cmake script to auto download and install the repo. 

Thoughts?

**Comment by RicoAntonioFelix** [comment]
I'm +1 for keeping...

Rationale:
* Headers are included into an application/module based on needs which imply that the user only concerns him/herself with what's needed for the task at hand
* Splitting them out to the Extended APIs don't solve the problem simply because doing so will also bring extra stuff into one's environment that may not be needed
* Moving around complexity doesn't change the fact that complexity exists, in this case, it only adds dimension which introduces more complexity

**Comment by carter-yagemann** [comment]
@rianquinn That's an interesting build system. When the time comes I'll be interested to hear how you manage that many git repos (e.g., pulling new commits).

To revise my earlier position, given the choice between keep or remove (disregarding the new build system for a moment), my first choice would be to keep _and_ make the headers complete, second choice would be remove. What I was really trying to get at is the worst option (imo) is to be in a "wishy-washy" in between state.

The new build system could be a reasonable compromise, but I'll wait to hear the details about how it works.

**Comment by rianquinn** [comment]
@carter-yagemann To get a feel for it, I am currently working on the following:
https://github.com/Bareflank/bfsdk
https://github.com/Bareflank/bfelf_loader

The SDK is were my current attention is. I have it working with Ubuntu and Windows. One big difference is that with Windows, it compiles using Cygwin, NMake, MSBuild, and the Linux Subsystem for Windows 10 (testing that now... keep your fingers crossed). The ELF loader is pretty cool as the unit tests now work on Windows, and it's independent, so people who want to bootstrap C++ can use these individual repos to do that, without having to use the VMM if they do not want.

To answer your question, repo management is up to you (there are a lot of different options that already exist). CMake will do this for you. But you can also download each repo and build, update, etc... yourself, and use your own repo management tool if you wish. There are a lot of options, and it will depend on the person.

**Comment by rianquinn** [comment]
As for the vote.... we are at:

+4 Keep (with the intent to complete the headers)
+1 Remove

@connojd Is there anything you would like to see if we decide to keep? Any ideas on how to address your issue of complexity without moving the headers to another repo?

**Comment by connojd** [comment]
@rianquinn... it makes no difference to me personally.  I wrote ~98% of that code anyway so I know my way around it :smirk:.  I was just trying to view it from an early-adopters point of view.

**Comment by rianquinn** [comment]
Ok... so lets use this forum to start a list of the headers that need to be completed still:

**VMCS**:
- pt_conceal_vm_exits (vmcs::vm_exit_controls, bit 24)
- pt_conceal_vm_entries (vmcs::vm_entry_controls, bit 17)
- pt_conceal_vmx_non_root_operation (vmcs::secondary_processor_based_vm_execution_controls, bit 19)

MSRs:
- ia32_rtit_ctl (addr 0x570)
- ia32_rtit_status (addr 0x571)
- ia32_rtit_cr3_match (addr 0x572)
- APIC MSRs

CPUID:
- All subleafs 


Anything else? Now is the time to get it in. If you guys get a chance, take a once over the SDM for things that you think you will need. 

@connojd Oh.... and one idea I would be to place all of the VMCS namespace logic into the intrinsics module. This way... ALL of this logic is in one place, and the VMCS is simple.

**Comment by connojd** [comment]
@rianquinn I'd be fine with that

**Comment by carter-yagemann** [comment]
The full list of MSRs is in Intel ASDM Vol 3, Chapter 35. Chapter 35.1, Table 35-2 are the MSRs that aren't expected to change in future model releases. It's a pretty long list...

The PT related VMCS fields are in Vol 3, Chapter 36.5.1, Table 36-46. I don't know if there's a master table anywhere for *every* VMCS field.

The full list of CPUID leafs is in Vol 2, Chapter 3.2, Table 3-8. It's also very large...

**Comment by rianquinn** [comment]
So for now I think we are likely to take on the remaining VMCS fields, and the CPUID fields. We (as in myself and @connojd) don't have enough time to work on all of the MSRs at the moment, but we will work to get in what we can outside of the list above. PR's welcome 😄 

FYI... these changes are part of v1.2 so work on them should be done on the bfvmm repo (will be created tomorrow as @connojd will be working on that starting Monday).

**Comment by rianquinn** [comment]
@connojd and @JWZepf are working this now.
