### ISSUE TITLE
error when running MAKE

### ISSUE THREAD

**Issue by penhoi** [Bareflank/hypervisor#446]
I got the following message when running MAKE:

Cloning into 'source_libbfc'...
fatal: could not read Username for 'https://github.com': No such device or address

Moreover, i found that there is no repository named libbfc.git

**Comment by rianquinn** [comment]
@penhoi sorry about that. We will be releasing v1.1 and deprecating v1.0 this week and as part of that we removed libbfc. The code for that is now in the main hypervisor repo under bfvmm. For now I would use master as it works really well, and will likely be the v1.1 that you see (minus maybe some doc changes). 

If you have any other issues, feel free to let us know.
