### ISSUE TITLE
[RFC]: extended_apis: control register access exit handling

### ISSUE THREAD

**Issue by scalys7** [Bareflank/hypervisor#450]
I would like to add an API to support handling control register accesses for both monitoring and intervening objectives.

This API was originally designed for cr3, but I think that the same design would fit all control registers (cr0, cr3, cr4 and cr8); that being said, I currently do not wish to handle special cases (e.g., cr4 shadow etc.); I will leave that to the callback function's logic.

# Proposed APIs:
   - void enable_cr0_load_hook(cr0_value_type (*callback)(cr0_value_type), uint64_t cr0_guest_host_mask, uint64_t cr0_read_shadow);

   - void enable_cr3_load_hook(cr3_value_type (*callback)(cr3_value_type));

   - void enable_cr3_store_hook(cr3_value_type (*callback)(cr3_value_type));

  -  void enable_cr4_load_hook(cr4_value_type (*callback)(cr4_value_type), uint64_t cr4_guest_host_mask, uint64_t cr4_read_shadow);

where the signature for the load and store callbacks receive the cr3 value (to be stored or loaded) and returns the cr3 value to be actually stored or loaded.
If the callback is for monitoring only, it can perform whichever bookkeeping operations it wishes and return the value given; if it is for intervening, it can modify the value however it wants and return the new value that will be set.
  - void disable_cr0_load_hook();

  -  void disable_cr3_load_hook();

  -   void disable_cr3_store_hook();

  -    void disable_cr4_load_hook();
which will simply disable the exit controls for that register.

The control flow will build upon the design of @connojd in https://github.com/connojd/extended_apis/blob/ecr/src/exit_handler/src/exit_handler_intel_x64_eapis.cpp:

1. exit_handler_intel_x64_eapis::handle_exit would check for control_register_accesses.
2. exit_handler_intel_x64_eapis::handle_exit__ctl_reg_access()
which will switch on the register number, read the value about to be read/set, and call the callbacks     that were set with vmcs::enable_control_register_access_hook. It will then emulate the instruction by setting the returned value from the callback to the required register (the cr in a load, or the gpr in a store) in the VMCS guest area, then calling
3. exit_handler_intel_x64_eapis::advance_and_resume().

# Default
It will be disabled by default.

**Comment by rianquinn** [comment]
@scalys7 This sounds great. Could minor questions / comments:
- We should have this setup for all of the CRs including CR0 (wasn't mentioned above). 
- Should we use the index or should be have a set of functions for each CR? Like enable_cr0_access_hook? This way there is less testing involved because you don't have to have code to check the cr #. 
- We should use a C++ alias instead of UNIT64, this way we can change the type if need be in the future. 

Other than that... nice RFC!

**Comment by scalys7** [comment]
On the first point, i've updated the rfc.

The second, I don't see how beneficial (performance wise) it will be, as the switch on the cr number will only be avoided on enable/disable and not in the exit handler which is heavier. Then it all comes down to ease of usage; I can go with both ways, whichever seems nicer to you guys.

The third, no problem, but do you mean use a predefined alias (if so, which one?) or one made up for this purpose?

**Comment by rianquinn** [comment]
I think I would prefer enable_cr0_access_hook/disable_cr0_access_hook, and so on as providing a CR# as part of the API would require an enum which would be more verbose, and a bit more cumbersome. 

Each CR already has it's own alias:
https://github.com/Bareflank/hypervisor/blob/master/bfvmm/include/intrinsics/crs_intel_x64.h#L46

So you should be able to use this, in an alias defined in the VMCS. Something like:

```
using cr0_value_type = intel_x64::cr0::value_type
```

**Comment by scalys7** [comment]
In that case, I prefered adding a different api for store & load, as someone might care for stores/loads only, and this could affect performance vastly as it can prevent unnecessary vm-exits.

See my updated rfc.

**Comment by rianquinn** [comment]
LGTM +1

**Comment by rianquinn** [comment]
@connojd @brendank310 ?

**Comment by scalys7** [comment]
A few comments after starting to play with the code:

1.  There is only a store/load cr3 and cr8 execution control; for cr0 and cr4, the following is stated by the Intel manual:

> MOV to CR0. The MOV to CR0 instruction causes a VM exit unless the value of its source operand
> matches, for the position of each bit set in the CR0 guest/host mask, the corresponding bit in the CR0 
> read shadow. (If every bit is clear in the CR0 guest/host mask, MOV to CR0 cannot cause a VM exit.)

same goes for cr4. This means that if I'd want enable_cr0_load_hook to actually assert that all loads will execute our hook, I'd have to modify the mask and shadow and make sure that it will never match the above conditions. Would that something that you'd want me to do?
My recommendation would be not to do so, and to only hook these commands when they do not match the normal conditions; this way, we can let the user decide whether he wants to hook all the commands or only the ones that cause an exit normally. 

Also, note that for cr0 and cr4, store never exists!
Thus I will remove the store APIs for them.

2. There isn't an alias for cr8. Should I create one? I forked the extended-eapis repo, and the appropriate spot for that alias should be crs_intel_x64.h...

3. I'm thinking that vmcs isn't the appropriate namespace for these APIs. I think exit_handler_intel_x64_eapis will do the job.

What are your thoughts?

**Comment by rianquinn** [comment]
1:
Probably best to provide in your RFC, the APIs for all 4 registers, as I bet they will not all look the same. For 3 and 8, what you have will work. For 0 and 4, the user should provide the desired mask for load, and as you stated, there would be no APIs for store. 

2:
Your right, we are missing CR8. @JWZepf Feel free to provide a PR for the hypervisor repo that adds this missing set of APIs. That was my bad as I forgot to add them. 

3: 
Right now, all of the APIs for setting up the VMCS are in the VMCS namespace. Out of curiosity, why exit_handler_intel_x64_eapis? 

So far, I think this is really shaping up to look pretty awesome. Thanks for the hard work.

**Comment by connojd** [comment]
@scalys7 LGTM. I agree with @rianquinn with putting the enable/disable functions in the VMCS though

**Comment by scalys7** [comment]
So I updated my RFC; a few notes/questions:
1. In cr0/cr4 load hooks, should I check / force the masks to specific actions in regards to certain fields? or should I let the programmer live with the consequences?
E.g., the vmx enable bit of cr4.
2.  For the cr8 hooks, I am waiting for you to add a cr8_value_type.

**Comment by rianquinn** [comment]
@scalys7 Crap.... sorry about that. I'll have that up in ASAP. As for #1, let them live with the consequences for now.

**Comment by rianquinn** [comment]
The PR for this was merged. Once I do some additional cleanup, and merge this work into v1.2, I will close this ticket. Great job @scalys7

**Comment by rianquinn** [comment]
The updates can be here. The only functional change was the VMCS doesn't register a callback, but rather the exit handler has a set of callbacks that can be overloaded. 
https://github.com/Bareflank/extended_apis/commit/547fe82079c42c1d1535909efcd90a18ca933058

This code has also been cleaned up so that it will be accepted by the 1.2 build system as well, and the port of that code is complete.
