### ISSUE TITLE
[Bug] Fix for the build_windows.bat file

### ISSUE THREAD

**Issue by Randshot** [Bareflank/hypervisor#451]
Hey,

I noticed that when you try to execute `make driver_load` on a different drive than `C` on Windows, it complains about `LaunchBuildEnv.cmd` not being a valid command/file.
To fix this, I had to change the `cd` commands to include `/D`, which forces a drive change.
From the `cd` documentation:
```
Use the /D switch to change current drive in addition to changing current
directory for a drive.
```

In short:
`cd C:\ewdk\` -> `cd /D C:\ewdk\`.
`cd %1` -> `cd /D %1`

**Comment by rianquinn** [comment]
Thanks a ton for the bug report. Would you like to post a PR for this change?

**Comment by Randshot** [comment]
Sure, I will do that in a moment.
