### ISSUE TITLE
[Bug] Add cmake to the cygwin install targets on Windows

### ISSUE THREAD

**Issue by Randshot** [Bareflank/hypervisor#452]
Hey,

when I tried to compile the hypervisor for the first time, I came across an issue, where cmake wouldn't compile libc++(abi).
After some research, I found out, that my cmake installation wouldn't accept cygwin paths.
To solve this, I had to additionally install the cygwin version of cmake.
After doing that, it compiled without issues.

**Comment by rianquinn** [comment]
That's strange, your right that cmake is missing from the setup script. The question is... how is it that our Jenkin's server can build and run on cygwin without an issue? At any rate, I agree that cmake should be added to the list. Would you like to provide a PR for this?
