### ISSUE TITLE
[RFC] bfvmm: intrinsics expansion and reorganization

### ISSUE THREAD

**Issue by JWZepf** [Bareflank/hypervisor#459]
The goal of this project is to reorganize the intrinsics headers located in bfvmm as well as implement some missing functions from the Intel SDM.

By reorganizing the intrinsics and VMCS logic, it should be easier for developers to pick the intrinsics functions that are applicable to their project while avoiding functions they do not need. By implementing the missing intrinsics functions, the headers will be more complete providing enhanced functionality to users.

# Proposed API and Testing Changes
In the bfvmm repository, intrinsics logic will be implemented in `bfvmm/include/intrinsics/x86/`. Functions that are used by both Intel and AMD processors will belong in the `bfvmm/include/intrinsics/x86/common/` directory while Intel specific functions will belong in the `bfvmm/include/intrinsics/x86/intel/` directory. Within each of these directories will be a directory for MSR headers and CPUID headers. VMCS headers will be located in the `bfvmm/include/intrinsics/x86/intel/` directory. This organization allows for users who only want to use common intrinsics to just include the common headers.

In addition, currently all tests for a lot of the vmcs headers are located in `bfvmm/src/intrinsics/tests/test_vmcs_intel_x64.cpp`. I plan on breaking up this test file into multiple test files. Each header in `bfvmm/include/intrinsics/x86/intel/vmcs/` will have a corresponding test file in `bfvmm/src/intrinsics/tests`.

I also plan on expanding some of the incomplete intrinsics headers. All the CPUID fields will be implemented (Intel SDM Volume 2 Chapter 3.2 Table 3-8). All Architectural MSR instructions will be implemented (Intel SDM Volume 4 Chapter 2.1 Table 2-2).

The following VMCS functions will also be added:
* pt_conceal_vm_exits (vmcs::vm_exit_controls, bit 24)
* pt_conceal_vm_entries (vmcs::vm_entry_controls, bit 17)
* pt_conceal_vmx_non_root_operation (vmcs::secondary_processor_based_vm_execution_controls, bit 19)

# Default
N/A

**Comment by rianquinn** [comment]
👍

**Comment by rianquinn** [comment]
All of the code changes are in, all that's left is some cleanup of the unit tests.

**Comment by rianquinn** [comment]
Done
