### ISSUE TITLE
Can't make bareflank produce serial output

### ISSUE THREAD

**Issue by nick-kvmhv** [Bareflank/hypervisor#485]
I was able to get serial output when starting bareflank on a virtual machine. Now I am trying to use it on a real hardware with a real NULL modem cable and so far I was unable to make it work.
- COM port by itself works and Windows Device Manager shows 03F8-03FF as the I/O range
- I can see the output if I use cat /dev/ttyUSB0 on the receiving machine and echo "something" > /dev/ttyS0 on the machine with bareflank (from cygwin prompt)
- Bareflank itself works and I can see the debug ring output from make dump. 
I added some printouts to serial_port_intel_x64.cpp to the get_baud_rate() function and apparently it goes to the default branch in the case because both port reads return 255 and not the expected divisor.  I tried changing the default baud rate in constants.h from 9600 to 115200 with no success. Anything I may be missing here? 
Also, I am running it on i7-875k which is one architecture behind the supported one and other than this serial issue it works fine. I assume this is why I am getting these two warnings:
``WARNING: set_vm_control_if_allowed failed: enable_invpcidcontrol is not allowed to be set to 1
WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
``

**Comment by rianquinn** [comment]
Yes, those two warnings can be safely ignored on a lot of systems. I use serial on my ASUS Skylake machine running Windows and Linux all the time without issue (using a null modem cable and USB converter to my Macbook). 

Now that being said, serial doesn't work with Windows on VMWare, and we still have not figured out why. The serial logic is straight out of OSDev, and their code fails as well so it's possible there is something else going on here (for example, it might be a different serial device). Without more information, or a similar box it's going to be really hard to debug this but I'll help as much as I can from this end.

**Comment by nick-kvmhv** [comment]
Just tried to boot the same PC from Ubuntu 16.04 and serial output works there, so it is Windows 10 issue.

**Comment by rianquinn** [comment]
Huh, so this is the first time we have seen this issue on real hardware. I have even tried setting up more than one serial device to see if Windows was trying to use the device, but that doesn't work either. That being said, based on your test, it sounds like if we can get it working in VMWare, we can also get it working for your case as well. I'm just not sure where to start.

**Comment by nick-kvmhv** [comment]
Do you mind referencing that OSDev code that fails on VMWare?

**Comment by nick-kvmhv** [comment]
Ok, here is how to solve the issue:
In regedit find ``HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\``
For the following 3 keys (could be any combination, haven't tested) change Start from 3 to 4:
- Serial
- Serenum
- sermouse
This prevents Windows from loading anything COM1 related and that seems to be enough for the issue to go away.

**Comment by rianquinn** [comment]
@nick-kvmhv Is Bareflank working for you on Windows? If so, which version of Windows 10?

**Comment by nick-kvmhv** [comment]
I am using Windows 10 Pro. I had to upgrade from Windows 7 because it was unsupported. After I disabled those 3 drivers, I also see serial output from it.

**Comment by rianquinn** [comment]
Windows is working for me now, I was running into some stupid build issues. I can also confirm that you only need to turn off the Serial driver, and this is the one-liner that you can use:
```
reg add "HKEY_LOCAL_MACHINE\System\CurrentControlSet\Services\Serial" /f /v "start" /t REG_DWORD /d "4"
```
