### ISSUE TITLE
setup_archlinux.sh is out of date

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#490]
`setup_archlinux.sh` appears to be out of date. It fails when it tries to call a `check_hardware` function which doesn't seem to exist anymore. Furthermore, it installs docker, which none of the other setup scripts do, so I assume this is something that has changed when it was written.

    % ./tools/scripts/setup_archlinux.sh
    ./tools/scripts/setup_archlinux.sh: line 31: check_hardware: command not found

**Comment by rianquinn** [comment]
Feel free to update that script as knowbody is maintaining it. Now... that being said, please do all new development using the "dev" branch and not master as master is really out of date.

**Comment by cpavlina** [comment]
Am I correct in thinking the references to docker can just be removed?

**Comment by rianquinn** [comment]
Yeah, docker is not used at all.

**Comment by rianquinn** [comment]
@cpavlina any updates on this?

**Comment by cpavlina** [comment]
I'll submit a PR later today.
