### ISSUE TITLE
[RFC] bfelf_loader: aarch64 relocations

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#496]
# Description

In order to properly load aarch64 binaries we need to support the relocations specific to that architecture. There are a large number of these (81 in the [ELF for ARM 64 manual](http://infocenter.arm.com/help/topic/com.arm.doc.ihi0056b/IHI0056B_aaelf64.pdf)) but we probably don't need them all. I don't think I need to start on this for the rest of the week or so; creating this RFC now so we have time to discuss.

# Proposed changes

- Extract "ELF Relocations" section of `bfelf_loader.h` to a separate definitions file. That header is already quite long and dumping in a pile of aarch64 relocs won't help.
- Implement aarch64 relocations in the same way x86_64 are now, with no compile-time switch - I can't think of any reason e.g. x86_64 builds must not contain the aarch64 code, and it simplifies the structure not to switch sections in and out.
- Depending on how many of the aarch64 relocations we end up having to implement, consider placing the code to do them also in a separate file, `bfelf_aarch64_reloc.h` or similar. The x86_64 ones can be moved out for consistency as well.
- Compile-time switch can simply be around the section which checks `e_machine` to verify the file being loaded is for the correct architecture. This should require no changes to the build system as there is no foreseeable reason for the loader to be compiled for a different arch than the files it loads, so the compiler-defined macros `__x86_64__` and `__aarch64__` can be used.
- Add tests to verify the behavior of the new relocations.
- No API changes are necessary.

**Comment by rianquinn** [comment]
I think your proposal so far. I would name the two new files:
- bfelf_loader_reloc_x64.h
- bfelf_loader_reloc_aarch64.h

The main file would simply call the reloc function, and the above two files would both implement the same function but for the specific arch they support. You would also then have to either use cmake to add this additional file to the main one on install, or install the arch specific header along with the main header. 

Everything else sounds great. The tests should work the same as they do now, allowing you to execute an ELF binary from userspace on an ARM device.

**Comment by connojd** [comment]
:+1:

**Comment by connojd** [comment]
see #549
