### ISSUE TITLE
[BUG] Compilation Issue

### ISSUE THREAD

**Issue by CiraciNicolo** [Bareflank/hypervisor#497]
I get this error when I make the project:

```
cp  default.out
cp: missing destination file operand after 'default.out'
Try 'cp --help' for more information.
<builtin>: recipe for target 'default.out' failed
make: *** [default.out] Error 1

```

I don't understand which Makefile causes this issue.

**Comment by rianquinn** [comment]
Please provide the build steps you used to make the project. Also, are you using v1.1 or the "dev" branch?

**Comment by rianquinn** [comment]
Huh, I will setup a VM and give it a shot. Are you using stretch?

**Comment by CiraciNicolo** [comment]
Yep, I'm using Debian 9.1

**Comment by rianquinn** [comment]
I just did a fresh install of Debian 9.1 (gnome), and everything compiled and ran without issue. I didn't try v1.1.0 but used master. Have you tried master?

**Comment by rianquinn** [comment]
Just tried v1.1.0 and it worked fine too

**Comment by CiraciNicolo** [comment]
Clean install and it worked.

**Comment by CiraciNicolo** [comment]
Issue reappeared in a clean VM. Just installed debian, cloned bareflank, setup it and make give me the same issues as before.

**Comment by CiraciNicolo** [comment]
OS is Debian 9.2

**Comment by CiraciNicolo** [comment]
This issue appears also on bare machine (not VM)

**Comment by rianquinn** [comment]
I have yet to test Debian 9.2 so I will take a look at that.

**Comment by CiraciNicolo** [comment]
I investigated a little more, and it seems that the compilation is indeed working. I can load, start, get status, dump and make vmcall. I get the same error at the end of make. These are the output of the other commands:

```
cyrak@cyrak:~/hypervisor$ make load
cyrak@cyrak:~/hypervisor$ make start
cyrak@cyrak:~/hypervisor$ make status
VMM_RUNNING
cyrak@cyrak:~/hypervisor$ make dump
WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
DEBUG: success: host os is now in a vm on vcpuid = 0
WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
DEBUG: success: host os is now in a vm on vcpuid = 1
WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
DEBUG: success: host os is now in a vm on vcpuid = 2
WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
DEBUG: success: host os is now in a vm on vcpuid = 3
cyrak@cyrak:~/hypervisor$ ARGS="versions 1" make vmcall
BAREFLANK_VERSION_MAJOR: 0x1
BAREFLANK_VERSION_MINOR: 0x1
BAREFLANK_VERSION_PATCH: 0
cyrak@cyrak:~/hypervisor$ 
```

**Comment by rianquinn** [comment]
Yeah, that all looks great. If you are running on old hardware, or in VMWare, you will get those warnings. So far it seems you can safely ignore them.

**Comment by CiraciNicolo** [comment]
i5-4278U is considered old hardware? Do you have any ideas why that error is appearing?

**Comment by rianquinn** [comment]
Haswell usually has the XSAVE VMX secondary control. Are you running on bare metal, or are you running in VMWare?

**Comment by CiraciNicolo** [comment]
Both, the logs that I just posted were taken from a bare machine

**Comment by rianquinn** [comment]
Huh, so I'm not sure about the default.out issue, but the warning your getting can safely be ignored. It's just saying that your hardware is missing a VMX feature, but it's not needed. Once I get a chance, I will test out Debian 9.2 to see if I can repro the default.out issue

**Comment by CiraciNicolo** [comment]
Sorry to bother more, but I'm writing a custom exit handler (copying for the example) but I'm getting an error with `make quick` and also `make load`:

```
nested@debian:~/nested$ make quick
Caught unhandled exception:
    - what(): parse error - unexpected end of input; expected '}'
```

**Comment by rianquinn** [comment]
Likely your modules file, which is JSON, has invalid syntax

**Comment by rianquinn** [comment]
Oh, and you will be happy to know that we no longer need the modules file in v1.2

**Comment by CiraciNicolo** [comment]
I kinda like them, they are self-explanatory. Of course I did not know what is coming, so I should not judge.

**Comment by rianquinn** [comment]
Please use master
