### ISSUE TITLE
[RFC] Build System Support for Aarch64

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#498]
# Description
The current Bareflank build system supports building all components and external dependencies for the x86_64 architecture only. In order to expand support to other architectures, numerous changes to the build system must be made. This RFC proposes a list of changes to the build system that must be accomplished immediately in the short term, and also proposes some longer-term changes that will be more difficult or time consuming to implement.

There are a lot of proposed changes in this RFC, and it would probably make sense to break them down into smaller, separate RFCs after feedback is received. I'm hoping the community can use this RFC to come to consensus about necessary changes to the build system as a whole.

# Proposed Short Term Changes

The immediate short-term goal for build system is to allow for Bareflank components and external dependencies to build for both x86_64 and aarch64 by means of a cross-compiler toolchain. The changes proposed in this section are the bare minimum needed to add basic ARM support to the Bareflank build system:

* Add a mechanism to specify a cross-compile toolchain and/or architecture as input to the Bareflank build system. For an immediate first step, update the env.sh script to allow specifying a target OS and architecture as a parameter.
* Remove all checks from the build system that detect which OS and toolchain you have installed, and use the toolchain configured with env.sh instead.
* Remove nasm as a dependency for ARM builds (or remove it all together?). Use the assembler that comes with the clang toolchain
* Create a new toolchain file for aarch64 (hypervisor/bfsdk/cmake/CMakeToolchain_Aarch64) that will update all necessary cmake variables to make the build system use an ARM toolchain.
* Update or (more desirable) get rid of compiler_wrapper.sh in favor of calling the configured toolchain directly

# Proposed Long Term Changes

The changes proposed in this section are more long-term oriented goals that would help simplify and restructure the Bareflank build system, but will likely require more significant effort than the bare-minimum goals listed above:

* Update build system input mechanism so that it is compatible with bitbake/yocto. In other words, make sure that a Yocto-based toolchain can easily configure Bareflank's cmake system to build for the correct OS/architecture in the context of a larger project.
* Remove almost all configuration from the top-level CMakeLists.txt file, and rather use it as a way to orchestrate smaller, more specialized cmake files under hypervisor/bfsdk/cmake.
* Restructure cmake files that download external dependencies (top-level CMakeLists.txt file and hypervisor/bfsdk/CMakeLists.txt). Break these out into one/several separate cmake files under hypervisor/bfsdk/cmake.
* Allow external dependencies to download in parallel
* Reorganize the directory structure of the build tree: get rid of empty directories that serve no purpose, get rid of unnecessary files that cmake generates, structure the build output so that is intuitive to navigate to build artifacts, and move all "noise" generated by cmake away from the main build artifacts.
* Move all CMake macros into their own CMakeLists.txt file

There are some other great ideas about how to organize a cmake build system that supports multiple OS's and architectures in the following open-source project:
https://github.com/labapart/polymcu

**Comment by rianquinn** [comment]
The OS detect work is nice since the primary use case is Intel at the moment. If you want to provide your own CMake tool chain file for the cross-compiled portions (i.e. the sysroot and vmm), you can actually do that today, you just need to create a new one. Probably what we should do is label the current VMM tool chains with an intel_x64 so that it's clear what arch they are for. With respect to the rect of the code, you should be able to provide a toolchain during configuration of the hypervisor itself, and just pass this toolchain to the other projects (i.e. bfm, bfdrivers, etc). 

As for nasm, I don't think you will be able to get rid of that as it is used a lot for all of the intrinsics, and I'm a big fan of nasm's syntax over "gas" which is what you would have to use. Inline ASM is a no-go as well. Instead, you simply need to figure out what assembler you will need to use for aarch64, and then write the aarch64 versions of the intrinsics that already exist

**Comment by cpavlina** [comment]
I'm really skeptical of the notion that we should stick with nasm because you prefer the syntax. Why have different assemblers for every architecture (and introduce the additional build dependency) when the toolchain already includes one? Switching to the toolchain assembler should allow building asm files to be handled the same way as building c and cpp files and remove the need for handling this as a special case the way we're currently doing.

**Comment by rianquinn** [comment]
So, CMake doesn’t support the auto detection of of ASM like it does with C or C++. If you look at the project file, we have to play some tricks to get it to even support NASM. NASM itself only works on Intel, so you will need to state an assembler for aarch64 regardless. I don’t want to go an re-write all of the assembly for a different assebler when it won’t change the fact that you will have to write new assembly specific to aarch64. In other words, the none of the assembly that is in there today can be shared with ARM so touching the Intel part doesn’t do anything other than add additional work.

**Comment by JaredWright** [comment]
Adding a comment here to reflect some recent feedback in Gitter: changes to the build system will be modeled after the [bfbuild_sandbox](https://github.com/JaredWright/bfbuild_sandbox) repo.

**Comment by AlexLanzano** [comment]
Can't you just use the ".intel_syntax noprefix" directive so you wouldn't have to rewrite anything? Or is that not cross platform?

**Comment by rianquinn** [comment]
maybe, but you would still have to re-write a lot of the intrinsics because they are different for ARM.

**Comment by rianquinn** [comment]
@JaredWright Another thing that I forgot to add to this, is that the root CMakeLists.txt should have a "make install", which installs BFM into the user path, builds the driver, and premaritally installs the driver in place. Also, the libraries should also be installed in a place where they can be linked automatically as well. The idea is extensions should not have to point to the hypervisor directory, but instead should be able to build simply running `cmake ..`. 

Also, this should work for Windows and Linux.

**Comment by rianquinn** [comment]
@JaredWright The instructions here is basically what I am talking about. The "cmake" part of these instructions really should be simplified as I noticed a couple of issues:
- If dev mode is used on the hypervisor, but not on the extension, you get some strange issues
- The clang version is auto detected by the hypervisor, but it is not by an extension, we really should put the auto detection in a common file so that the extension can get it's clang version by simply including the same thing the hypervisor does
- I think the rest of this could be auto detected as well so long as you point the extension to the build folder you want to use for the hypervisor

https://github.com/Bareflank/hypervisor_example_cpuidcount/tree/dev

**Comment by JaredWright** [comment]
@rianquinn In the new build system, there is a concept of a build configuration file that contains settings like which compilers are used, which settings are turned on/off, etc. Maybe it would make sense to install that build-configuration file along with bareflank when someone runs 'make install', and then when someone goes to build examples or their own extensions, that configuration file can be absorbed by the extension's build system by default.

**Comment by rianquinn** [comment]
I like that.

**Comment by rianquinn** [comment]
Any ideas on how to do a make install that handles both the cross compiled prefix and the test prefix?

**Comment by JaredWright** [comment]
The way I see it, everything in the "test prefix" doesn't really need to be installed on the user's system at all. Correct me if I'm wrong, but everything that goes into the test prefix is just so that you and/or Travis/Appveyor can run 'make test', right?

**Comment by rianquinn** [comment]
Correct. 

Now, that being said, the user (as in us in this example), might want to create unit tests for their extensions, in which case, these files are needed. Now, you could also for the user to point to the test prefix, which is not that big of a deal so long as the rest of it is simple

**Comment by JaredWright** [comment]
Ah ok, that little bit of extra context makes sense. We want to make it extremely easy for developers to write unit tests for their extensions. I'll keep that in mind and think on it a little, but I agree, that is important

**Comment by rianquinn** [comment]
Yeah, I mean my example above works, but I feel like the cmake command is WAY too complicated. I'd love for:

Normal Build:
```
cmake .. <hypervisor>
cmake .. -DBLAH=/path/to/prefix <extension>
```

Unit Test Build
```
cmake .. -DENABLE_UNITTESTING=ON <hypervisor>
cmake .. -DENABLE_UNITTESTING=ON -DBLAH=/path/to/prefix -DBLAH=/path/to/test_prefix <extension>
```

This requires a little more than what you describe above, but it allows you to have more than one build tree. I also don't want a ton of logic in the extension CMakeLists.txt either. They should simply have to include a file from the prefix once it is defined.

**Comment by rianquinn** [comment]
@JaredWright I am working right now on trying to remove the need for the env.sh script (@cpavlina thats right !!!). One thing that I am noticing is that we should be able to get rid of the VMM_XX.txt files and simply use autodetection. 

For example, find the clang compile, and then use it's version to construct the cross compiler triple.

**Comment by JaredWright** [comment]
@rianquinn I would be careful spending too much time adding changes to the build system on dev, because the new system on my fork is so fundamentally different that anything you change there to toolchains, etc. won't make any sense soon. All of those VMM_*.txt things are already gone on my fork.

**Comment by rianquinn** [comment]
Awesome, yeah, I talked to @connojd about that exact problem. There are several things I want to fix, but this was the only one I decided to do because it was such a pain, and it was really messing up the examples are you could not do ExternalProject_Add with Bareflank itself.

**Comment by JaredWright** [comment]
If you want a preview of whats to come, check out the branch:https://github.com/JaredWright/hypervisor/tree/cmake_future. I think you're going to be very happy with how this is turning out!

**Comment by rianquinn** [comment]
It's looks great so far. When do you think you'll have a PR ready for review?

**Comment by JaredWright** [comment]
There have been numerous unforeseen issues that I ran into, so its a little difficult for me to say when the PR will be ready. I've got my local copy building all of the projects now, but not all the unit tests and build configurations yet. I think we need to discuss status tomorrow and coordinate a little.
