### ISSUE TITLE
[RFC] extended_apis: CPUID emulation

### ISSUE THREAD

**Issue by JWZepf** [Bareflank/hypervisor#506]
# Description
We would like to create a way for our users to emulate what returns when the CPUID instruction is called. This would allow the user to emulate different processor environments for testing purposes, or to "lie" to certain programs to get different behavior. It should be noted that we do not actually want to change the underlying CPUID structure, but rather we just want to change what is returned from a CPUID call.

Note: These changes will be implemented in the Extended APIs repository.

# Proposed APIs
* `exit_handler::emulate_cpuid(uint32_t leaf, uint32_t subleaf, string eax, string ebx, string ecx, string edx)`
* `exit_handler::reset_cpuid_leaf(uint32_t leaf, uint32_t subleaf)`
* `exit_handler::reset_cpuid_all()`
* `exit_handler::log_cpuid_access(bool enable)`
* `exit_handler::clear_cpuid_access_log()`
* `exit_handler::dump_cpuid_emulation_log()`

__emulate_cpuid:__
This function will set the corresponding return values in each register at the specified leaf and subleaf to the supplied values.

__reset_cpuid_leaf:__
This function will cause the return values at the specified leaf and subleaf to return to the default machine values.

__reset_cpuid_all:__
This function will cause all CPUID calls to return the default machine values.

__log_cpuid_access:__
If enabled, the log will keep track of how many times each CPUID leaf has been accessed, whether it is emulated or not.

__clear_cpuid_access_log:__
This will remove every entry from the cpuid access log.

__dump_cpuid_emulation_log:__
This will return the map containing every emulated leaf to the user

# Proposed VMCall APIs
## JSON Based Calls
* {"command": "emulate_cpuid", "leaf": int, "subleaf": int, "eax": str, "ebx": str, "ecx": str, "edx": str}
    - The str values for this vmcall will be binary representations of what the user wants the register to return upon a CPUID call. Strings will be 32 characters and can contain `0`, `1`, and `-`. A user can set bits as usual by using `0` and `1`, or the user can specify the bit as a "pass-through" bit by placing `-`. A pass-through bit will take on the value returned by the non-emulated CPUID call.
* {"command": "reset_cpuid_leaf", "leaf": int, "subleaf": int}
* {"command": "reset_cpuid_all"}
* {"command": "log_cpuid_access", "enabled":true/false}
* {"command": "clear_cpuid_access_log"}
* {"command": "cpuid_access_log"} -> log (std::map -> JSON)
* {"command": "dump_cpuid_emulations_log"} -> log (std::map -> JSON)
    - This JSON API outputs the contents of the emulations map to a JSON output

# VMCall Policy
In order to deny invalid vmcalls, there will be a `std::map<vmcall_index_type, vmcall_verifier*> policy` that will be referenced before handling the vmcall function. Each vmcall will have a `vmcall_index_type`, so each vmcall can use the policy map to access it's verification function.
```
if (policy(emulate_cpuid)->verify(leaf, subleaf, eax, ebx, ecx, edx) != vmcall_verifier::allow)
    policy(emulate_cpuid)->deny_vmcall();
```
```
if (policy(reset_cpuid_leaf)->verify(leaf, subleaf) != vmcall_verifier::allow)
    policy(reset_cpuid_leaf)->deny_vmcall();
```
```
if (policy(reset_cpuid_all)->verify() != vmcall_verifier::allow)
    policy(reset_cpuid_all)->deny_vmcall();
```
```
if (policy(log_cpuid_access)->verify(enabled) != vmcall_verifier::allow)
    policy(log_cpuid_access)->deny_vmcall();
```
```
if (policy(clear_cpuid_access_log)->verify() != vmcall_verifier::allow)
    policy(clear_cpuid_access_log)->deny_vmcall();
```
```
if (policy(cpuid_access_log)->verify() != vmcall_verifier::allow)
    policy(cpuid_access_log)->deny_vmcall();
```
```
if (policy(dump_cpuid_emulations_log)->verify() != vmcall_verifier::allow)
    policy(dump_cpuid_emulations_log)->deny_vmcall();
```

# Default
By default, no CPUID leafs will be emulated and access logging will be disabled.

**Comment by rianquinn** [comment]
The "effects" of emulating CPUID is up to the person extending Bareflank. In other words, this emulation API only provides a means to change the values of CPUID, it doesn't ensure emulation from that point on is correct. 

Everything so far looks good, but I think a couple of things are missing / wrong:
- I would like to see a JSON interface in addition to a register based VMCall interface
- These should be "exit_handler::" and not "vmcs::" as this would be a change to the exit handler. 
- I'd like to see a dump "config" function
- There probably should be a log, which would need an enabled log, and dump log set of functions. Please see the io instruction emulation for an example.

**Comment by rianquinn** [comment]
Oh.... and don't forget about the VMCall policy part

**Comment by JaredWright** [comment]
@rianquinn Did you mean to assign this issue to JWZepf?

**Comment by rianquinn** [comment]
@JaredWright Actually I meant to assign this to Connor. My bad.

**Comment by rianquinn** [comment]
Note that this is going to make doing the register based CPUID difficult, so I think for now, the VMCall interface should just be JSON based. Realistically, we are only really going to need CPUID emulation for research on the VMCall side, so JSON is fine. The internal exit_handler APIs that you have defined above will be used programmatically by an extension which can take a string with no issues.

**Comment by JWZepf** [comment]
RFC has been updated with the changes discussed above.
* JSON API interface
* Removed register based APIs to accommodate bit level configuration
* Created dump API
* Created log functions
* Created VMCall Policy section

**Comment by rianquinn** [comment]
Couple of notes:
- `exit_handler::emulate_cpuid(uint32_t leaf, uint32_t subleaf, uint32_t eax, uint32_t ebx, uint32_t ecx, uint32_t edx)` still uses uint32_t, so I'm not sure how you would express "0, 1, or -". 
- I don't see a dump API. I see the log enable and clear, but I don't see a dump log or dump config API. 
- The JSON command is labeled read, but all of the other functions for IO and MSRs are labeled dump. Would be nice if they had the same pattern. 
- Since the emulate_cpuid JSON command takes JSON as an input, it would be nice if there was a JSON based API for setting up all of these commands. This way, you could compile in a config, and set everything with a simple JSON file. You would then use this same function from the JSON VMCall interface (kill two birds with one stone).
