### ISSUE TITLE
bareflank_astyle_format.sh and bareflank_clang_tidy.sh try to process deleted files

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#509]
Because these scripts use `git ls-files` to determine which files to process, they attempt to process files that have been deleted from the working tree but not from the index. `git ls-files` doesn't appear to have an option to exclude deleted files, but it does have one to emit _only_ deleted files, so the following somewhat long-winded replacement should work:

    git ls-files | sort | comm -23 - <( git ls-files -d | sort )

If we're not going to fix this we should at least document it; it took me way too long to figure out where they were getting the names of files I had removed...

**Comment by rianquinn** [comment]
I'd love to see a PR here. Although, it would be great if there was a better solution for getting the files.

**Comment by cpavlina** [comment]
> I'd love to see a PR here.

I was waiting first to see if anyone had input on...

> Although, it would be great if there was a better solution for getting the files.

:stuck_out_tongue:

**Comment by rianquinn** [comment]
This has been fixed
