### ISSUE TITLE
[RFC] Architecture naming and organization

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#533]
We really should make a formal decision regarding how we are going to refer to and organize architectures. Currently, for instance, we are using `x86`, `x64`, and `x86_64` variously to refer to the same thing, and have plans to bring AMD into the mix too. `aarch64` and `arm64` have the same problem.

For reference, #529 suggests organizing the architecture-dependent source files like this:

- foo/
    - arch/
        - x86/
            - intel/
            - amd/
        - aarch64/
    - (common files...)

There is a slight issue I see with this: having an inconsistent organizational depth for architectures complicates referring to them in code and build scripts. In the current iteration of the build system rework, `BUILD_TARGET_ARCH` indicates the target and is either `x86_64` or `aarch64`. How would this expand to include Intel and AMD? I'd rather something flat like this, but I'm not familiar enough with the issues relating to Intel and AMD to know if this will cause trouble:

- foo/
    - arch/
        - intel_x64/
        - amd_x64/
        - aarch64/
    - (common files...)

Items common to `intel_x64` and `amd_x64` could perhaps go in `x64` or `common_x64` or similar. `BUILD_TARGET_ARCH` would be `intel_x64`, `amd_x64`, or `aarch64`. These are nice, flat names that are valid to use in cmake scripts as well as in file names, namespaces, etc. I notice that in `intrinsics` there appears to be a couple uses of `common_x64` and `intel_x64` already, so probably an easy direction to continue in.

Let's decide for good on what we're going to call these architectures, and I welcome comments regarding the code organization.

**Comment by rianquinn** [comment]
I like the idea of the flat naming scheme. I would however like to drop the “common” part and just use x64 for common code as it keeps the namespaces in the code short. Other than that I like your proposal as it matches the code and build system

**Comment by rianquinn** [comment]
@connojd @brendank310 @RicoAntonioFelix @josephsharkey Any comments?

**Comment by RicoAntonioFelix** [comment]
I agree with @rianquinn's comment, "common" can be dropped as the meaning of that can be inferred from the surrounding context, so go with `x64`.

:+1: on the proposal.

**Comment by rianquinn** [comment]
If nobody has any issues, I am going to move the VMCS, VMXON and Exit handler to a "hve" folder which stands for "hardware virtualization extensions", and then use the arch layout we have here. These will be part of one module which will simplify things, and prevent confusion with respect to intel vs arm.

**Comment by rianquinn** [comment]
Complete: https://github.com/Bareflank/hypervisor/pull/575

Will next to port the EAPIs to use this scheme as well at some point
