### ISSUE TITLE
[BUG] build system - unnecessary re-compilation

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#534]
The build system re-compiles every file every time you build.

### Root Cause
This bug happens because some of the external dependency projects (hypervisor/scrips/cmake/depends/*.cmake) install their build artifacts into the build tree's install directory every time the project is built. The reason this happens is because the built-in cmake function ExternalProject_Add_Step is not correctly tracking dependencies of projects built using ExternalProject_Add.

### Steps to reproduce

1. Clone and build Bareflank in any valid configuration
2. Build bareflank again. ALL components will be re-compiled

### Temporary work-around

1. Clone and build Bareflank in any valid configuration
2. Run cmake again (i.e. ```cmake ..```)
3. Build again. Only source files that have been modified will be recompiled

**Comment by JaredWright** [comment]
I may have found a fix for this... there is a built-in cmake command *copy_if_different* that you can use as a part of ExternalProject_Add_Step. You have to specify each file to be copied individually (doesn't work recursively), but it appears to fix the issue.

**Comment by rianquinn** [comment]
Nice, git it a try and I can test once it's ready.
