### ISSUE TITLE
[BUG] build system - windows support

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#535]
There a numerous issues preventing the new build system from compiling on Windows/Cygwin:

* bfdriver can't compile on windows. The .sln and .vcxproj files checked in to source control have invalid data (the software license) that prevents visual studio from using them
* A new toolchain for using msbuild and/or cl needs to be added for building bfm and bfdriver
* Compiler flags need to be added for msbuild/cl
* Appveyor needs to be updated to use the new build system. Add appveyor specific project configurations to scripts/cmake/config.

**Comment by Randshot** [comment]
I have tried compiling and running the **dev** branch of [rianquinn's](https://github.com/rianquinn/hypervisor/tree/dev) fork.
The cmake configuration and the actual compilation work fine, but when I try to compile the driver with `make driver_build`, it throws the following errors:
```
hypervisor\bfsdk\include\bfdebug.h(990): fatal error C1083: Cannot open include file: 'wdm.h': No such file or directory
hypervisor\bfdriver\src\platform\windows\driver.h(22): fatal error C1083: Cannot open include file: 'ntddk.h': No such file or directory
platform.c(20): fatal error C1083: Cannot open include file: 'ntddk.h': No such file or directory
```

I have installed VS 2015, VS 2017 and the WDK.

**Comment by rianquinn** [comment]
My changes are in. I still have some testing to do, but I think most of it is there. I updated the dev branch of hypervisor_example_cpuidcount so that you can see how it works. To use the config and extension.cmake, add -DCONFIG=<path> and -DEXTENSION=<path>

**Comment by Randshot** [comment]
@rianquinn Nice. I will do some testing soon.

**Comment by rianquinn** [comment]
Fixed: https://github.com/Bareflank/hypervisor/pull/575
