### ISSUE TITLE
[BUG] - build system - duplicate vmm main exectuables

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#537]
If you build the vmm with both BUILD_VMM_SHARED=ON and BUILD_VMM_STATIC=ON, the output executable is named "vmm" in both cases. This executable gets installed into the vmm sysroot to /bin, therfore overwriting one with the other.

### Proposed fix
* Change the output names for the VMM executable to vmm_shared and vmm_static.
* Take the compiler defines out of BFM that choose the default vmm's name
* Add a cmake variable that will hold the VMM's name, and let the build system choose a sensible default VMM based on the current configuration (shared vs. static, eapis, etc)
* Pass the VMM's name to BFM when you run ```make quick```, etc. as a command line argument

**Comment by cpavlina** [comment]
All of this looks perfectly reasonable to me. :+1:

**Comment by JaredWright** [comment]
After looking into this bug, I believe that *entirely* removing the compiler defines from BFM that determine the default VMM name and path falls outside the scope of a bug fix. Removing those defines completely would be better addressed in a seperate RFC that will address not only removing those defines, but also other related clean up before we can allow users to install BFM onto their host system.

With that said, I at *least* moved those compiler defines into their own cmake configuration variables (see new "BFM Configs" section of scripts/cmake/config/default.cmake). A sensible path and VMM name is choosen by the build system based on your shared/static/eapis configurations.
