### ISSUE TITLE
[RFC] Updated VMM Extension Integration

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#545]
## Overview

This RFC proposes a new mechanism for integrating the base Bareflank hypervisor repo with extensions (including the extended apis). I beleive that an ideal implementation would have the following characteristics:

* **Absolute minimal work required for the extension writer** - Developers should be able to start writing an extension by doing something as simple as including one file, or writing one line of code in their extension project.
* **Homogeneity** - The process for integrating the extended APIs and hyperkernel should be exactly the same as for custom developer extensions.
* **Out-of-tree** - Make it easy and desirable for Bareflank extensions to reside outside of the main hypervisor source tree. For example, it should not be necessary or encouraged to clone the extended APIs to hypervisor/eapis
* **Encourage inter-extension integration** - Extensions should be encouraged to integrate together, and depend on other extensions. For example, many people will probably want to use the extended APIs as a dependency of their own extension

Some other points to think about:
* Should we *require* extension writers to use cmake as the extension's build system, even if its just a minimal CMakeLists.txt file?
* Should the extension be built using the extension's build system, or should the we let the base Bareflank build system carry out the heavy lifting? Is it possible to allow for both options?

## Proposed API Changes

Here's an initial stab at how extension integration might work. If you'd rather read these changes in the form of source code, I have a mostly-working branch with these features implemented, and an example extension. To get my example branch working:

```
git clone -b extensions_overhaul https://github.com/JaredWright/hypervisor
mkdir hypervisor/build && cd hypervisor/build
cmake .. -DBFCONFIG=extensions_example.cmake
make -j<# cores>
```

### Extension Registration

Let extension writers declare their extensions to the base hypervisor build system using a build system configuration file (already part of the new build system), and a new *vmm_extension()* macro. The vmm_extension macro will support any arguments that cmake's built-in ExternalProject_Add macro supports. The hypervisor build system will do the heavy lifting, and "reach out" to the extension to clone it, build it, and do whatever else you declare in the configuration file. The hypervisor's build system will also copy the entire build configuration (cmake cache variables, etc) into the extension's scope. That way, the extension can access build configurations the exact same way the base hypervisor repo does.

An example build configuration might look like this:
```
# extensions_example.cmake

# First, you can override any default build configurations that you'd like:
set(BUILD_VMM_STATIC ON)
set(BUILD_VMM_SHARED OFF)
# etc...

# Next, you can add extensions to the build system using the vmm_extension
# macro, passing any arguments supported by cmake's built-in
# ExternalProject_Add() function.
vmm_extension(
    extended_apis
    GIT_REPOSITORY https://github.com/jaredwright/extended_apis.git
    GIT_TAG dev
)

# Or, you could add extensions from a local directory like this:
# vmm_extension(
#     extended_apis
#     SOURCE_DIR /home/wrightj/extended_apis
# )

# Extensions can depend on other extensions:
vmm_extension(
    jareds_example_vmm
    GIT_REPOSITORY https://github.com/jaredwright/example_extension.git
    DEPENDS extended_apis
)

# You can tell the build system which vmm you want BFM to load during
# 'make quick' like this:
set(BFM_DEFAULT_VMM jareds_example_vmm)
```

### Extension's CMakeLists.txt
The extension author will be required to provide a CMakeLists.txt file at the top-level of the extension's source tree, with a minimal amount of configuration (one include() statement). The base hypervisor's build system will provide some convenience macros for interacting with the build system. For example:

```
cmake_minimum_required(VERSION 3.6)
project(jareds_example_extension C CXX)

# Bareflank extensions will integrate with the base hypervisor build system
# using a single include:
include(${BF_VMM_EXTENSION})

# Make an executable or library out of the given source files, linked with all bfvmm and
# vmm support libraries:
add_vmm_executable(jareds_example_vmm vcpu_factory_rdtsc.cpp)
# add_vmm_library(jareds_vmm_lib some_support_functions.cpp)

# Install the executable to the base build system's vmm sysroot:
install_vmm_executable(jareds_example_vmm)
```

### Build tree structure

Extensions will be integrated into the build tree of the base hypervisor project exactly like external dependencies, except they will be built under build/extensions instead of build/depends. I also suggest grouping the built-in bareflank-vmm components into the build directory at build/hypervisor to make it extremely obvious which components belong where. The full build tree would then look like this:

```
hypervisor
|  - build
    |  -  hypervisor
         |  - bfdriver
         |  - bfelf_loader
         |  - bfm
         |  - bfsdk
         |  - bfsupport
         |  - bfunwind
         |  - bfvmm
    |  -  depends
         |  - astyle
         |  - binutils
         |  - gsl
         |  - json
         |  - libcxx
         |  - libcxxabi
         |  - llvm
         |  - newlib
    |  -  extensions
         |  - extended_apis
         |  - jareds_example_extension
    |  -  install
         |  - vmm-x86_64-release
         |  - linux-x86_64-release
         |  - linux-x86_64-test
```

**Comment by connojd** [comment]
The extension developer

**Comment by cpavlina** [comment]
# First, you can override any default build configurations that you'd like:
    set(BUILD_VMM_STATIC ON)
    set(BUILD_VMM_SHARED OFF)
    # etc...

I wonder if we should also have the ability for extensions to add conditions to be validated at the build config validation stage.

**Comment by JaredWright** [comment]
+1 x1000. That is a fantastic idea!

**Comment by connojd** [comment]
This looks great to me. One thing I would be sure to add is some documentation/examples of how to create the config files.

I think it is ok to require a single CMakeLists, especially since there really aren't very many lines that would have to be written. I also like that the extension developer could use a different build system if they wanted/needed to just by passing the appropriate step commands to vmm_extension

**Comment by rianquinn** [comment]
+1. I think you nailed it. 

Out of curiosity, what does the source tree look like if you use the local source for an extension? Also, will all of the make targets work with the extensions so that we can do our testing on the extensions as well? How will Travis CI work for the extensions?

**Comment by JaredWright** [comment]
@connojd I completely agree with adding some documentation. I can probably sneak in some README info along with my PR when its ready.

@rianquinn The source tree can look like whatever you want if you're using local source for an extension. Even though the source can be scatterred anywhere you want, the build tree will all be located in the same place.

For make targets and unit testing, I will probably need to add a way for extensions to indicate wheather or not they support unit tests, and then might want to provide a seperate vmm_extension_test() macro that will build the extension's tests, add them to the 'make test' target, etc. That way, the build configuration file is what determines whether or not you build tests for any given extension. I'll have to play around with that a little...

As for CI, I envision extensions providing one build configuration file per CI build. Those config files can be located anywhere really, as long as CI can specify a path to them.

**Comment by JaredWright** [comment]
Another thing that I'd like to suggest making a conscious effort on with extensions is to encourage a "convention over configuration" mindset for extension devlopers. In other words, our build system should provide defaults that make up the Bareflank suggested convension. For example, we could have a convention like this:

*If you put a file named build_rules.cmake at the top of your extension's source tree, the build system will automatically use it to validate your extension's build rules*

Then, allow developers who want to "break" that convension to do so via configuration:

```
set(VMM_EX_BUILD_RULES_FILE /custom/path/to/extension/build_rules.cmake
```

The important part is: developers who follow our convensions should be free from having to know any details of our build system.

**Comment by rianquinn** [comment]
+1

**Comment by JaredWright** [comment]
Status update: I technically have a PR ready for this, but I think I'm going to spend the rest of today creating some build system documentation before I submit the PR. If anyone wants to play around or start reviewing what I have so far, here's a couple places to look:

1. Here's some quick instructions (see the README) on how to get started building the base hypervisor + the extended apis + a custom extension: https://github.com/JaredWright/example_extension

2. Here's the branch where I've been working on with changes to the base hypervisor build system: https://github.com/JaredWright/hypervisor/tree/extensions_overhaul

I'll have a PR ready with documentation shortly!

**Comment by JaredWright** [comment]
Documentation to be inluded along with this RFC can be found on PR #560 at /hypervisor/scripts/docs

**Comment by Randshot** [comment]
I have just tried compiling the extended_apis (dev) extension, but when I call `make` it never gets compiled.
After some debugging, I noticed that `add_vmm_extensions()` never gets called.
So I tried adding it at the end of the (top-level) `CMakeLists.txt`, but that lead to the following error being thrown:
```
CMake Error at /usr/share/cmake-3.6.2/Modules/ExternalProject.cmake:2140 (get_property):
  get_property could not find TARGET bfvmm.  Perhaps it has not yet been
  created.
Call Stack (most recent call first):
  /usr/share/cmake-3.6.2/Modules/ExternalProject.cmake:2476 (_ep_add_configure_command)
  scripts/cmake/macros.cmake:1155 (ExternalProject_Add)
  CMakeLists.txt:183 (add_vmm_extensions)


-- Registered VMM Extensions: extended_apis
CMake Error at scripts/cmake/macros.cmake:1171 (endif):
  endif An ENDIF command was found outside of a proper IF ENDIF structure.
  Or its arguments did not match the opening IF command.
Call Stack (most recent call first):
  CMakeLists.txt:183 (add_vmm_extensions)
```

**Comment by rianquinn** [comment]
Huh. 

I am currently working on the VMM extensions stuff in a giant PR. Hopefully I have something today if you want to try that.

**Comment by Randshot** [comment]
@rianquinn I would certainly like to test it, since I wanted to update my own VMM extension to work with the dev branch.

**Comment by rianquinn** [comment]
Awesome, I will post here once I have it pushed up and working
