### ISSUE TITLE
[BUILD]: Auto running tidy and format should not be on by default

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#552]
Running make format and make tidy on "make all" needs to be removed by default. I think there are a couple of options we should consider:

- Providing a "make pr" target that can be used for doing a complete build, format and static check as well as anything else we want to add to it. 
- Providing a config option that turns a "PR" build on so that these are always run on "make all"
- Going back to our original model where you simply have to run these manually. 

Thoughts?
- Rian

**Comment by JaredWright** [comment]
Tidy and format only run under 'make all' automatically when developer mode is turned on, which is off by default.

**Comment by rianquinn** [comment]
My bad, I meant to say that it should be turned off by default when developer mode is turned on. It's really annoying 😄

**Comment by JaredWright** [comment]
What would be the point of developer mode then? Can't you just turn developer mode off while you devlop, then re-enable it when you're ready for your PR build?

**Comment by rianquinn** [comment]
It's original intent was to enable it so that you "could" run make format and make tidy as needed without having to change your cmake settings, but was not mandated on every build. I run make all a "lot", and then when I get a set of changes done, I run make tidy and make format before moving onto the next part of my PR

**Comment by rianquinn** [comment]
FYI, at some point I would like to see a make codecov as well so that we can get a local report from codecov on coverage. We are not there yet, but that would be really helpful so that you don't have to constantly push to your remote branch to see your coverage

**Comment by JaredWright** [comment]
I think that the behaviour you desire is already included in the build system. If you want to have astyle/tidy enabled but not run automatically:

``` 
cmake .. -DENABLE_ASTYLE=ON -DENABLE_TIDY=ON
make
make tidy
make format
```

If you want to use developer mode, then turn it off later:
```
cmake .. -DENABLE_DEVELOPER_MODE=ON
make # tidy and format run automatically
cmake .. -DENABLE_DEVELOPER_MODE=OFF
make # Now you have the same build settings, but tidy and format don't run automatically
```

Also, I agree that code-coverage would be nice locally.

**Comment by rianquinn** [comment]
I can compromise on that
