### ISSUE TITLE
[BUILD]: Newlib disables build based on existence

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#564]
The following is used to gate the compilation of newlib:

```
if(NOT EXISTS "${BUILD_SYSROOT_VMM}/lib/libc.a" OR NOT EXISTS "${BUILD_SYSROOT_VMM}/lib/libc.so")
```

This needs to be removed as it will prevent the compilation of newlib if the upstream repo changes which means that people with an already established build will not get updates as needed.

**Comment by JaredWright** [comment]
I would argue that this is the same as bug #553. Dependency caching will fix this as well (almost have an RFC and PR ready for that)

**Comment by rianquinn** [comment]
I agree, but I don't want to forget about fixing this (and anything else like this) when caching is done

**Comment by rianquinn** [comment]
Fixed: https://github.com/Bareflank/hypervisor/pull/575
