### ISSUE TITLE
Load Error

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#565]
I try to use the hypervisor to hook some things in kernel, however, when I just modify the hook example, something goes wrong, when I run  `make load`
the error message is as follow 
`bfm: ioctl failed: `IOCTL_LOAD_VMM` `
`Makefile:176: recipe for target 'load' failed`
`make[1]: *** [load] Error 1`
`Makefile:5: recipe for target 'load' failed`
`make: *** [load] Error 2`

The error information I got from `dmesg` is that:
`
[34196.504579] [BAREFLANK DEBUG]: common_add_module [19]:  
`
`
[34196.504580] [BAREFLANK DEBUG]:     addr = ffffc90005004000
`
`
[34196.504581] [BAREFLANK DEBUG]:     size = 000000000000b018
`
`
[34196.504582] [BAREFLANK DEBUG]: IOCTL_ADD_MODULE: succeeded
`
`
[34196.526040] [BAREFLANK ERROR]: private_get_sym_global [1047] no such symbol: _ZN28exit_handler_intel_x64_eapis11init_policyEv
`
`
[34196.527260] [BAREFLANK ERROR]: IOCTL_LOAD_VMM: common_load_vmm failed: 8000000000a00000 - BFELF_ERROR_NO_SUCH_SYMBOL
`
module[19] in file modules is that 
`"%BUILD_ABS%/makefiles/src_extended_apis_example_hook/vcpu_factory/bin/cross/libvcpu_factory.so"`

I use `readelf -s`  to get the symbols information about `libvcpu_factoary.so` and got the following return value:
`202: 0000000000000000     0 NOTYPE  GLOBAL DEFAULT  UND _ZN28exit_handler_intel_x`
All symbols with prefix `_ZN28` is same with the above one. there is no symbols as the debug information list.

could you please give some instructions on the reason why I got wrong? 
Besides, If the information get from `dmesg` is the same with that through `serial debug` 
Thank you so much!

**Comment by rianquinn** [comment]
It looks like your missing your policy module. Can you show your modules file?

**Comment by kunlilin2991** [comment]
Yes, I didn't add the vmcall_policy module into the the modules file.
But, I haven't used vmcall to registe any trap on EPT entry? and why should I add this .so into the hypervisor? now I just want to verify if the EPT can work or not, so when VM exit because of EPT violation, I just resume to VM. could you please explain why I need to load the vmcall_policy module. 
Thanks so much!

**Comment by rianquinn** [comment]
It defines the symbol that your missing. It might not be a bad idea to compile out that symbol if the vmcall policy is not used, which is the default. Feel free to adda feature request for this if you like. For now, you can either link in the library, or add the function to an existing library.

**Comment by kunlilin2991** [comment]
Thank you so much! Could you please give me some information on what's these symbols used for?

**Comment by rianquinn** [comment]
Some users need to disable specific vmcalls, so these systems are designed to provide a means to protect / filter specific vmcalls. We have plans in the near future (next 3 months), to create a 4th repo specific for hypercalls which would move all of the hypercalls from the extended APIs into it's own repo, so in the future this will not be needed.

**Comment by kunlilin2991** [comment]
Thanks so much!
