### ISSUE TITLE
Invalid GPA

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#568]
I use this hypervisor to hook some kernel data structure. but, something goes wrong:
I use `kvm` and `qemu` as the development environment. 
For QEMU, I set 4G for guest physical memory. 
For hypervisor, I also set `MAX_PHYSICAL_ADDRESS` = 4G and use identify map for Guest Physical Memory with 4kb per page frame. 
when I make start, the hypervisor would encounter an `EPT Violation` forever. 
I get information as following \:
use `get()` in `intel_x64::vmcs::exit_qualification::ept_violation`, the output is `0x83`
GPA access type is `0x83` too
`page_fault_if_exit` is `0x83`
`EPT Violation` at `vir` = 0
`EPT violation`  at guest physical address at `0x13b09200`, which is larger than 4G
Could you please offer me some help on how to solve it. 
Actually, when I set `MAX_PHYSICAL_ADDRESS` = 64G and QEMU = 12G(which is the max physical address on my computer) , the problem disappears. 
Thanks so much!

**Comment by rianquinn** [comment]
Since you are on a 64bit system, you have to provide more than your max physical memory. All that is doing is defining how much RAM you are providing the system. That doesn't change the size of the address space, which is needed for a lot of other things other than RAM.

**Comment by kunlilin2991** [comment]
I used to set `MAX_PHYSICAL_ADDRESS`=16G with `QEMU` = 4G, however when I `make start`, the hypervisor crashed due to bad allocation error

**Comment by rianquinn** [comment]
You probably didn't give the hypervisor enough memory. You can play around with total memory in constants.h
