### ISSUE TITLE
handle_vmcall_data error?

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#569]
I try to use json to import some addresses to protect, But somethings goes wrong with `make_unique_map_x64`
the code is listed as following 
```C++
        json dearray = {json::array({"systable",0x1234567})};
        json *imap = & dearray;
        regs.r00 = VMCALL_DATA;
        regs.r01 = VMCALL_MAGIC_NUMBER;
       /*
         * r2 = uuid1 (bits 0 -> 63)
         * r3 = uuid2 (bits 64 -> 127)
        */
        regs.r04 = VMCALL_DATA_STRING_JSON;
        regs.r05 = reinterpret_cast<uintptr_t>(imap);
        regs.r06 = imap->size();
```
However I got error with json parse() as following
```C++
----------------------------------------
- Standard Exception Caught            -
----------------------------------------
parse error - unexpected ''

```
I modify `bfvmm/src/exit_handler/src/exit_handler_intel_x64.cpp` to find out where gone wrong .
the following code seems to return a wrong Rreference. 
```C++
    auto &&imap = bfn::make_unique_map_x64<char>(regs.r05, vmcs::guest_cr3::get(), regs.r06, vmcs::guest_ia32_pat::get());
```
I received `1` for imap. 
Could you please give me any help on how to fix my mistake? Thanks!
Besides, I use QEMU to test all the code above.

**Comment by Randshot** [comment]
I think you need to define an output buffer:
```
     /*
      * Data
      *
      * Provides a means to send and receive binary data (page sharing). With
      * this vmcall, an in and out buffer are provided. The VMM will map in
      * both buffers, perform whatever operation it should, and then unmap the
      * buffers. The type field must be provided for the input buffer, and it
      * defines what type of data is being provided. The VMM will return data
      * in the output buffer, and set the output type based on whatever
      * operation it performed. The size is in bytes, but the VMM will map
      * complete pages. If the size of the buffer is not a multiple of a page,
      * the VMM will have access to data outside the bounds of the buffer
      * (which may be fine depending on the use case). The uuid field is provided
      * as a means to identify the data being sent / received. Specifically,
      * this field can be paired with the registers vmcall to ensure that
      * consecutive vmcalls have the proper data. For example, if an operation
      * takes more than one vmcall to perform, and software on the CPU is
      * threaded, the uuid field provides the VMM with a means to handle when
      * more than one vmcall becomes interlaced. Note that the uuid field is
      * optional. out_size contains the max size of the output buffer that
      * is provided, but the VMM must set out_size to the actual number of
      * bytes that it is sending back, which likely will not be the same as
      * the output buffer going in is likely the "max" sized buffer, while the
      * actual contents being written back are likely smaller.
      *
      * In:
      * r0 = VMCALL_DATA
      * r1 = VMCALL_MAGIC_NUMBER
      * r2 = uuid1 (bits 0 -> 63)
      * r3 = uuid2 (bits 64 -> 127)
      * r4 = in_type (vmcall_data_type)
      * r5 = in_addr (addr of virtually contiguous buffer)
      * r6 = in_size (size of virtually contiguous buffer)
      * r7 = out_type (vmcall_data_type)
      * r8 = out_addr (addr of virtually contiguous buffer)
      * r9 = out_size (size of virtually contiguous buffer)
      *
      * Out:
      * r1 = 0 == success, error code otherwise
```
(from [vmcall_interface.h](http://bareflank.github.io/hypervisor/html/vmcall__interface_8h_source.html))

**Comment by kunlilin2991** [comment]
According to instruction in `./include/vmcall_interface.h', I need to pass the address of a buffer
```C
  /*
     *  With this vmcall, an in and out buffer are provided. The VMM will map in
     * both buffers, perform whatever operation it should, and then unmap the
     * buffers. The type field must be provided for the input buffer, and it
     * defines what type of data is being provided.
  */
```
and 
```C
/*
In:
     * r0 = VMCALL_DATA
     * r1 = VMCALL_MAGIC_NUMBER
     * r2 = uuid1 (bits 0 -> 63)
     * r3 = uuid2 (bits 64 -> 127)
     * r4 = in_type (vmcall_data_type)
     * r5 = in_addr (addr of virtually contiguous buffer)
     * r6 = in_size (size of virtually contiguous buffer)
*/
```
Is it wrong if I just pass the address of an json structure.
Thanks!

**Comment by Randshot** [comment]
It's not necessarily wrong, but since you defined the data type (in `r4`) as `VMCALL_DATA_STRING_JSON`, you will also have to provide a string/char pointer.
The example i posted previously shows it. The example is taken from the command line parser for Bareflank.

**Comment by rianquinn** [comment]
@Randshot is correct, you should be sending the address of the string (which we call "buffer").

**Comment by kunlilin2991** [comment]
Thanks so much!
However, when I track the process of handle_vmcall_data, I found something confusing.
Firstly, `vmcall` is handled in `bfvmm/src/exit_handler/exit_handler_intel_x64.cpp`, which located in Class `exit_handler_intel_x64`
But, when the process is going to handle json file in function `handle_vmcall_data_string_json`, 
the function jump into Class `exit_handler_intel_x64_eapis` which is located in `extended_apis/src/exit_handler/src/exit_handler_intel_x64_eapis.cpp`. 
I just wonder why I need to handle that `vmcall`  in `extended apis` but not in Class `exit_handler_intel_x64` in `bfvmm` ?

**Comment by connojd** [comment]
@kunlilin2991 the extended apis are meant to serve as an example of how to extend bfvmm; it may make more sense, depending on the application, to handle it in bfvmm and not the extended apis. That being said, the current inheritance design between bfvmm and extended apis (and elsewhere in the code) will soon be rewritten to use a delegate pattern instead, with the aim of providing more flexibility than what is there now

**Comment by kunlilin2991** [comment]
@connojd I used to think that extended apis are used to support hardware-relevant or architecture-
relevant feature, such as ept for intel. VMM without extended apis can also be executed perfectly. 
If it is correct I think about, now exit handler seems to be not properly, because class `exit_handler_intel_x64` should be not be put in bfvmm but extended apis. together with class `*eapi`

**Comment by Randshot** [comment]
@kunlilin2991 Why shouldn't you be able to use the exit handler without EPT (etc.) support?
The extended_apis module extends, like the name suggests, the already existing API (see below).
```
class exit_handler_intel_x64_eapis : public exit_handler_intel_x64
{}
```

**Comment by connojd** [comment]
@kunlilin2991 the bfvmm serves as the bare-minimum code required to turn on VT-x. Things like cpuid exit in the guest right after you execute vmxon, so there has to be code in the hypervisor to handle that. On the other hand, things like EPT are not required to turn on VT-x and have been placed in the eapis.

**Comment by kunlilin2991** [comment]
@Randshot the definition and code of `class exit_handler_intel_x64_eaps` are located in extended apis. but not the bfvmm directory

**Comment by Randshot** [comment]
@kunlilin2991 I know. It's a subclass of the exit handler in bfvmm.

**Comment by rianquinn** [comment]
@kunlilin2991 It's really up to you as to how you use Bareflank. You can directly modify the bfvmm, you can extend the bfvmm (similar to what the EAPIs do), or you can extend the EAPIs. Also, @connojd is right, the current inheritance model will be changed in the very near future to use delegates instead in an attempt to make this easier, and a bit more lightweight. 

Also, a lot of the vmcall logic in the EAPIs will be moved to a 4th repo specific to a "PV interface". Our goal is to support a custom Bareflank specific interface and the Xen PV interface in the near future.

**Comment by rianquinn** [comment]
I'm going to close this for now. Feel free to reopen if you think there is something else that needs to be addressed.
