### ISSUE TITLE
[BUG] build system: missing dependency for bfelf_loader headers

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#570]
There is a missing dependency relationship between the bfelf_loader headers in the source tree and their copies in the build tree, so if you modify the headers and try to rebuild, the modified files are not copied in and the build is done with stale files.

**Comment by rianquinn** [comment]
My current mods fix this:
https://github.com/Bareflank/hypervisor/pull/571

I will close this ticket once we merge this code (could days away)

**Comment by rianquinn** [comment]
Fixed: https://github.com/Bareflank/hypervisor/pull/575
