### ISSUE TITLE
[RFC] Aarch64 Intrinsics: Register Access

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#572]
This RFC proposes a method for implementing vmm intrinsics that relate to reading and writing registers on the aarch64 architecture. 

## Background

Recently, ARM released their ARM-V8 Architecture Reference Manual (the ARM-ARM) in a
[machine parsable format](https://developer.arm.com/products/architecture/a-profile/exploration-tools).
This specification is made up of two parts: a set of .xml files, and a custom description language invented by ARM (the ARM Architecture Specification Language, or ASL for short). The .xml files together with ASL comprise a complete specification of the entire Aarch64 architecture, plus a specification for the A64, A32, and T32 instruction set architectures. Alastair Reid, the primary researcher at ARM Ltd. responsible for creating these documents, released a series of blog posts and open source code that demonstrate what is possible to accomplish with this spec. Some examples have included generating a complete aarch64 emulator from ASL, transpiling ASL into executable C code, and transpiling ASL into Verliog. There are several entries in Alastair's blog that introduce these concepts:

* https://alastairreid.github.io/specification_languages/
* https://alastairreid.github.io/alastairreid.github.io/ARM-v8a-xml-release/
* https://alastairreid.github.io/dissecting-ARM-MRA/
* https://alastairreid.github.io/asl-lexical-syntax/
* https://alastairreid.github.io/arm-v8_3/
* https://github.com/alastairreid/mra_tools

## Design Goals

This RFC proposes one possible design for generating aarch64 vmm intrinsics from the above mentioned machine parsable specification. The scope of this RFC will be limited to intrinsics that perform writes and reads to/from machine registers, and will not consider intrinsics that perform system instructions such as cache/TLB maintenance, etc. (another RFC will be created for that separately). There are many ways in which machine register intrinsics could be derived from the ARM specification, but this RFC proposes one such implementation that will possess the following characteristics:

* **Callable from C/C++** - All generated intrinsics needs to be accessible from the C/C++ environment that make up the current Bareflank hypervisor
* **Testable** - All code that participates in transpiling ARM specifications into a callable intrinsic function must be covered by unit tests
* **Integrates with the current VMM toolchain** - The generated intrinsics need to be compilable and linkable with Bareflank's VMM toolchain
* **Performance** - Our implementation will strongly preference generating an intrinsics layer that is optimized for performance when called from the Bareflank C/C++ environment. However, the implementation of code that actually *generates* the intrinsics will strongly preference simplicity and ease of use over performance.
* **Namespace Integration** - The generated intrinsics should be callable in such a way that resembles the current x86_64 register access intrinsics, using C++ namespaces to organize the intrinsics appropriately

## Proposed Implementation

The component to be developed will function as a transpiler that will ingest .xml and ASL (provided by ARM) and output one or more C++ header files. The generated C++ code will then be compiled and linked into vmm executable code by the base Bareflank build system. The transpiler will itself be implemented in Python in order to support the design goal of flexibility and ease of use of the transpiler source code. The transpiler scripts will be run at CMake configuration time (when you run ```cmake ..```), and will output C++ header(s) to the current configured CMake (build or source?) directory.

The transpiler will only support parsing the minimal subset of elements needed from the ARM provided .xml specification files. The minimal subset will consist of all .xml data that fully describes how to accomplish the following:
* Read each register defined in the aarch64 architecture by name: ``` aarch64::registers::spsr_el2::read();```
* Read each named bit or bitfield (contiguous group of bits) from each register: ```aarch64::registers::spsr_el2::ge::read();```
* Write each register defined in the aarch64 architecture by name: ```aarch64::registers::elr_el1::write(0xf00dbeef);```
* Set each named bit or write each named bitfield of each register: ```aarch64::registers::spsr_el2::v::write(1);```

## Example

Consider the following snippet from an example ARM specification .xml file that describes the EL2 saved program status register, along with one of that register's named bitfields ("z"):
```
<register is_register="True" is_internal="True" execution_state="AArch64" is_banked="False" is_optional="False" is_stub_entry="False">
      <reg_short_name>SPSR_EL2</reg_short_name>
      <reg_long_name>Saved Program Status Register (EL2)</reg_long_name>

<!-- ... (content ommitted) ... -->

    <field id="Z_30_30" is_variable_length="False" has_partial_fieldset="False" is_linked_to_partial_fieldset="False" is_access_restriction_possible="False">
        <field_name>Z</field_name>
        <field_msb>30</field_msb>
        <field_lsb>30</field_lsb>
        <field_description order="before">
            <para>Set to the value of <register_link state="AArch32" id="AArch32-cpsr.xml">CPSR</register_link>.Z on taking an exception to Hyp mode, and copied to <register_link state="AArch32" id="AArch32-cpsr.xml">CPSR</register_link>.Z on executing an exception return operation in Hyp mode.</para>
        </field_description>
        <field_values>
        </field_values>
        <field_resets>
        </field_resets>
    </field>

<!-- ... (more content ommitted) ... -->

</register>

```

Our developed transpiler would parse this xml snippet and generate something along the lines of the following C++ header:

```
//
// (NOTE: Some boilerplate will go here: license, include guards, includes, etc.)
//

namespace aarch64
{
namespace registers
{

// Saved Program Status Register (EL2)
// Holds the saved process state when an exception is taken to EL2
namespace spsr_el2
{

    inline auto get() noexcept { READ_REG_32(spsr_el2, r0) }; // <-- Not exactly correct, but conveys the idea
    inline void set(uint32_t value) noexcept { WRITE_REG_32(spsr_el2, value) };

    // Set to the value of CPSR.Z on taking an exception to Hyp mode, and copied to CPSR.Z
    // on executing an exception return operation in Hyp mode.
    namespace z
    {
        inline auto get() noexcept { READ_REG_32_FIELD(spsr_el2, 30, 30, r0) };
        inline void set(uint32_t value) { WRITE_REG_32_FIELD(spsr_el2, 30, 30, value) };
    }

}

}
}
```

Note that all of the above inline comments will be generated from xml, and the macros such as READ_REG_32 would be defined in a separate header file that will be written manually (not generated). For example:

```
// Example of what the low-level system register manipulations might look like.
// There would be more for reading/writing general purpose registers.
// These are not 100% correct, but convey the idea.

#define WRITE_SYSREG(sysreg, val, type) \
    asm volatile ("msr "#sysreg", %0\n" : : "r"((type)(val)))
#define READ_SYSREG(sysreg, val, type) \
    asm volatile ("mrs %0, "#sysreg"\n" : "=r"((type)(val)))

#define READ_SYSREG_32(sysreg, val)   READ_SYSREG(sysreg, val, uint32_t)
#define WRITE_SYSREG_32(sysreg, val)  WRITE_SYSREG(sysreg, val, uint32_t)
#define READ_SYSREG_32_FIELD(sysreg, msb, lsb, val)   READ_SYSREG(sysreg, /* bit-twiddling-goes-here*/, uint32_t)
#define WRITE_SYSREG_32_FIELD(sysreg, msb, lsb, val)  WRITE_SYSREG(sysreg, /* bit-twiddling-goes-here*/, uint32_t)

#define READ_SYSREG_64(sysreg, val)   READ_SYSREG(sysreg, val, uint64_t)
#define WRITE_SYSREG_64(sysreg, val)  WRITE_SYSREG(sysreg, val, uint64_t)
#define READ_SYSREG_64_FIELD(sysreg, msb, lsb, val)   READ_SYSREG(sysreg, /* bit-twiddling-goes-here*/, uint64_t)
#define WRITE_SYSREG_64_FIELD(sysreg, msb, lsb, val)  WRITE_SYSREG(sysreg, /* bit-twiddling-goes-here*/, uint64_t)

// ... etc

```

#### Unit Tests

Unit tests will provide test coverage for the *transpiler itself* (i.e. the Python code). Unit-tests will NOT be written to test the generated C++ headers. 100% unit test coverage will be the target for the transpiler component.

#### Integration Tests

Integration testing will consist of running the transpiler against one/several/all of the required XML/ASL files and testing for any exceptions/errors while running the transpiler all the way through to completion (i.e. test that it generates a C++ header with valid contents that successfully compiles)

## Dependencies

The developed transpiler will have two different dependencies: Python and ARM's XML/ASL specification files. Python is already a dependency of Bareflank, but the XML/ASL files will need to be managed:

* ARM XML/ASL files will be checked into a new git repository under the Bareflank group
* Bareflank's build system will need to be modified to include these XML/ASL dependencies during appropriate builds (i.e. include them when the target architecture is aarch64 only)

## Alternative Implementation Strategies:

If Python scripts will not suit our purposes, we could alternatively consider creating a more formal parser/lexer using flex and bison. This would offer the advantage of developing a transpiler with a technology more specialized for that purpose, but would add the complexity of additional build steps, and an additional level of indirection between .xml -> callable C++ function.

**Comment by connojd** [comment]
Overall I think it is a great proposal. I have just a couple things for now:

It may be possible to check generated functions against the emulator. If so that would probably be easier than running them on actual hardware.  That being said, I really like the idea of behavioral testing and it would be great if we could get that working (it would also be nice to have something like that on x86).

I also like the idea of using python, because it will allow us to extend/reuse the initial transpiler code later on e.g. in the event that machine readable specs become more common (one can dream 😃)

**Comment by rianquinn** [comment]
+1 for python. 

My only concern is that I would like the functions to mimic the same functions on the intel side if possible (i.e. set / get instead of read / write). Right now, we have single bit manipulators, bit manipulators that read on their own, vs being supplied a previously read value, bool support, etc.

**Comment by JaredWright** [comment]
I was thinking of making the generated C++ API use get/set just like the Intel side, and having the underlying macros that back those functions use read/write, just like how the intel side has things like _read_msr() and _write_msr() that back those intrinsics.

By "bit manipulators", do you mean to include functions that manipulate bits within a register/data structure by their name, and overload them to be "settable" in multiple ways (bools, ints, etc)? For example, the spsr_el2 register in the example above has a single bit named "z". The generated C++ API should have both aarch64::registers:: spsr_el2::z::set(bool_b), aarch64::registers:: spsr_el2::z::set(int_i), etc?

**Comment by rianquinn** [comment]
Yes, that is what I am referring to. Take a look at the MSR intrinsics for Intel as that has a good example. There are basically two types of getters / settings: int and bool. All of the functions that you see in that file should be supported as they all have important reasons for being there.
