### ISSUE TITLE
[RFC]: Namespace Renaming

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#583]
## Overview

This RFC proposes to rename all xxx_intel_x64 and xxx_64 classes using namespaces instead of embedding this information in the class's name itself. The goals of this modification include:

* **Reduce verbosity** - Although a fully qualified name will likely be more verbose than the current implementation, `using namespace xxx` can be used to reduce this verbosity on demand. 
* **Easier readability** - All of the namespaces in the hypervisor will reflect the current directory structure. For example, `intel_x64::msrs::ia32_monitor_filter_size` becomes `bfintrinsiccs::arch::intel_x64::msrs::ia32_monitor_filter_size`. Once again, this is more verbose, but this verbosity can be removed. The more explicit namespace not only prevents namespace collisions (e.g. the difference between the bfintrinsics vmcs, and the bfvmm vmcs), but also provides the reader with everything they need to locate the code (as the class's qualifiers are the class's location). 
* **Better extension support** - currently, extensions have to provide more verbose class names to prevent collisions. Using namespaces prevents this. The bfvmm and the extended APIs can both have a class located in "vmcs.cpp", and both are called "vmcs". If a collision occurs, you can qualify the name as needed to reduce verbosity, while maintaining readability. 

## Proposed API Changes

No API changes are being proposed. 

### Build tree structure

No build tree structure changes are being proposed. Instead, the goal is to match a class's name to the existing build structure.

**Comment by connojd** [comment]
Overall I like this. My one concern is coupling the namespaces to the directory layout. If we need to change the layout, then will have to change the namespaces as well, or else they become inconsistent. Another possible issue may come from extension writers that may have their preferred directory layout which doesn't match ours.

That being said, I'm in favor of the coupling for my own development sake =)

**Comment by rianquinn** [comment]
Yeah, I had that concern too, but to be honest, I really hope we don't have to move files around anymore so this should be a none issue if we think the directory structure is good too, which at this point, I'm very happy with. 

Another way to put it, I feel the benefits far outweigh the potential risks (especially one that we should really try not to do in the future).

**Comment by connojd** [comment]
Agreed

**Comment by rianquinn** [comment]
I order to simplify this, the intrinsics will use the global namespace while the bfvmm will have the "bfvmm" namespace. So for example, if you see:

```
::intel_x64::vmcs::primary_processor_based_vm_execution_controls
```

That comes from the intrinsics. If you see:
```
bfvmm::intel_x64::check::all()
```

That comes from the vmm. There are still a lot of changes to make that work, but it's explicit without it being overly verbose.

**Comment by rianquinn** [comment]
Completed:

https://github.com/Bareflank/hypervisor/pull/601
https://github.com/Bareflank/hypervisor/pull/595
