### ISSUE TITLE
[RFC]: Source Tree Modifications

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#590]
## Overview

This RFC proposes to swap each modules include/src/tests folders. 

## Problem

Up until now, each file in Bareflank has had its architecture and location hardcoded into the filename itself. A good example of this is:

```
exit_handler_intel_x64_eapis.cpp
exit_handler_intel_x64_eapis_cr_access_hooks.cpp
exit_handler_intel_x64_eapis_io_instruction_emulation.cpp
exit_handler_intel_x64_eapis_io_instruction_vmcall.cpp
exit_handler_intel_x64_eapis_monitor_trap_emulation.cpp
exit_handler_intel_x64_eapis_msr_vmcall.cpp
exit_handler_intel_x64_eapis_rdmsr_emulation.cpp
exit_handler_intel_x64_eapis_rdmsr_vmcall.cpp
exit_handler_intel_x64_eapis_verifiers.cpp
exit_handler_intel_x64_eapis_verifiers_vmcall.cpp
exit_handler_intel_x64_eapis_vpid_vmcall.cpp
exit_handler_intel_x64_eapis_wrmsr_emulation.cpp
exit_handler_intel_x64_eapis_wrmsr_vmcall.cpp
```

Besides the obvious, on Windows this has actually caused compilation issues because MSVC has a small file length maximum size which adds up quick when using CMake. To deal with this, and many other issues, we have moved the repo to use the following tree structure:
https://github.com/Bareflank/hypervisor/issues/533

This has fixed most of the issues, but didn't address extensions having name collision issues. As we started to port the extended APIs, we realized that all extensions would have the same file names and include paths. For example:

```
#include <hve/arch/intel_x64/vmcs/vmcs.h>
```

This currently refers to the bfvmm's vmcs, but this same include also could also refer to the vmcs provided by the EAPIs, and the build system doesn't have any way to resolve the ambiguity. A better path would be:

```
#include <bfvmm/hve/arch/intel_x64/vmcs/vmcs.h>
```

This path both solves the ambiguity, and is explicit, making it easier to read the code as well. To do this, we propose swapping the modules include/src/tests folders. The tree structure would look like this instead:

```
- include
  - bfvmm
    - hve
      - ...
  - bfelf_loader
  ...
- src
  - bfvmm
    - hve
      - ...
  - bfelf_loader
  ...
- tests
  - bfvmm
    - hve
      - ...
  - bfelf_loader
  ...
```

Everything else would remain the same, and git should be able to resolve the changes without huge headaches. 

## Proposed API Changes

No API changes are being proposed.

**Comment by connojd** [comment]
+1

**Comment by Randshot** [comment]
I like it. +1

**Comment by JaredWright** [comment]
Maybe theres a different way to approach this. I sorta don't like grouping all of the source under hypervisor/src, because things like hypervisor/src/bfdriver *looks* to me like bfdriver is part of the hypervisor's source code. Also, it seems like the EAPIS (and other extensions) should strive not to depend on the source tree structure of the hypervisor repo at all.

I could be wrong on this, but doesn't all the eapi's include paths just point to a prefix? The hypervisor repo builds, and then installs all its headers to that prefix, and then the eapi's and other extensions include them from there.

Can't we just change the install step of all headers in CMake to install to prefix/include/bfvmm instead of /prefix/include?

**Comment by connojd** [comment]
Yeah I like @JaredWright's method better if we can make that work

**Comment by rianquinn** [comment]
Yes, we can do that, but the eapis and etc... cannot. We would have to be ok with the hypervisor using:
```
#include <hve/arch/intel_x64/vmcs/vmcs.h>
```

and the eapis using:
#include <eapis/hve/arch/intel_x64/vmcs/vmcs.h>

And to pull this off, will still have to do this for extensions.

**Comment by Randshot** [comment]
If I am not missing something, not all of EAPIs include paths actually point to the prefix.
```CMake
    include_directories(
        ${ARG_INCLUDES}
        ${SOURCE_BFSDK_DIR}/include
        ${SOURCE_BFELF_LOADER_DIR}/include
        ${SOURCE_BFINTRINSICS_DIR}/include
        ${CMAKE_CURRENT_LIST_DIR}
        ${CMAKE_CURRENT_LIST_DIR}/include
)
```
Only the ones that are provided by passing it to `init_project()` can point to the prefix if they are relative and not absolute.

**Comment by rianquinn** [comment]
The toolchain file includes the prefix

**Comment by Randshot** [comment]
Ah, ok. Nvm then.
