### ISSUE TITLE
[BUG] validation of default for `BUILD_TARGET_ARCH` or bad default

### ISSUE THREAD

**Issue by cpavlina** [Bareflank/hypervisor#609]
After the addition of Rian's build system rework, I can't build on aarch64 without the hack in 9a890ea99eaac4f5171fb92b02a572197034140d. This is because the default value is `${HOST_SYSTEM_PROCESSOR}` which in my build environment actually evaluates to `unknown`. This validation is performed sufficiently early that even adding `-DBUILD_TARGET_ARCH=aarch64` to the cmake command line doesn't seem to allow it to proceed; the hack is necessary.

**Comment by JaredWright** [comment]
https://github.com/Bareflank/hypervisor/blob/5d20e31f41a3f5e1f659c6ca7839207d41d9b219/scripts/cmake/config/default.cmake#L42

I think we just need to add an additional case in this block for aarch64

**Comment by rianquinn** [comment]
Agreed

**Comment by cpavlina** [comment]
Makes sense, I didn't realize `HOST_SYSTEM_PROCESSOR` was our own variable being set from cmake's.

**Comment by rianquinn** [comment]
Any variable that has "CMAKE_" in front is a CMAKE variable, all other variables are our own.

**Comment by JaredWright** [comment]
Closing this issue because it is out of date, and is no longer accurate. We will need to revisit this after numerous other build system changes for ARM eventually get added
