### ISSUE TITLE
vmcall__vm_map_foreign_lookup failed

### ISSUE THREAD

**Issue by ptokponnon** [Bareflank/hypervisor#631]
Hello,
I have this issue when starting the basic VM application basic_cxx, to test the hyperkernel [https://github.com/Bareflank/hyperkernel](url).
Environment:
- Ubuntu 17.10 running on KVM-enabled qemu, cpu = host, 
-  Hardware : Intel(R) Core(TM) i5-4300U CPU @ 1.90GHz on Dell Latitude E5540 laptop.
This is the output on the serial line.

> DEBUG: domain init: 0
> WARNING: set_vm_control_if_allowed failed: enable_invpcidcontrol is not allowed to be set to 1
> WARNING: set_vm_control_if_allowed failed: enable_xsaves_xrstorscontrol is not allowed to be set to 1
> WARNING: set_vm_control_if_allowed failed: load_ia32_perf_global_ctrlcontrol is not allowed to be set to 1
> WARNING: set_vm_control_if_allowed failed: load_ia32_perf_global_ctrlcontrol is not allowed to be set to 1
> DEBUG: success: host os is now in a vm on vcpuid = 0
>
> ----------------------------------------
>  Standard Exception Caught
> ----------------------------------------
> GSL: Precondition failure at  /hypervisor/bfvmm/include/memory_manager/map_ptr_x64.h: 924

**Comment by connojd** [comment]
Are you on Linux? Kernels since the spectre/meltdown debacle use PCIDs, which is the lowest 12 bits of CR3. It's likely that Windows does the same, but I'm not sure. The call to lower() checking if bits[11:0] == 0. I think you should be able to place a `cr3 &= 0xFFFFFFFFFFFFF000;` before the call to lower() to fix the problem

**Comment by rianquinn** [comment]
Yeah, we have not tested the hyperkernel since the Meltdown changes to Windows and Linux. We are about to do a pretty massive re-write of that code in the next couple of weeks.

**Comment by ptokponnon** [comment]
Ok, Thank you for the clarification.

**Comment by rianquinn** [comment]
I'm going to close this for now. Let us know if you run into any other issues.
