### ISSUE TITLE
[BUG] Missing lines in unit tests

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#660]
The unit tests for [bfbenchmark.h](https://codecov.io/gh/Bareflank/hypervisor/pull/659/src/bfsdk/include/bfbenchmark.h#L77) and [bfnewdelete.h](https://codecov.io/gh/Bareflank/hypervisor/pull/659/src/bfsdk/include/bfnewdelete.h#L63) are missing some lines.

**Comment by rianquinn** [comment]
Fixed
