### ISSUE TITLE
kernel module build

### ISSUE THREAD

**Issue by kunlilin2991** [Bareflank/hypervisor#669]
I want to develop a misc character device as the interface between a user application (such as the hook application in src_extended_examples_hook) and the protected kernel. I have complete the lkm source code,but, I wonder how can I compile the driver\`s source code along with the extended source code(in src_extended_hook_example)?  for example, after configuration, I just need to run `make` , the module\`s makefile can be executed as well.
I study the way that you build `bareflank.ko`, but is there some way to compile my module with modifying the code in directory src_* but not the hypervisor.
thanks!!!

**Comment by kunlilin2991** [comment]
I note that tools/scripts has benn removed, I used this hypervisor in ubuntu16.04 by  modifying the setup_ubuntu.sh, which works with cmake  version 3.5.1, how can solove the problem mentioned above thanks

**Comment by rianquinn** [comment]
There really isn't a way to compile a userspace application using the kernel build system, they have to be treated as two different projects as their build systems are vastly different. 

Using CMake, you can however treat them as different projects, while still compiling them with a single make command. To do this, you will need three CMakeLists.txt files. One to compile userspace code, one to compile kernel code, and then a third that uses ExternalProject_Add for both projects to compile both using a single make command. We basically do that today, with the one exception that the driver has to still be explicitly compiled (although at one point we had make compiling everything). Just depends on what you add to the ALL target. 

Hope that helps.
