### ISSUE TITLE
'nlohmann/json.hpp' file not found error even after applying the patch from pull #672

### ISSUE THREAD

**Issue by boddumanohar** [Bareflank/hypervisor#674]
I applied this patch, from the pull #672, to enable json build for extensions
```
diff --git a/scripts/cmake/depends/json.cmake b/scripts/cmake/depends/json.cmake
index 5f0dcb29..19f1577d 100644
--- a/scripts/cmake/depends/json.cmake
+++ b/scripts/cmake/depends/json.cmake
@@ -16,20 +16,27 @@
 # License along with this library; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA
 
-if(ENABLE_BUILD_USERSPACE OR ENABLE_BUILD_TEST)
+if(ENABLE_BUILD_VMM OR ENABLE_BUILD_USERSPACE OR ENABLE_BUILD_TEST)
     message(STATUS "Including dependency: json")
-
     download_dependency(
         json
         URL         ${JSON_URL}
         URL_MD5     ${JSON_URL_MD5}
     )
+
 endif()
 
 list(APPEND JSON_CONFIGURE_FLAGS
     -DJSON_BuildTests=OFF
 )
 
+if(ENABLE_BUILD_VMM)
+    add_dependency(
+        json vmm
+        CMAKE_ARGS ${JSON_CONFIGURE_FLAGS}
+    )
+endif()
+
 if(ENABLE_BUILD_USERSPACE)
     add_dependency(
         json userspace
```
For the first time, after applying the patch, the json build works. 
Next time, I created a new a build directory and used the same commands, as the previous one,
```
cmake ../hypervisor -DDEFAULT_VMM=example_vmm -DEXTENSION=../libvmi_extensions
sudo make
```
 this time, the json didn't build!! and I am getting file not found error.  

Why didn't the json build, when I am building from a new directory?

**Comment by boddumanohar** [comment]
I still get this error. So I copied the json.cpp into libvmi_extensions directory and included it using, 
```
include "json.hpp"
```

 Now I am able to do json serialization without using `bfjson.h`. 

Would I run into any problem if I use `json.hpp`this way?

**Comment by rianquinn** [comment]
No, that should work, but I will also take a look at this to see if
something is wrong

**Comment by boddumanohar** [comment]
This is working. something is wrong from my side.
