### ISSUE TITLE
[RFC] convert to pass-by-reference intrinsics + remove intrinsics unit tests

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#675]
This RFC proposes three things:

1. Change all type 2 intrinsics (see definition below) throughout the project to use a pass-by-reference, in/out parameter style

2. Update all of the APIs (including the extended APIs) to use the new style of intrinsics

3. Delete all of the intrinsics unit tests

## Background

All of Bareflank's intrinsics that access a data structure of some kind (MSRs, control registers, page table entries, etc) all follow the same basic pattern. For each accessor (get, set, enable, disable, etc), there is a "type 1" function to access the data structure directly, and a "type 2" function to access a representation of the data structure in memory. For example:

* Type 1 accessor:
```
inline void enable()
{ _write_msr(addr, set_bit(_read_msr(addr), from)); }
```

* Type 2 accessor:
```
inline auto enable(value_type msr)
{ return set_bit(msr, from); }
```

This RFC concerns **type 2** accessors only. Currently, all of the type 2 accessors take arguments by-value, and then return a new value that contains the result after the modification. This works great for all of the intrinsics that we have currently, because every data structure we have an intrinsic for is 64-bits or less in size. Looking into the future (VT-d support), there are some data structures on the Intel platform that are larger than 64 bits in size. For example, VT-d interrupt remapping entries are 128 bits in size, and posted interrupt descriptors are 512 bits. While the current pass-by-value style will technically work, it would make more sense in these cases to pass values by reference, and then modify those values directly in the style of "in/out" parameters. For example:
```
inline void enable(value_type &msr)
{ msr = set_bit(msr, from); }
```

## Reasons for this proposal

For item 1, the type 2 intrinsics are all so similar that this transformation can be scripted (I'm confident that I already have a working solution for that part).

For item 2, most of intrinsics that are actually called by the base hypervisor and extended APIs are the type 1 kind. There are only maybe a few dozen calls to the type 2 intrinsics, so not much to update there.

For item 3, *every* unit test for the intrinsics would need to be manually rewritten to support the new style. But beyond that, I propose that we get rid of all these unit tests anyways because they aren't all that useful in my opinion. For example, consider the following test case:
```
TEST_CASE("ia32_platform_id_platform_id")
{
    using namespace intel_x64::msrs::ia32_platform_id;

    g_msrs[addr] = 0xFFFFFFFFFFFFFFFFULL;
    CHECK(platform_id::get() == (platform_id::mask >> platform_id::from));
    CHECK(platform_id::get(platform_id::mask) == (platform_id::mask >> platform_id::from));
}
```
This test case uses the internals of the implementation to verify the behavior of each function. In the above two checks, if a developer gets the values wrong for platform_id::mask and platform_id::from, the unit test will still pass. Furthermore, the file that test case came from (test_msrs.cpp) is nearly 10,000 lines long, containing mostly this exact same test case duplicated for every msr. I feel that this adds unnecessary complexity and SLOC to the project with no real value, and therefore should be removed. If desired, we could also mark the bfintrinsics directory as excluded from codecov.

**Comment by connojd** [comment]
I like the looks of this! What tests exactly will be removed? All the .cpp under bfintrinsics/tests?

**Comment by rianquinn** [comment]
Yeah, I would only consider getting rid of the tests in bfintrinsics as
they really don't provide any value (they are just bit masks). The rest of
the logic actually tests things that could end up buggy and should stay /
be expanded upon.

**Comment by connojd** [comment]
See #676
