### ISSUE TITLE
lma::disable() freezes the cpu

### ISSUE THREAD

**Issue by boddumanohar** [Bareflank/hypervisor#684]
I enabled IA-32e paging on my system by calling
```
::intel_x64::vmcs::guest_ia32_efer::lma::enable();
```
This works just fine, and in the userspace, and even after many power cycles, when I check for lme bit of MSR_EFER register, it is always set. 

Later, I wanted to switch back to PAE paging, so  I tried to clear lme bit by calling:
```
::intel_x64::vmcs::guest_ia32_efer::lma::disable();
```
this freezes my cpu. I had to forcefully press the power button. 

here is the code, of extension, that I used to disable. https://github.com/boddumanohar/disable_lme/blob/master/src/disable_lme.cpp#L49

The demo code is:
```
#include<stdio.h>
int main() {
    asm("vmcall");
    return 0;
}
```
Is this a correct way to switch back to PAE paging?

**Comment by rianquinn** [comment]
LME is always enabled in the hypervisor as it is needed for 64bit. You cannot disable this in the VMM without doing a proper switch to 32bit mode.
