### ISSUE TITLE
[RFC]: VT-d IOMMU Intrinsics

### ISSUE THREAD

**Issue by JaredWright** [Bareflank/hypervisor#690]
## Overview

This RFC proposes additional intrinsics to add support for Intel® VT-d to Bareflank.

## Background

RFC #679 added intrinsics to manipulate the numerous translation table structures listed in Chapter 9 of the [Intel® Virtualization Technology for Directed I/O Architecture Specification](https://software.intel.com/sites/default/files/managed/c5/15/vt-directed-io-spec.pdf). This RFC proposes adding more intrinsics to manipulate the register's of a hardware remapping unit (IOMMU) on the intel platform, listed in Chapter 10 of the [same spec](https://software.intel.com/sites/default/files/managed/c5/15/vt-directed-io-spec.pdf).

## Proposed Changes

On the Intel platform, an IOMMU is accessed via memory-mapped IO at a location defined by the platform's ACPI tables (specifically, DRHD). Since this base address will vary across systems, a small class will be created to wrap the IOMMU's base address, and provide read/write primitives for accessing each register by its offset (defined in the spec):

* bfintrinsics/include/arch/intel_x64/vtd/phys_iommu.h

```
class phys_iommu
{

public:

    phys_iommu(uintptr_t base) : m_base(base) { }

    ~phys_iommu() = default;

    inline uint32_t read_32(uint32_t offset)
    { return *reinterpret_cast<uint32_t *>(m_base + offset); }

    inline uint64_t read_64(uint64_t offset)
    { return *reinterpret_cast<uint64_t *>(m_base + offset); }

    inline void write_32(uint32_t offset, uint32_t val)
    { *reinterpret_cast<uint32_t *>(m_base + offset) = val; }

    inline void write_32_preserved(uint32_t offset, uint32_t val, uint32_t mask)
    { write_32(offset, (read_32(offset) & mask) | (val & ~mask )); }

    inline void write_64(uint64_t offset, uint64_t val)
    { *reinterpret_cast<uint64_t *>(m_base + offset) = val; }

    inline void write_64_preserved(uint64_t offset, uint64_t val, uint64_t mask)
    { write_64(offset, (read_64(offset) & mask) | (val & ~mask )); }

private:

    uintptr_t m_base;

};
```

In addition, intrinsics will be added to a new file bfintrinsics/include/arch/intel_x64/vtd/iommu.h. Only the *appropriate* accessors will be included for each register and field defined in the spec according to the register/field's defined permissions (read-only, read-write, write-only, etc). The C++ namespaces that will represent each register and field will be *exactly* as they appear in the manual (i.e. the initialism for the register), while the "name" constants in each namespace will use the non-initial name for printing/debugging. For example:

```
namespace ver_reg
{
	constexpr const auto name = "version_register";
	constexpr const auto offset = 0x000;

	using value_type = uint32_t;

	inline auto get(const gsl::not_null<phys_iommu *> iommu) noexcept
	{ return iommu->read_32(offset); }

	namespace min
	{
		constexpr const auto mask = 0xFULL;
		constexpr const auto from = 0ULL;
		constexpr const auto name = "minor_version_number";

		inline auto get(const gsl::not_null<phys_iommu *> iommu) noexcept
		{ return get_bits(iommu->read_32(offset), mask) >> from; }

		inline auto get(const value_type &ver_reg) noexcept
		{ return get_bits(ver_reg, mask) >> from; }

		inline void dump(int level, const value_type &ver_reg, std::string *msg = nullptr)
		{ bfdebug_subnhex(level, name, get(ver_reg), msg); }
	}

	namespace max
	{
		constexpr const auto mask = 0xF0ULL;
		constexpr const auto from = 4ULL;
		constexpr const auto name = "major_version_number";

		inline auto get(const gsl::not_null<phys_iommu *> iommu) noexcept
		{ return get_bits(iommu->read_32(offset), mask) >> from; }

		inline auto get(const value_type &ver_reg) noexcept
		{ return get_bits(ver_reg, mask) >> from; }

		inline void dump(int level, const value_type &ver_reg, std::string *msg = nullptr)
		{ bfdebug_subnhex(level, name, get(ver_reg), msg); }
	}

	inline void dump(int level, const value_type &ver_reg, std::string *msg = nullptr)
	{
		bfdebug_nhex(level, name, ver_reg, msg);

		min::dump(level, ver_reg, msg);
		max::dump(level, ver_reg, msg);
	}

	inline void dump(int level, const gsl::not_null<phys_iommu *> iommu, std::string *msg = nullptr)
	{
		auto reg_val = get(iommu);
		dump(level, reg_val, msg);
	}
}
```

## Questions and Comments

* The phys_iommu class maintains state (a single pointer), and therefore arguably doesn't belong under the bfintrinsics folder. However, I can't think of a better place to put it. Any suggestions?

**Comment by connojd** [comment]
There was also a small amount of state for the IOAPIC and xAPIC. I put classes for those in the extended APIs. I don't really have a preference, but we should remain consistent with whatever we decide. I can move the apic classes to base if need be

**Comment by JaredWright** [comment]
Agreed about consistency, I'll move the phys_iommu class to the extended apis to conform to the existing pattern with the ioapic and xapic.

**Comment by JaredWright** [comment]
Nevermind, I can't move the phys_iommu class to the eapis, because the iommu intrinsics depend on that class. Both need to be in the same repo, and since all of the other vtd intrinsics are in the base, I'm inclined to keep everything in the base.

How about putting phys_iommu.h under bfvmm/include/hve/arch/intel_x64/vtd/phys_iommu.h?

**Comment by connojd** [comment]
:+1:

**Comment by JaredWright** [comment]
Merged
