### ISSUE TITLE
hiding hypervisor from guest OS?

### ISSUE THREAD

**Issue by mingwayzhang** [Bareflank/hypervisor#722]
Hi,

I am wondering whether bareflank did hiding itself from guest OS or does protection on EPT and its own code/data and prevent access to them. If so, could you point out the location of the code? Thanks.

**Comment by rianquinn** [comment]
Not by default. If you want to use EPT, you need to include the Extended APIs repo. From there, you can set up whatever protections you want.

**Comment by rianquinn** [comment]
For example:
https://github.com/Bareflank/extended_apis_example_hook

**Comment by rianquinn** [comment]
I am going to close this for now. Let me feel free to open this ticket again if you have any more questions.
