### ISSUE TITLE
[QUESTION]: State of UEFI development

### ISSUE THREAD

**Issue by pietrushnic** [Bareflank/hypervisor#725]
Hi,
We are interested in Bareflank hypervisor support for UEFI. The website says it is under development, what is the status of development? Can we help in debugging/development?

**Comment by rianquinn** [comment]
It currently works fine so long as you include the Extended APIs. We absolutely could use more testing, however. The instructions for setting up EFI are on the main README.md, but I will also do a screencast tomorrow morning and upload it to our YouTube channel to help walk you through it. 

The short answer is, use the example config and turn on EFI and the extended APIs. Once you do that, the build system should output a bareflank.efi. Put that on your EFI partition and run it before you run Windows or Linux. If all goes well, the OS will load while under Bareflank. You can then use the rest of the APIs to set up Bareflank to do whatever you want. 

There are a couple of limitations that we have not fixed yet (would love help finishing these):
- When using Linux, you might have to tell Linux to use the INIT delay. We need to patch the Linux kernel with a BF specific init to prevent the INIT delay from being set to 0. Ubuntu works fine, but Arch doesn't. We talked to the Linux community and even though this is an issue for all hypervisors, they would prefer a BF specific fix. 
- Sleep is not supported. If you put the system to sleep, when you wake BF will no longer be loaded. We need to add a sleep handler to EFI to reload BF on wake.

**Comment by pietrushnic** [comment]
@rianquinn thanks for prompt feedback. I will try that as soon as I will find the time. We wonder about loading 4 independent bare metal binaries, but I assume first we would like to exercise how Linux works to understand principles. Will get back to you as soon I will exercise described procedure.

**Comment by rianquinn** [comment]
I updated the README to be a bit more explicit.

**Comment by rianquinn** [comment]
@pietrushnic Here is the YouTube video that shows how to do this. 
https://www.youtube.com/watch?v=FuEyjDqA53M&t=4s

I am going to close this for now. If you have any more questions, please don't hesitate to reach out.

**Comment by pietrushnic** [comment]
@rianquinn thanks for that video. I have couple comments, which I would publish later e.g. I'm not sure why EFI is used, if we talking about UEFI.

Anyway, we investigating Bareflank internally and would like to do more research about it. Our goal is to run couple executables in separate VM, we will is if we can figure out how to do that.

**Comment by rianquinn** [comment]
@pietrushnic Sorry. I used to work a lot on EFI before it became UEFI, so I have a tendency to say EFI when I really mean UEFI. As for guest support, we are working on that work now. I should have a video on our progress by the end of the week which will include installation, UEFI and guest support on Windows (Linux works too) which will demo the ability to launch guest VMs from Bareflank after it was loaded using UEFI.  

With that said.... guest support is very new. We can launch applications (C, C++ or Linux) so long as the application starts using the HVMLite protocol for Xen, which is really just 32bit Protected mode with Paging disabled. There currently isn't any support for disk or network, but we do have write-only serial support. Starting next year, we will be working on a more polished implementation of guest support that includes the ability to do disk, network and a full serial device and the specifics of that work will be announced near Christmas including what we plan to implement, tasking, and whose doing what which will absolutely include tasks that the rest of the community can help us complete. 

As for building and running our internal demo (the demo I plan to make the video one in the next couple of days), if you want to run and install that yourself, let me know and I can make a quick video on that with a giant warning stating that its still in heavy development. 😄
