### ISSUE TITLE
[QUESTION]: UEFI `make ack`

### ISSUE THREAD

**Issue by krystian-hebel** [Bareflank/hypervisor#726]
Hi,
This is a follow-up for previous question (#725 ). I'm also working with @pietrushnic in 3mdeb, and we have a couple of questions.

We've prepared a Docker container for better reproducibility and easier development, but we've hit some obstacles. As I understand, `make ack` is mentioned as a way for verifying if VMM started successfully, but it has to be run from within started OS. As we're working mostly on embedded devices, setting up OS with development environment can be difficult sometimes. Is it possible to check it from within UEFI, for example by preparing small UEFI application with `vmcall` instruction? This may require writing a handler for `#UD` exception, but in our case this can be easier than installing OS (we're building custom UEFI image anyway).

Another question is about size of bareflank.efi. It will probably be embedded in flash chip in our project, so 2 MB seems a little too big. Is there any way to make it smaller? If I understood instructions from README correctly, extended_apis are required to boot Windows and Linux, is it possible for other binaries (say, UEFI applications for example) to work without them?

There is also an issue with `make clean`. Shouldn't it remove `build` directory?

**Comment by connojd** [comment]
@krystian-hebel the make ack command uses cpuid to ping the hypervisor. From your UEFI app you could call cpuid with rax = 0xBF00 (see https://github.com/connojd/hypervisor/blob/hyperkernel_1/bfvmm/src/hve/arch/intel_x64/exit_handler.cpp#L772 for an example). If you're working off of the master branch, you may need to add a handler for cpuid, the one I linked is on my hyperkernel_1 branch).

> Another question is about size of bareflank.efi. It will probably be embedded in flash chip in our project, so 2 MB seems a little too big. Is there any way to make it smaller?

Yep there are a whole list of things we could do. Do you have a size limit in mind?  @rianquinn we haven't had many embedded uses yet so what do you think is best here?

> If I understood instructions from README correctly, extended_apis are required to boot Windows and Linux, is it possible for other binaries (say, UEFI applications for example) to work without them?

Definitely. Depeding on your environment, there are a whole host of things that could be eliminated. Alot of code in the eapis is to support INIT-SIPI and booting from < 64bit (EPT and unrestricted guest)

> There is also an issue with make clean. Shouldn't it remove build directory?

I don't think so, but @rianquinn would know better than me

**Comment by rianquinn** [comment]
To reduce the overall size, I would start by ensuring that developer mode is turned off so that you get full optimizations. I would also play around with the settings in bfconstants.h as the memory buffers that are compiled in are located there, and there are some things you can do to make things small there too. 

If that doesn't make it small enough, you can get a bit more heavy-handed by also doing things like turning off exception support which will also make things smaller. 

As for make clean, we use a CMake build system, so no, it will not remove the build directory as that is how CMake is designed. If you want to do a  completely fresh build, you should wipe your build folder and start again.

**Comment by krystian-hebel** [comment]
Thank you both for answers.

Indeed, cpuid seems safer than vmcall, I'll look into adding a handler.

Changing bfconstants.h doesn't help enough, only a couple of kB can be saved this way, we will need more. Doing `strip vmm` before `xxd` brings the size down to 1.6 MB, which is better. Perhaps we will even need to compress this file, as at he moment we have about 550 kB available, maybe after some clean-up we might hit 1-1.2 MB.

**Comment by rianquinn** [comment]
Yeah, if you only have that much, I would compress. With my testing, I have not seen this code smaller than 1mb in size. I just did a simple gzip on our hyperkernel, which has a lot more code in it, and without a strip it was 440K, so compression + strip should provide you with more than enough space.

**Comment by rianquinn** [comment]
Closing this for now. Let me know if you have any other questions.
