### ISSUE TITLE
[BUG] CMake fails

### ISSUE THREAD

**Issue by krystian-hebel** [Bareflank/hypervisor#734]
CMake fails on rc2.0.3 with:

```
--     failed to download https://github.com/bareflank/capstone/archive/v2.0.zip
CMake Error at scripts/cmake/macros.cmake:396 (message):
  Failed to download https://github.com/bareflank/capstone/archive/v2.0.zip
  with md5 hash of 2d3809e48b97d93e29e6b6ac7a0dd1aa
```

I know that there is rc2.0.4 available which builds correctly, but shouldn't tagged versions be supported for at least some time? It makes it very hard to keep up with changes, especially if most of the commits are squashed merges, tens of thousands changed lines of code each.

**Comment by rianquinn** [comment]
Yeah, I will fix that. We never actually used capstone so I just have to delete that code in cmake and then I will update the RC. Sorry about that. For now, in the top level CMakeLists.txt just delete the "include_dependency" line that says capstone in it and the problem will go away

**Comment by pietrushnic** [comment]
@rianquinn thanks for the support. We entering the final planning phase for our UEFI hypervisor, so would be glad to stick to some code base which will not change suddenly. Can we assume `rc2.0.4` is a good candidate?

**Comment by rianquinn** [comment]
FYI, this should be fixed. Let me know if you still have issues.

**Comment by krystian-hebel** [comment]
@rianquinn unfortunately problem still exist. We decided to move towards merged extended_apis anyway (great idea to merge them BTW), so this won't be a problem, at least for us.

**Comment by rianquinn** [comment]
Ok, I'll take another look at it tomorrow. I still want to make sure that its working properly before I close this. I might have messed something up (updating a release tag in GitHub is clunky)

**Comment by rianquinn** [comment]
Yup, somehow my changes never made it into the main branch. I just cut a new release and tested it and everything works with capstone removed. Everything should be good to go now.
