### ISSUE TITLE
extended_apis_example_hook compilation error

### ISSUE THREAD

**Issue by wooddii** [Bareflank/hypervisor#738]
Hello, having trouble compiling https://github.com/Bareflank/extended_apis_example_hook:
![image](https://user-images.githubusercontent.com/35064537/52167134-af506480-2727-11e9-9bb3-5fd0f6388241.png)

Used the following commands in the Cygwin terminal under Windows 10 x64: 
```
git clone https://github.com/Bareflank/hypervisor
git clone https://github.com/Bareflank/extended_apis
git clone https://github.com/Bareflank/extended_apis_example_hook.git
mkdir build; cd build
cmake ../hypervisor -DDEFAULT_VMM=example_vmm -DEXTENSION="../extended_apis;../extended_apis_example_hook"
make -j3
```

Error is:
![image](https://user-images.githubusercontent.com/35064537/52167143-bd05ea00-2727-11e9-98b6-115b1c9cc57b.png)

How can I fix it? Clear BareFlank with compilation instructions from readme compiles & works great.

**Comment by rianquinn** [comment]
I am going to close this for now. If you are still having issues after moving to RC2.0.4, please let us know.
