### ISSUE TITLE
[FEATURE REQUEST]: User object per vCPU

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#743]
With the new APIs, there is no ability to create a user object that is tied to each vCPU. I would like to propose a chance to the vCPU to store a user object using a std::any. Specifically, this change to the vCPU would add the following:

```
auto mydata = vcpu->data<mydata>();
vcpu->set_data<mydata>(mydata{});
```

This way, the user can store data as they wish within the vCPU. I propose using std::any (even though I would typically advocate against this) as any feature like this would require a malloc so the malloc that is used by std::any is not a big deal, and unlike just storing a void *, this would provide type safety.

**Comment by JaredWright** [comment]
I love it. How would access your data later from a handler? Something like this?

```
bool my_handler(vcpu *vcpu)
{
    auto mydata = vcpu->get_data<mydata>();
   ...
}
```

**Comment by JaredWright** [comment]
Also... would this feature be added to the base vCPU or the intel-specific vCPU?

**Comment by rianquinn** [comment]
This would be added to the base vCPU, and you would access it like this:

```
bool my_handler(vcpu *vcpu)
{
    auto mydata = vcpu->data<mydata>();
   ...
}
```

which is more "C++" ish.

**Comment by rianquinn** [comment]
Done
