### ISSUE TITLE
Sign Windows driver

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#848]
We need to add steps in our build system to sign the drivers with something other than the test signature.

**Comment by JaredWright** [comment]
How do you envision this working? Something along the lines of adding a CMake configuration with a path to the certificate to be used for signing drivers?

**Comment by rianquinn** [comment]
This should be a quick fix. Basically, the driver code is signed right now using a test signature that has to be uploaded, which is actually already in the scripts. All we have to do provide a way to replace the test signature with a real one (like check for the existence of a file) and then document how it works.
