### ISSUE TITLE
amd support

### ISSUE THREAD

**Issue by Labuurii** [Bareflank/hypervisor#856]
As I understand AMD is not supported currently. Is there any plans?
If not can you point me in the right direction so I can learn and port that part myself?
I got plenty of time.

**Comment by rianquinn** [comment]
AMD support (and ARM) are both things that we plan to implement on this project. In fact, if you look at the code, we have a lot of references to plan x64 and not intel_x64 as the x64 code is code that we know will be shared between AMD and Intel (AMD, of course, would be called amd_x64). If you want to take a stab at adding support, we would love to help you along the way. 

Satoshi (author of HyperPlatform) created a project for turning on AMD virtualization that mimicked SimpleVisor called SimpleSvm: https://github.com/tandasat/SimpleSvm. This would be my starting point for adding support.

**Comment by JaredWright** [comment]
@Labuurii Thanks for your interest in the project! If AMD support is something that you are interested in implementing, here is a high-level approach I would use to start down that path:

1) Get intimately familiar with Bareflank's build system (based on CMake). Learn how builds are configured, what types of builds go into our CI process, how unit tests are integrated, and how Bareflank extensions are built. Check out ```hypervisor/scripts/cmake```, and the ```CMakeLists.txt``` files throughout the project.
2) Look into what it would take to add AMD-specific intrinsics (```hypervisor/bfintrinsics/include```, and a few others under ```hypervisor/bfintrinsics/src```). In Bareflank, all accesses to hardware and virtualization control structures go though an intrinsic function. This layer of the project aims match the language of CPU reference manuals as close as possible. There will likely be a lot of AMD intrinsics to be added.
3) Look at the components under ```hypervisor/bfvmm/hve``` for the "main" components that make up a Bareflank based hypervisor. This is probably where the bulk of AMD support would need to be added.

A good first goal to aim for would be to print "hello world" over serial from a vmexit handler for the CPUID instruction.

**Comment by Labuurii** [comment]
Thank you, I will take a look :)
