### ISSUE TITLE
Page Table Scan?

### ISSUE THREAD

**Issue by adilahmad17** [Bareflank/hypervisor#859]
Hey,

Is there a way for Bareflank to perform a faster page table scan? Like scanning the whole
page table, i.e., each entry?

Thanks!
Adil

**Comment by rianquinn** [comment]
With respect to which APIs? Can you send a link to the code you are referring too?

**Comment by rianquinn** [comment]
Closing this for now. If you have any more questions, please open another ticket

**Comment by adilahmad17** [comment]
Sorry for the late replies! I figured this out! :)

**Comment by rianquinn** [comment]
No problem. Good luck!!!
