### ISSUE TITLE
undefined mutex_lock and mutex_unlock when build for windows

### ISSUE THREAD

**Issue by InvisK** [Bareflank/hypervisor#864]
Hello, im using Visual Studio 2017 to build the hypervisor project but i get mutex_lock and mutex_unlock undefined, how to fix it?

**Comment by InvisK** [comment]
should fix by replace to ExAcquireFastMutex and ExReleaseFastMutex?

**Comment by InvisK** [comment]
also in driver.c at line 26
> extern int g_status = 0; << multi define warning

maybe it's should to be ?

>  extern int g_status;

>

**Comment by rianquinn** [comment]
Are you using master? This should be fixed, but the fix might be in one of my branches. Either way, if this is still an issue in master I can draft up a patch quick. This stuff was added just recently to support sleep/resume on Boxy properly.

**Comment by InvisK** [comment]
hello, yes im using master branch, by Visual Studio 2017.

**Comment by connojd** [comment]
Fixed in #866
