### ISSUE TITLE
Windows 10 1809 x64 - driver unload fail code c0000010 - STATUS_INVALID_DEVICE_REQUEST

### ISSUE THREAD

**Issue by InvisK** [Bareflank/hypervisor#865]
hello, im loaded bareflank.sys ok but i cant unload the driver, it's returned c0000010 - STATUS_INVALID_DEVICE_REQUEST by NtUnloadDriver.

**Comment by rianquinn** [comment]
Are you using the "make driver_load", "make driver_unload" scripts from cygwin? Also, what version of Windows are you on?

**Comment by InvisK** [comment]
hello, im using Novirus-thanks driver loader, after driver unload failed im try to use my own code with NtUnloadDriver, all same return c0000010.

**Comment by rianquinn** [comment]
@InvisK Did you ever sort this out? I am seeing something similar with "make stop" on 1903. The difference is I get a hang on one of the cores, but the rest of the system seems to run fine until I attempt to reboot when I just get an endless reboot

**Comment by rianquinn** [comment]
I am going to close this for now, and open a new bug report for the 1903 issue so that we can track this
