### ISSUE TITLE
[VOTE]: Unit Test Coverage

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#870]
When we started the project, we added Coveralls support to ensure we have 100% test coverage and we learned a couple of things:
- Coveralls itself didn't seem to work well for our project. We ran into a lot of issues with how it was processing the coverage reports from gcov. 
- Getting to 100% didn't offer any real value. There is a difference between code coverage and test coverage and attempt to achieve code coverage definitely is not as valuable as getting good test coverage. The problem is there is no way to measure test coverage. 

Later we added support for Codecov which lately has had its own issues with the coverage reports. 

I would like to take a quick vote. Personally, I have invested a lot of time into ensuring 100% code coverage, but as the project grows, this requirement is becoming harder and harder to maintain, and there really doesn't seem to be a benefit to doing it. Test coverage seems far better, meaning unit tests are designed to ensure input/output acts as expected and the author of the code needs to ensure the input is comprehensive. To add to the mess, the coverage tools have a lot of problems only adding to the complexity and time it takes to maintain. 

At this point, I am in favor of removing code coverage from the project in favor of test coverage. If you agree, please vote this comment up, otherwise vote down.

**Comment by JaredWright** [comment]
I support removing code-coverage tracking from the project, primarily because I feel that it distracts from the goal of creating high quality tests (rather than high quantity). To be clear: I believe we should continue our requirement for unit-tests within the project, and I view removing code-coverage as a means to focus on increasing the *quality* of our unit tests.

**Comment by connojd** [comment]
SGTM

**Comment by rianquinn** [comment]
With no objections, I am going to close this and move forward.
