### ISSUE TITLE
[BUG] buddy allocator hangs when request is greater than available memory

### ISSUE THREAD

**Issue by connojd** [Bareflank/hypervisor#876]

**Comment by rianquinn** [comment]
Just don't allocate more memory than you have and you will be fine :smile:

**Comment by boddumanohar** [comment]
is it possible to have a check between requested memory and available before Bareflank loads?

**Comment by rianquinn** [comment]
Yes and no.  My hope is to remove the need for the buddy allocator in favor of just a page allocator. I will have more details on that soon, which should make this issue OBE.
