### ISSUE TITLE
[RFC]: Move to Slack

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#879]
Gitter is causing a lot of issues for me, and the mobile app is not really working at all on my iPhone. Anybody have any issues with us moving to slack? Any better ideas for a chat engine? I like the idea of slack as most people already use it, so it is one less app that people will have to install on their phones.

**Comment by boddumanohar** [comment]
+1 for slack.

**Comment by Randshot** [comment]
I would like to suggest [Matrix](https://matrix.org/) as an alternative.

**Comment by rianquinn** [comment]
Does Matrix have a mobile app that works? My issue with Gitter is that the mobile app is basically abandoned. Slack also has the advantage that most developers already have it installed.

**Comment by Randshot** [comment]
@rianquinn Matrix itself is only the underlying protocol name, but yes, there are mobile clients for both Android and iOS: https://matrix.org/clients/
Some homeservers (like matrix.org) also have bridges to Gitter and/or Slack: https://matrix.org/bridges/
If needed, there are also GitHub bots available (for selfhosting): https://github.com/maubot/github

**Comment by rianquinn** [comment]
Ok, I downloaded an tried some of the apps for iOS and I was not a huge fan. This might be another option too. Thoughts?
https://bareflank.zulipchat.com/#
