### ISSUE TITLE
[BUG] EPT and ia32_vmx_cr0_fixed0 issue

### ISSUE THREAD

**Issue by krystian-hebel** [Bareflank/hypervisor#881]
`g_vcpu_global_state` is used for host VM. It includes `ia32_vmx_cr0_fixed0` field, which is changed later if EPT is used - paging and protected mode are no longer forced to be enabled in order to support unrestricted guests.

However, this field is used in vCPU constructor's initializer list (specifically, `control_register_handler::enable_wrcr0_exiting()` uses it), before EPT handler changes it. As a result, BSP uses different mask for CR0 than the rest of cores.

Because of that BSP cannot use some modes of operation (like paged 32b with PAE enabled), while APs can.

**Comment by rianquinn** [comment]
huh... nice catch. Do you want to provide a patch to fix this? In the future, we need to handle CR0 and CR4 differently as this type of issue is possible with the current approach.

**Comment by krystian-hebel** [comment]
Sorry, I forgot to reply earlier. I can do this, but it would be sometime in next week. I dug into some project and cannot afford to go through rebasing this patch to master at the moment.

**Comment by rianquinn** [comment]
No problem. We are not in a rush as our primary focus at the moment is our rework branch.

**Comment by rianquinn** [comment]
Any luck on a fix?

**Comment by krystian-hebel** [comment]
Code was lying on my disk for some time, forgotten... Sorry again, I had quite busy end of year.
https://github.com/Bareflank/hypervisor/pull/883

**Comment by rianquinn** [comment]
No worries, I feel your pain. Thanks a ton for the patch.
