### ISSUE TITLE
Cmake failed in Windows 10

### ISSUE THREAD

**Issue by Changochen** [Bareflank/hypervisor#882]
Hi. I am trying to compile bareflank on windows 10. I followed the instructions in the readme(Install vs 2019 and wdk etc, but not cygwin). When I execute `cmake ..\hypervisor`, I got the following error:

`CMake Error at C:/Program Files/CMake/share/cmake-3.16/Modules/ExternalProject.cmake:2962 (get_property):
  get_property could not find TARGET libcxxabi_x86_64-vmm-elf.  Perhaps it
  has not yet been created.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.16/Modules/ExternalProject.cmake:3239 (_ep_add_configure_command)
  scripts/cmake/macros.cmake:408 (ExternalProject_Add)
  scripts/cmake/depends/libcxx.cmake:55 (add_dependency)
  scripts/cmake/macros.cmake:188 (include)
  CMakeLists.txt:111 (include_dependency)

-- Extension: C:/Users/Ne0/Downloads/hypervisor-master/hypervisor-master/examples/cpuidcount
-- Extension: C:/Users/Ne0/Downloads/hypervisor-master/hypervisor-master/examples/hook
-- Extension: C:/Users/Ne0/Downloads/hypervisor-master/hypervisor-master/examples/rdtsc
-- Extension: C:/Users/Ne0/Downloads/hypervisor-master/hypervisor-master/examples/vpid
CMake Error at scripts/cmake/macros.cmake:975 (message):
  ENABLE_BUILD_VMM is not supported on Windows
Call Stack (most recent call first):
  scripts/cmake/validate.cmake:93 (invalid_config)
  CMakeLists.txt:198 (include)`

I modified scripts/cmake/config/default.cmake to make it support vs 2019, but it still failed. Is it possible to compile it on Windows without cygwin? Any help is appreciated.

**Comment by rianquinn** [comment]
No. You must have cygwin as we cross compile which is not supported by MSVC
