### ISSUE TITLE
Benchmarking within the hypervisor

### ISSUE THREAD

**Issue by adilahmad17** [Bareflank/hypervisor#889]
Hey,

I was wondering if there is a timer implementation in Bareflank, basically
for benchmarking purposes?

I can see that `bfsdk` uses `chrono` for benchmarking but it seems that the function `benchmark(..)` hangs whenever I call it within my hypervisor pass (basically similar to the hook example). Any ideas?

Thanks!

**Comment by rianquinn** [comment]
There isn't. Actually, we have worked pretty hard to ensure that Bareflank doesn't need a timer, and relies on the host operating system for timing, scheduling, etc...

**Comment by adilahmad17** [comment]
Ah, I see. Thanks for the information anyways! :)
