### ISSUE TITLE
Bareflank as a VMM for hypervisor question

### ISSUE THREAD

**Issue by Outstep** [Bareflank/hypervisor#893]
Greetings,

I hope that everyone is going well.

I have been on this hypervisor journey for a while now as it seems to mold and take on a form of it own as I move through the process.

What I am looking to do is to possibly port Bareflank (or similar) single instance VMM over to an x86_64 platform hypervisor and wanted to try and get some information as to how stable and challenging this porting might be?

I am also interested if the current version of Bareflank can run both 32- and 64-bit Guest OS's like Linux, Windows, etc..

The remaining question would also be as to how hard it might be to add in the RDP protocol (FreeRDP, rdesktop, or some other?

Of course the current hypervisor code does not have any type of xserver, but is currently the core small footprint hypervisor and components are being added as needed.

Any information would be greatly appreciated.
Cheers,

**Comment by Outstep** [comment]
On an additional question, I was wondering how Bareflank (Boxy) can compare to the FreeBSD Bhyve or OSX port Xhyve since really these are currently the only ones that I am considering at the moment.

**Comment by rianquinn** [comment]
Sorry for the late reply here. Bareflank itself doesn't have any guest support. To get guest support you would need either Boxy, or wait for the newer MicroV project the finish. Both Boxy and MicroV can handle any fully enlightened guest operating system including 32bit or 64bit, but the upstream projects for now only support our custom version of Linux. You would have to add support for something else (we want to add unikernel support at some point as well). Windows guests is something that we want to get to, but that will take time. Also, Boxy itself doesn't have any virtual device support. That is something that MicroV will be working on over the next year or two. Once that is done, something like RDP should be possible. As for how we compare to Bhyve, please check out the description of MicroV as that should answer your question. 

Thanks a ton for the interest in our project and let us know what you think.
