### ISSUE TITLE
[ANNOUCEMENT] Bareflank Community Call - 3pm UTC on 6/12/2020

### ISSUE THREAD

**Issue by rianquinn** [Bareflank/hypervisor#915]
AIS will be holding a Bareflank Community Call at 3pm UTC on 6/12/2020 via Zoom. Or goal with the community call is to:
- Provide users with an opportunity to ask questions and meet the team. 
- Learn more about the future of the Bareflank projects including the hypervisor, Boxy/MicroV, the BSL, PAL and the Standalone C++ library. 

If you have a topic that you would like to discuss, please add it to this issue.  As we get closer to the call, I will post the Zoom info as well as draft a rough agenda based on the feedback we get here. Everyone is welcome to join and add items to the agenda.

**Comment by rianquinn** [comment]
The biggest thing that I would like to see talked about during the call are the changes coming to the hypevisor and MicroV repos based on the conversations in the Bareflank 3.0 issue. This includes the addition of the microkernel, the removal of some of the APIs, how we plan to support Libc++ (for those who really want this) as well as other languages in the VMM like Rust and Python, etc...

**Comment by rianquinn** [comment]
AMD and maybe even ARM support is another topic I think we should discuss.

**Comment by pietrushnic** [comment]
@rianquinn AMD would be very interesting :) 3mdeb will definitely participate.

**Comment by rianquinn** [comment]
> @rianquinn AMD would be very interesting :) 3mdeb will definitely participate.

Looking forward to seeing you there.

**Comment by rianquinn** [comment]
We should probably also talk about some of the Xen work we are doing, and our plans for how we plan to open source it (hopefully with the Xen community). There will likely be a larger discussion on this at the Xen Summit.

**Comment by rianquinn** [comment]
Ok, based on a bunch of feedback that we have gotten, this is the agenda for next week. Feel free to continue to add to this list if you would like something else to be discussed

- [ ] Introductions
    - How are you using the project?
- [ ] Microkernel Architecture
- [ ] Separating the loader/kernel from the virtualization extensions library
    - Preference for Bareflank/hypervisor
- [ ] Plans for Boxy/MicroV
    - Xen Hypercall Support
    - Working with the Xen Community
- [ ] PAL
- [ ] AMD/ARM Support
- [ ] AUTOSAR Support

**Comment by rianquinn** [comment]
Here is the Zoom information for tomorrow's meeting

Rian Quinn is inviting you to a scheduled ZoomGov meeting.

Topic: Bareflank Community Call
Time: This is a recurring meeting Meet anytime

Join ZoomGov Meeting
https://ainfosec.zoomgov.com/j/1600996390?pwd=SUpxK1d1SDdYQWFrLzN0Ni9zOERSZz09

Meeting ID: 160 099 6390
Password: 068712
One tap mobile
+16692545252,,1600996390#,,1#,068712# US (San Jose)
+16468287666,,1600996390#,,1#,068712# US (New York)

Dial by your location
        +1 669 254 5252 US (San Jose)
        +1 646 828 7666 US (New York)
Meeting ID: 160 099 6390
Password: 068712
Find your local number: https://ainfosec.zoomgov.com/u/abWobTnADy

**Comment by rianquinn** [comment]
Thanks everyone for a great Community Call. If you have any questions between now and our next call in 3 months, let us know.
