### ISSUE TITLE
RTOS Linux

### ISSUE THREAD

**Issue by pfdx44** [Bareflank/hypervisor#923]
I need to run real time linux with hypervisor in Windows PC. Is it possible with your SDK?

**Comment by rianquinn** [comment]
The answer is.... sort of. Using Boxy, you can run a modified version of Linux in a VM on Windows. You are free to modify our version of Linux to include an RTOS scheduler as needed. We have never tried this before, but it should work. Currently, there is no device support in the Linux VMs, something we are working hard to remove by the end of next year (internally, we already have this working, we just need a way to upstream the work). So what this means is, you should be able to do what you want, but it would have limited usefulness until next year sometime. 

In addition... Windows itself is NOT an RTOS, and it is responsible for scheduling the VM. So, yes, you can run Linux with an RTOS scheduler, but that doesn't mean you will have any RTOS like scheduling unless you tell Windows not to schedule other activities on the same core that you are running the VM on. As with most Intel based systems, this will likely work most of the time, but if you need hard RTOS guarantees, you would be better off running a VM from UEFI and stealing the cores that you need from Windows before it boots. This is also possible using Boxy (we also do this internally), but you would need to modify the upstream code to make that work. Our goal as a project is to ensure you have the tools needed to create whatever hypervisor environment you need as easily as possible, but depending on your use case, you might still need to do some coding to get things working exactly the way you want. By next year, you should be able to do this with full device support as well.
