### ISSUE TITLE
[BUG] Win10 BSOD

### ISSUE THREAD

**Issue by liujian883** [Bareflank/hypervisor#926]
Hello,
 I use lastest Cygwin to compile the win10 version, make driver_quick command compile driver succeed, then I run make quick, encountered win10 blue screen, error code is KERNEL_SECURITY_CHECK_FAILURE

compiler: lastest VS2019 and WDK
windows version:20H2(19042.685)

thanks!

**Comment by rianquinn** [comment]
I'll be diving into Windows support for Bareflank 3.0 soon here. This will likely come up. I am not really sure what the issue is, but my guess is, we are not handling something right with the new version of Windows.

**Comment by taodaqiao** [comment]
Looking forward to the support of windows

**Comment by rianquinn** [comment]
@liujian883 @taodaqiao Windows should be working in Master now. Give it a test.
