### ISSUE TITLE
bareflank_efi_loader fails if UEFI environment does not have EFI_SHELL_PROTOCOL

### ISSUE THREAD

**Issue by tkchia** [Bareflank/hypervisor#949]
Good day,

I built the `hypervisor` code for UEFI using something along the lines of the following:
```
$ git clone --recurse-submodules https://github.com/Bareflank/hypervisor.git
$ cd hypervisor
...
$ rm -rf build
$ mkdir build
$ cd build
$ cmake -GNinja -DHYPERVISOR_BUILD_EFI=ON \
      -DFETCHCONTENT_SOURCE_DIR_BSL=".../bsl" ..
$ ninja
```

When I run the resulting `efi_cross_compile/bin/bareflank_efi_loader` under `qemu-system-x86_64` 5.2.0 with `ovmf` 2020.11, I get the following message:

![20210713-2](https://user-images.githubusercontent.com/5507843/125482227-ef78aaef-a8dd-4dce-81ba-7d5e740f3730.png)

Thank you!

**Comment by tkchia** [comment]
One possible way to resolve this &mdash; which I have used in another code base &mdash; would be to obtain a handle for the boot device, by way of the `EFI_LOADED_IMAGE_PROTOCOL` on the `ImageHandle` passed to `efi_main`.

Thank you!

**Comment by rianquinn** [comment]
@tkchia Do you want to provide a PR to fix it? I ran into the same issue on VMWare, so this is definitely something I have seen. This code was actually added recently to deal with needing to locate fs0.

**Comment by tkchia** [comment]
Hello @rianquinn,

> @tkchia Do you want to provide a PR to fix it? I ran into the same issue on VMWare, so this is definitely something I have seen. This code was actually added recently to deal with needing to locate fs0.

Thanks!  Yes, I can try to write up and submit a patch, though that might take a while.

**Comment by rianquinn** [comment]
@tkchia Thanks a ton. Let me know if you need any help

**Comment by tkchia** [comment]
Hello @rianquinn,

I have submitted my proposed patch: https://github.com/Bareflank/hypervisor/pull/950 .  Thank you!
