### ISSUE TITLE
extension and VMM modules 

### ISSUE THREAD

**Issue by xiaolongwu01** [Bareflank/hypervisor#955]
What is the difference between VMM extension and VMM modules?

**Comment by rianquinn** [comment]
Not really sure what you are referring to WRT a "VMM module" as that is not something Bareflank has. We also don't really have a VMM extension, but rather just "extensions" which are userspace applications that run on top of the microkernel that implement the VMM. The following diagram might help:

https://raw.githubusercontent.com/Bareflank/MicroV/master/.github/images/high_level.png

**Comment by xiaolongwu01** [comment]
The VMM modules is from here https://github.com/Bareflank/hypervisor/releases/tag/v1.0.0
Custom ELF loader for loading the VMM modules
I guess the bfelf_loader is for loading the VMM modules.
So what is VMM modules here?

**Comment by xiaolongwu01** [comment]
The VMM modules is from here https://github.com/Bareflank/hypervisor/releases/tag/v1.0.0
Custom ELF loader for loading the VMM modules
I guess the bfelf_loader is for loading the VMM modules.
So what is VMM modules here?

**Comment by rianquinn** [comment]
@xiaolongwu01 IIRC, this was addressed in slack
