### ISSUE TITLE
Fate of the `hypervisor` project

### ISSUE THREAD

**Issue by sskras** [Bareflank/hypervisor#981]
Hello,

I see no commits since [Oct 21, 2021](https://github.com/Bareflank/hypervisor/commit/10af879f58a0b1d9ace17b84cd9b1e41a1cc67d0).

Now with both Rian and Brendan being Senior Software Engineers at Microsoft (since Oct 2021 and May 2022 respectively), is there any chances for the project to resume its' development?

S.

**Comment by chp-io** [comment]
@sskras, thank you for your interest in this project and your concern for its ongoing development. I understand your concerns given the period of inactivity.

I was brought on by Rian before he left and I’m currently handling different versions of this project. The main repository may have an appearance of being paused, but this project is not abandoned, as we’re currently focused on downstream projects.

Your contribution and involvement in this project would be highly appreciated as well. Open source projects thrive on community engagement, and it would be great to have more hands on deck. If you are interested, there are many ways to contribute, such as code contributions, documentation, testing, or even just reporting bugs.

Thank you for reaching out and sparking this important discussion.

**Comment by sskras** [comment]
Thanks for the clear feedback, Christopher!

Well, I am of no help here with C++ being a language too foreign to me:)

The first thing I would do could learning the project fundamentals and drawing the architecture diagrams.
Then probably comparing it to the architectures of Xen and ACRN.

Cheers!
